unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonalInfoDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>個人情報開示承認の有無</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから契約会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HXmTEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Healthcheck_NOT_WB__c</fullName>
        <description>勤務先会社情報の「個人情報開示承認」が「ON」の場合にのみ「あり」にできる</description>
        <label>WB健診以外の健診結果</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>あり</fullName>
                </value>
                <value>
                    <fullName>なし</fullName>
                    <default>true</default>
                    <label>なし</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HUqkEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HuCZEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_MemberInfo_HealthCheck.cls
public class wb_MemberInfo_HealthCheck {
    private ApexPages.StandardController standardController;
    public MemberInfo__c MemberInfo {get;set;}
    public boolean 	Healthcheck_NOT_WB_Editable {get;set;}
    public boolean 	EditMode {get;set;}
    public wb_MemberInfo_HealthCheck(ApexPages.StandardController stdController){
        this.standardController = stdController;
        MemberInfo = (MemberInfo__c) stdController.getRecord();
        MemberInfo = [select Id, KinmuCompany__r.PersonalInfoDisclosure__c, 
                      CompanyKeiyakuNo__r.KeiyakuCompanyName__r.PersonalInfoDisclosure__c,
                      Healthcheck_NOT_WB__c
                      from MemberInfo__c
                      where Id =: MemberInfo.id];
        if (//MemberInfo.CompanyKeiyakuNo__r.KeiyakuCompanyName__r.PersonalInfoDisclosure__c == true ||
            MemberInfo.KinmuCompany__r.PersonalInfoDisclosure__c == true )
            {
                Healthcheck_NOT_WB_Editable = true;
            }
        else {
            Healthcheck_NOT_WB_Editable = false;
        }
        
          EditMode = false;
    }
    public void Edit(){
        EditMode = true;
    }
    public void View(){
        UpdateMemberInfo();
        EditMode = false;
    }
    
    public void UpdateMemberInfo(){
        if (MemberInfo != null)
            update MemberInfo;
    }

}