unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonalInfoDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>個人情報開示承認の有無</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>Healthcheck_NOT_WB__c</fullName>
        <label>WB健診以外の健診</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>なし</fullName>
                    <default>true</default>
                    <label>なし</label>
                </value>
                <value>
                    <fullName>あり</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>R00N10000000I9MMEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <formula>MemberShimei__r.KinmuCompany__r.Name</formula>
        <label>勤務先会社</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>FamilyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Healthcheck_NOT_WB__c</fullName>
        <description>勤務先会社情報の「個人情報開示承認」が「ON」の場合にのみ「あり」にできる</description>
        <label>WB健診以外の健診結果</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>あり</fullName>
                </value>
                <value>
                    <fullName>なし</fullName>
                    <default>true</default>
                    <label>なし</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HUqkEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HuCZEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_FamilyInfo_HealthCheck.cls
public class wb_FamilyInfo_HealthCheck {
    private ApexPages.StandardController standardController;
    public FamilyInfo__c FamilyInfo {get;set;}
    public boolean 	Healthcheck_NOT_WB_Editable {get;set;}
    public boolean 	EditMode {get;set;}
    public wb_FamilyInfo_HealthCheck(ApexPages.StandardController stdController){
        this.standardController = stdController;
        FamilyInfo = (FamilyInfo__c) stdController.getRecord();
        FamilyInfo = [select Id, MemberShimei__r.KinmuCompany__r.PersonalInfoDisclosure__c, 
                      MemberShimei__r.CompanyKeiyakuNo__r.KeiyakuCompanyName__r.PersonalInfoDisclosure__c,
                      Healthcheck_NOT_WB__c
                      from FamilyInfo__c
                      where Id =: FamilyInfo.id];
        if (//FamilyInfo.MemberShimei__r.CompanyKeiyakuNo__r.KeiyakuCompanyName__r.PersonalInfoDisclosure__c == true ||
            FamilyInfo.MemberShimei__r.KinmuCompany__r.PersonalInfoDisclosure__c == true )
        {
            Healthcheck_NOT_WB_Editable = true;
        }
        else {
            Healthcheck_NOT_WB_Editable = false;
        }
        
        EditMode = false;
    }
    public void Edit(){
        EditMode = true;
    }
    public void View(){
        UpdateFamilyInfo();
        EditMode = false;
    }
    
    public void UpdateFamilyInfo(){
        if (FamilyInfo != null)
            update FamilyInfo;
    }


}