unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CountryCd__c</fullName>
        <formula>CASE( CountryName__c , 
&quot;中国&quot;, &quot;CHN&quot;, 
&quot;香港&quot;, &quot;HKG&quot;, 
&quot;日本&quot;, &quot;JPN&quot;, 
&quot;ベトナム&quot;, &quot;VTN&quot;, 
&quot;インド&quot;, &quot;IND&quot;, 
&quot;インドネシア&quot;, &quot;IDN&quot;, 
&quot;フィリピン&quot;, &quot;PHL&quot;, 
&quot;カンボジア&quot;, &quot;KHM&quot;, 
&quot;タイ&quot;,&quot;THA&quot;, 
&quot;シンガポール&quot;,&quot;SGP&quot;, 
&quot;ミャンマー&quot;,&quot;MMR&quot;, 
&quot;スリランカ&quot;,&quot;LKA&quot;, 
&quot;韓国&quot;,&quot;KOR&quot;, 
&quot;台湾&quot;,&quot;TWN&quot;, 
&quot;マレーシア&quot;,&quot;MYS&quot;, 
&quot;ラオス&quot;,&quot;LAO&quot;, 
&quot;バングラデシュ&quot;,&quot;BGD&quot;, 
&quot;北米&quot;,&quot;GNA&quot;, 
&quot;メキシコ&quot;,&quot;MEX&quot;, 
&quot;中南米&quot;, &quot;GLA&quot;, 
&quot;欧州&quot;,&quot;GEU&quot;, 
&quot;オセアニア&quot;,&quot;GOC&quot;, 
&quot;CIS&quot;,&quot;GCI&quot;, 
&quot;中東&quot;,&quot;GME&quot;,
&quot;アフリカ&quot;,&quot;GAF&quot;, 
&quot;&quot;)</formula>
        <label>国コード</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Old_Id__c</fullName>
        <externalId>true</externalId>
        <label>旧ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>家族</relationshipLabel>
        <relationshipName>FamilyMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Old_Id__c</fullName>
        <externalId>true</externalId>
        <label>Old_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>旧会員番号</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_MemberNo__c</fullName>
        <formula>MembershipDetail__r.MemberNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>ApplicationDate__c</fullName>
        <label>申込日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>支払会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約（支払い）</relationshipLabel>
        <relationshipName>BillingMembershipContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingCountryNo__c</fullName>
        <label>請求先国番号</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingDept__c</fullName>
        <label>請求先部署</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingDistrict__c</fullName>
        <label>請求地区</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingExtNo__c</fullName>
        <label>請求先内線</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingFax__c</fullName>
        <label>請求先FAX</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BillingName__c</fullName>
        <label>請求先氏名</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingNote__c</fullName>
        <label>請求備考</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BillingTel__c</fullName>
        <label>請求先TEL</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BillingTitle__c</fullName>
        <label>請求先役職</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会社</fullName>
                </value>
                <value>
                    <fullName>個人</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractDistrict__c</fullName>
        <label>契約地区</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractExpiryDate__c</fullName>
        <label>契約満期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractIndividual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約</relationshipLabel>
        <relationshipName>IndividualContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreviousContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約</relationshipLabel>
        <relationshipName>PreviousContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>分類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>新規</fullName>
                </value>
                <value>
                    <fullName>継続</fullName>
                </value>
                <value>
                    <fullName>追加</fullName>
                </value>
                <value>
                    <fullName>交替</fullName>
                </value>
                <value>
                    <fullName>変更</fullName>
                </value>
                <value>
                    <fullName>解約変更</fullName>
                </value>
                <value>
                    <fullName>移行</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MemberNo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>人数</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>CardPrefix__c</fullName>
        <label>カード接頭</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>データタイプ</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>サービス</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_MembershipClone.cls
public class wb_MembershipClone {
    
    public id OrgMembershipId {get;set;}
    public id NextMembershipId {get;set;}
    
    public wb_Membership__c OrgMembership {get; set;}
    public wb_Membership__c NextMembership {get; set;}
    
    public List<wb_MembershipDetail__c> OrgMembershipDetails {get; set;}
    public List<wb_MembershipDetail__c> OrgMembershipDetailsParent {get; set;}
    public List<wb_MembershipDetail__c> OrgMembershipDetailsChild {get; set;}
    
    public  List<wb_Individual__c> thisIndividualMember {get; set;}
    public  List<wb_Individual__c> thisIndividualFamily {get; set;}
    public  List<wb_Member__c> ThisVisitor {get; set;}
    
    List<wb_utility_quicksort.IdIndex> OrgMembershipDetailsParentIdx;
    List<wb_utility_quicksort.IdIndex> OrgMembershipDetailsChildIdx;
    
    public List<wb_MembershipDetail__c> NextMembershipDetails {get; set;}
    
    public wb_Membership Helper {get; set;}
    
    public wb_MembershipClone( id OrgID ){
        OrgMembershipId = OrgID;
        Helper = new wb_Membership();       
        OrgMembership = Helper.getContractHeader(OrgMembershipId);
        OrgMembershipDetails = Helper.getContractDetail(OrgMembership);
        
    }
    
    
    public void start_continue(){
        //system.debug('start_clone');      
        
        OrgMembershipDetailsParent = new  List<wb_MembershipDetail__c>();
        OrgMembershipDetailsChild = new  List<wb_MembershipDetail__c>();
        
        system.debug(OrgMembershipDetails.size());
        for (wb_MembershipDetail__c d:OrgMembershipDetails){
            if (d.ParentDetail__c == null && d.CancellationDate__c == null)
                OrgMembershipDetailsParent.add(d);
            else if (d.ParentDetail__c != null && d.CancellationDate__c == null)
                OrgMembershipDetailsChild.add(d);
        }
        
        
        wb_utility_quicksort qshelper = new wb_utility_quicksort();
        
        OrgMembershipDetailsParentIdx = new List<wb_utility_quicksort.IdIndex>();
        
        OrgMembershipDetailsChildIdx = new List<wb_utility_quicksort.IdIndex>();
        system.debug(OrgMembershipDetailsParent.size());
        for (integer i=0; i < OrgMembershipDetailsParent.size();i++){
            OrgMembershipDetailsParentIdx.add( new wb_utility_quicksort.IdIndex(OrgMembershipDetailsParent[i].id,i));
        }
        system.debug(OrgMembershipDetailsParentIdx.size());
        
        for (integer i=0; i < OrgMembershipDetailsChild.size();i++){
            OrgMembershipDetailsChildIdx.add( new wb_utility_quicksort.IdIndex(OrgMembershipDetailsChild[i].ParentDetail__c,i));
        }
        

        qshelper.sortcustomObjList(OrgMembershipDetailsParentIdx);    
        qshelper.sortcustomObjList(OrgMembershipDetailsChildIdx);   
        
        Map<Id,Integer> OrgMembershipDetailsChildFirstParentIdxMap = new Map<Id,Integer>();
        
        for ( integer i=0; i < OrgMembershipDetailsChildIdx.size(); i++){
            if (i == 0){
                OrgMembershipDetailsChildFirstParentIdxMap.put(OrgMembershipDetailsChildIdx[i].Id,i);
            } else if ( OrgMembershipDetailsChildIdx[i-1].Id != OrgMembershipDetailsChildIdx[i].Id){
                OrgMembershipDetailsChildFirstParentIdxMap.put(OrgMembershipDetailsChildIdx[i].Id,i);
            }
            
        }
        
        Helper = new wb_Membership();    
        
        
        Helper = MembershipContractHeaderContinue( Helper, OrgMembership);
        
        
        system.debug(OrgMembershipDetailsParentIdx.size());
        
        List<Id> IndIDs = new List<Id>();
        List<Id> VisitorMemberIDs = new List<Id>();
        
        for ( integer p = 0; p<OrgMembershipDetailsParent.size();p++){
            if ( (OrgMembershipDetailsParent[p].Type__c == '家族' || OrgMembershipDetailsParent[p].Type__c == '単身') 
                && OrgMembershipDetailsParent[p].Individual__c != null) {
                    IndIDs.add(OrgMembershipDetailsParent[p].Individual__c);
                } else if (OrgMembershipDetailsParent[p].Type__c == '無記名'){
                    if(OrgMembershipDetailsChildFirstParentIdxMap.containsKey(OrgMembershipDetailsParent[p].Id))
                    {
                        
                        //get the index
                        Integer index = OrgMembershipDetailsChildFirstParentIdxMap.get(OrgMembershipDetailsParent[p].Id);
                        
                        system.debug(index);
                        for (integer i = index; i < OrgMembershipDetailsChildIdx.size() && 
                             OrgMembershipDetailsChildIdx[i].Id == OrgMembershipDetailsChildIdx[index].Id; i++){
                                 VisitorMemberIDs.add(OrgMembershipDetailsChild[OrgMembershipDetailsChildIdx[i].idx].Member__c);
                             }
                        
                    }
                }
            
        }
        
        
        thisIndividualMember =[select Id, name, WorkingCompany__c, Old_Id__c, Parent__c
                               from wb_Individual__c 
                               where id =:IndIDs // and id ='a0n5D000000eaemQAA'
                               order by Id];
        system.debug(thisIndividualMember);        
        
        Map<Id,Integer> MemberIdxMap = new Map<Id,Integer>();
        for ( integer i = 0; i<thisIndividualMember.size();i++){
            MemberIdxMap.put(thisIndividualMember[i].Id,i);
        }
        
        thisIndividualFamily = [select Id, name, Parent__c, Old_Id__c, Parent__r.Old_Id__c
                                from wb_Individual__c 
                                where Parent__c =:IndIDs  //and Parent__c ='a0n5D000000eaemQAA'
                                order by Parent__c desc ];
        system.debug(thisIndividualFamily);
        
        
        ThisVisitor = [select Id, Name, Old_Id__c, WorkingCompany__c, Old_MemberNo__c 
                       from wb_Member__c 
                       where Id =:VisitorMemberIDs 
                       order by WorkingCompany__c, f_MemberNo__c];
        system.debug(ThisVisitor);
        
        Map<Id,Integer> VisitorWorkingCompanyFirstIdxMap = new Map<Id,Integer>();
        
        for ( integer i=0; i < ThisVisitor.size(); i++){
            if (i == 0){
                VisitorWorkingCompanyFirstIdxMap.put(ThisVisitor[i].WorkingCompany__c,i);
            } else if ( ThisVisitor[i-1].WorkingCompany__c != ThisVisitor[i].WorkingCompany__c){
                VisitorWorkingCompanyFirstIdxMap.put(ThisVisitor[i].WorkingCompany__c,i);
            }
            
        }
        
        
        
        Map<Id,Integer> MemberFamilyFirstIdxMap = new Map<Id,Integer>();
        
        for ( integer i=0; i < thisIndividualFamily.size(); i++){
            if (i == 0){
                MemberFamilyFirstIdxMap.put(thisIndividualFamily[i].Parent__c,i);
            } else if ( thisIndividualFamily[i-1].Parent__c != thisIndividualFamily[i].Parent__c){
                MemberFamilyFirstIdxMap.put(thisIndividualFamily[i].Parent__c,i);
            }
            
        }
        system.debug(MemberFamilyFirstIdxMap);
        
        //   for ( integer p =0; p < OrgMembershipDetailsParentIdx.size() ; p ++){
        List<wb_Individual__c> Family = new List<wb_Individual__c>();
        List<wb_Member__c> Visitor;
        for ( integer p =0; p < OrgMembershipDetailsParentIdx.size() ; p ++){
            
            
            system.debug(OrgMembershipDetailsParent[p]);
            if (OrgMembershipDetailsParent[p].Type__c == '家族' || OrgMembershipDetailsParent[p].Type__c == '単身' ) {
                Integer midx = MemberIdxMap.get(OrgMembershipDetailsParent[p].Individual__c);
                
                Family = new List<wb_Individual__c>();
                if ( OrgMembershipDetailsParent[p].Type__c == '家族'){
                    system.debug(OrgMembershipDetailsParent[p]);
                    if(MemberFamilyFirstIdxMap.containsKey(OrgMembershipDetailsParent[p].Individual__c))
                    {
                        
                        //get the index
                        Integer index = MemberFamilyFirstIdxMap.get(OrgMembershipDetailsParent[p].Individual__c);
                        system.debug(index);
                        for (integer i = index; i < thisIndividualFamily.size() && 
                             thisIndividualFamily[i].Parent__c == thisIndividualFamily[index].Parent__c; i++){
                                 Family.add(thisIndividualFamily[i]);
                             }
                    }
                }
                
                Helper = MembershipContractAdd( Helper,  
                                               OrgMembershipDetailsParent[p].Type__c,
                                               Integer.Valueof(OrgMembershipDetailsParent[p].Quantity__c),
                                               OrgMembershipDetailsParent[p].Individual__c,
                                               OrgMembershipDetailsParent[p].Service__c,
                                               thisIndividualMember[midx],
                                               Family,
                                               null,
                                               null,
                                               null,
                                               null
                                              );
            }
            else if (OrgMembershipDetailsParent[p].Type__c == '無記名'){
                Visitor = new List<wb_Member__c>();
                if(VisitorWorkingCompanyFirstIdxMap.containsKey(OrgMembershipDetailsParent[p].WorkingCompany__c))
                {
                    //get the index
                    Integer index = VisitorWorkingCompanyFirstIdxMap.get(OrgMembershipDetailsParent[p].WorkingCompany__c);
                    
                    for (integer v = 0 ; v < Integer.Valueof(OrgMembershipDetailsParent[p].Quantity__c); v ++){
                        if (ThisVisitor[index + v].WorkingCompany__c == OrgMembershipDetailsParent[p].WorkingCompany__c)
                            Visitor.add(ThisVisitor[index + v]);
                    }
                    
                }
                
                Helper = MembershipContractAdd( Helper,  
                                               OrgMembershipDetailsParent[p].Type__c,
                                               Integer.Valueof(OrgMembershipDetailsParent[p].Quantity__c),
                                               null,
                                               OrgMembershipDetailsParent[p].Service__c,
                                               null,
                                               null,
                                               OrgMembershipDetailsParent[p].WorkingCompany__c,
                                               Integer.Valueof(OrgMembershipDetailsParent[p].Quantity__c),
                                               Visitor,
                                               OrgMembershipDetailsParent[p].WorkingCompany__r.CountryCd__c
                                              );
                
                
            }
            
            
        }
        
        system.debug(Helper.MembershipDetailsParent);
        
    }
    
    public wb_Membership MembershipContractHeaderContinue(wb_Membership NextMS, wb_Membership__c ThisMSH ){
        
        date s;
        s=ThisMSH.ContractExpiryDate__c;
        s=s.addYears(1);
        
        NextMS.Membership.Status__c = '未確定';
        NextMS.Membership.ContractCompany__c = ThisMSH.ContractCompany__c;
        NextMS.GetGroupDiscountPercentage();
        NextMS.Membership.Classification__c ='会社';
        NextMS.Membership.BillingCompany__c = ThisMSH.BillingCompany__c;
        NextMS.Membership.ContractCountry__c =ThisMSH.ContractCountry__c;
        NextMS.Membership.ContractDistrict__c = ThisMSH.ContractDistrict__c;
        NextMS.Membership.BillingDistrict__c = ThisMSH.BillingDistrict__c;
        NextMS.Membership.Currency__c = ThisMSH.Currency__c;
        NextMS.Membership.ContractDate__c = system.today();
        NextMS.Membership.ApplicationDate__c = system.today();
        NextMS.Membership.ContractExpiryDate__c = s;
        NextMS.Membership.BillingCompany__c = ThisMSH.BillingCompany__c;
        NextMS.Membership.BillingNote__c = ThisMSH.BillingNote__c;
        NextMS.Membership.BillingFax__c = ThisMSH.BillingFax__c;
        NextMS.Membership.BillingTel__c = ThisMSH.BillingTel__c; 
        NextMS.Membership.BillingExtNo__c = ThisMSH.BillingExtNo__c; 
        NextMS.Membership.BillingCountryNo__c = ThisMSH.BillingCountryNo__c; 
        NextMS.Membership.BillingTitle__c = ThisMSH.BillingTitle__c;
        NextMS.Membership.BillingName__c = ThisMSH.BillingName__c;
        NextMS.Membership.BillingDept__c = ThisMSH.BillingDept__c;
        NextMS.Membership.BillingDistrict__c = ThisMSH.BillingDistrict__c;  

        NextMS.Membership.ContractIndividual__c  = ThisMSH.ContractIndividual__c;
        NextMS.Membership.PreviousContract__c = ThisMSH.Id;

        NextMS.RateAndRoundUp = NextMS.getRateAndRoundUp();
        return NextMS;
    }
    
    public wb_Membership MembershipContractAdd( wb_Membership MS,
                                               string Type, 
                                               integer Qty, 
                                               Id IndID, 
                                               Id ServiceID,
                                               wb_Individual__c theIndividual, 
                                               List<wb_Individual__c> theFamily,
                                               Id VisitorWorkingCompId, 
                                               Integer VisitorQty, 
                                               List<wb_Member__c> CardHolders,
                                               string CountryCode
                                              ){
                                                  wb_Service__c theService;
                                                  system.debug(MS.MembershipDetailsParent);
                                                  /*if (Type == '入会金'){
MS.theMembershipDetail[0].theRow.Membership__c = MS.Membership.id;
MS.theMembershipDetail[0].selectedValue = '1';
MS.theMembershipDetail[0].fetchServiceOptions();

for (wb_Service__c s:MS.MDService) {
if (s.DATATYPE__C =='入会金')
theService = s;
}
MS.theMembershipDetail[0].theRow.Service__c = theService.id;
MS.theMembershipDetail[0].theRow.Quantity__c= Qty;
MS.theMembershipDetail[0].fetchServiceFee();

}
else */
                                                  if (Type == '単身'){
                                                      integer ps = MS.MembershipDetailsParent.size();
                                                      //   system.debug(ps);
                                                      for (wb_Service__c s:MS.MDService) {
                                                          //if (s.SERVICE__C == 'Global Member' && s.DATATYPE__C=='単身' )
                                                          if (s.id == ServiceID )
                                                              theService = s;
                                                      }
                                                      
                                                      
                                                      MS.add_empty_row();
                                                      
                                                      MS.theIndividualList =IndID;
                                                      MS.theServiceList=theService.Id;
                                                      MS.theStartRowIndex= ps ;
                                                      MS.theStartRowID='';
                                                      //MS.UpdateAndInsertRow_at();
                                                      MS.UpdateAndInsertRow_at(theIndividual,null);
                                                      MS.theMembershipDetail[ps].theRow.Classification__c ='継続';
                                                      
                                                      
                                                  } 
                                                  else if (Type == '家族'){
                                                      integer ps = MS.MembershipDetailsParent.size();
                                                      for (wb_Service__c s:MS.MDService) {
                                                          // if (s.SERVICE__C == 'Global Member' && s.DATATYPE__C=='家族' )
                                                          if (s.id == ServiceID )
                                                              theService = s;
                                                      }
                                                      
                                                      
                                                      MS.add_empty_row();
                                                      MS.theIndividualList =IndID;
                                                      MS.theServiceList=ServiceID;
                                                      MS.theStartRowIndex= ps ;
                                                      MS.theStartRowID='';
                                                      //  MS.UpdateAndInsertRow_at();
                                                      MS.UpdateAndInsertRow_at(theIndividual,theFamily);
                                                      MS.theMembershipDetail[ps].theRow.Classification__c ='継続';
                                                  }
                                                  else if (Type == '無記名'){
                                                      integer ps = MS.MembershipDetailsParent.size();
                                                      for (wb_Service__c s:MS.MDService) {
                                                          // if (s.SERVICE__C == 'Biz Trip Pass' && s.DATATYPE__C=='無記名' )
                                                          //     theService = s;
                                                          if (s.id == ServiceID )
                                                              theService = s;
                                                      }
                                                      
                                                      MS.add_empty_row();
                                                      MS.theMembershipDetail[ps].selectedValue = '3';
                                                      MS.theMembershipDetail[ps].fetchServiceOptions();
                                                      MS.theMembershipDetail[ps].theRow.Service__c = theService.id;
                                                      MS.theMembershipDetail[ps].theRow.Type__c = theService.DATATYPE__C;
                                                      MS.theMembershipDetail[ps].theRow.MembershipPlan__c = theService.Service__c;
                                                      MS.theMembershipDetail[ps].theRow.WorkingCompany__c = VisitorWorkingCompId;
                                                      MS.theMembershipDetail[ps].theRow.Quantity__c= VisitorQty;
                                                      MS.theMembershipDetail[ps].fetchServiceFee();
                                                      MS.theMembershipDetail[ps].theRow.Classification__c ='継続';
                                                      //   for (wb_member__c nm : CardHolders) {
                                                      if (CardHolders != null ) {
                                                          for ( integer i = 0; i < CardHolders.size(); i++ ){
                                                              
                                                              //     if (CardHolders[i].Parent.Id == nm.MembershipDetail__c  ){
                                                              string MemberNo;
                                                              if ( CardHolders[i].Old_MemberNo__c != null )
                                                                  MemberNo = theService.CardPrefix__c + 
                                                                  CountryCode +  CardHolders[i].Old_MemberNo__c + '0';
                                                              else
                                                                  MemberNo = theService.CardPrefix__c + 
                                                                  CountryCode +  CardHolders[i].name + '0';
                                                              
                                                              //    integer subno =  CardHolder[i].GetNoofChild() + 1;
                                                              wb_MembershipDetail__c NCH = new wb_MembershipDetail__c(Name=  MS.theMembershipDetail[ps].theRow.name , 
                                                                                                                      WorkingCompany__c = VisitorWorkingCompId,
                                                                                                                      Type__c = MS.theMembershipDetail[ps].theRow.Type__c,
                                                                                                                      Member__c = CardHolders[i].Id,
                                                                                                                      MemberNo__c = MemberNo,
                                                                                                                      Membership__c =  MS.theMembershipDetail[ps].theRow.Membership__c,
                                                                                                                      Service__c = MS.theMembershipDetail[ps].theRow.Service__c,
                                                                                                                      MembershipPlan__c = MS.theMembershipDetail[ps].theRow.MembershipPlan__c,
                                                                                                                      Quantity__c = 1,
                                                                                                                      MembershipStartDate__c = MS.theMembershipDetail[ps].theRow.MembershipStartDate__c,
                                                                                                                      MembershipEndDate__c = MS.theMembershipDetail[ps].theRow.MembershipEndDate__c,
                                                                                                                      // ParentDetail__c = CardHolder[i].Parent.id
                                                                                                                      Classification__c ='継続'
                                                                                                                     );
                                                              //  insert NCH;
                                                              MS.MembershipDetailsChild.add(NCH);
                                                              
                                                          }
                                                      }
                                                      
                                                  }
                                                  MS.removeEmptyRow();
                                                  system.debug(MS.MembershipDetailsParent);
                                                  return MS;
                                              }
    
}