unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AffiliatedCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業グループ</label>
        <referenceTo>AffiliatedCompany__c</referenceTo>
        <relationshipLabel>会社情報</relationshipLabel>
        <relationshipName>R00N10000000uu4tEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Busho__c</fullName>
        <label>メディック担当者部署</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyCd__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>会社コード</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CompanyNameEng__c</fullName>
        <inlineHelpText>ローマ字入力ではなく、英文名称がわかる場合のみ入力します。</inlineHelpText>
        <label>会社名称(英語名)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（営業担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmmEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>同一の団体割引を適用するグループがある場合に選択します。</inlineHelpText>
        <label>割引グループ</label>
        <referenceTo>GroupName__c</referenceTo>
        <relationshipLabel>会社情報</relationshipLabel>
        <relationshipName>R00N10000000HYkvEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（内務担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmrEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfficeAdd__c</fullName>
        <label>住所</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>President__c</fullName>
        <label>代表者</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shimei__c</fullName>
        <label>メディック担当者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubBusho__c</fullName>
        <label>メディック実務担当部署</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShimei__c</fullName>
        <label>メディック実務担当</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubYakushoku__c</fullName>
        <label>メディック実務担当役職</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yakushoku__c</fullName>
        <label>メディック担当者役職</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Shimei__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>現住所</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Busho__c</fullName>
        <label>部署</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>営業</fullName>
                </value>
                <value>
                    <fullName>総合サービス</fullName>
                </value>
                <value>
                    <fullName>危機管理情報</fullName>
                </value>
                <value>
                    <fullName>商品企画開発</fullName>
                </value>
                <value>
                    <fullName>健診</fullName>
                </value>
                <value>
                    <fullName>医療保険査定</fullName>
                </value>
                <value>
                    <fullName>自動車保険査定</fullName>
                </value>
                <value>
                    <fullName>公估</fullName>
                </value>
                <value>
                    <fullName>事務管理</fullName>
                </value>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>人事総務</fullName>
                </value>
                <value>
                    <fullName>財務</fullName>
                </value>
                <value>
                    <fullName>教育研修</fullName>
                </value>
                <value>
                    <fullName>業務統括</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>Global Business</fullName>
                </value>
                <value>
                    <fullName>システム</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>携帯電話番号</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SeiMeiRoma__c</fullName>
        <formula>MeiRoma__c &amp;&quot; &quot;&amp; SeiRoma__c</formula>
        <label>姓名（ローマ字）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tel__c</fullName>
        <label>TEL</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Yakushoku__c</fullName>
        <label>役職</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>代表取締役</fullName>
                </value>
                <value>
                    <fullName>取締役</fullName>
                </value>
                <value>
                    <fullName>執行役員</fullName>
                </value>
                <value>
                    <fullName>董事</fullName>
                </value>
                <value>
                    <fullName>監事</fullName>
                </value>
                <value>
                    <fullName>本部長</fullName>
                </value>
                <value>
                    <fullName>営業総監</fullName>
                </value>
                <value>
                    <fullName>所長</fullName>
                </value>
                <value>
                    <fullName>支店長</fullName>
                </value>
                <value>
                    <fullName>部長</fullName>
                </value>
                <value>
                    <fullName>次長</fullName>
                </value>
                <value>
                    <fullName>課長</fullName>
                </value>
                <value>
                    <fullName>総経理</fullName>
                </value>
                <value>
                    <fullName>主任</fullName>
                </value>
                <value>
                    <fullName>リーダー</fullName>
                </value>
                <value>
                    <fullName>Managing Director</fullName>
                </value>
                <value>
                    <fullName>President Director</fullName>
                </value>
                <value>
                    <fullName>General Director</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>社員名簿</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>メールアドレス</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstNameRoma__c</fullName>
        <label>名（ローマ字）</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailDelivery__c</fullName>
        <defaultValue>false</defaultValue>
        <label>メール配信</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>携帯TEL</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tel__c</fullName>
        <label>TEL</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractDistrict__c</fullName>
        <label>契約地区</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractExpiryDate__c</fullName>
        <label>契約満期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountPercentage__c</fullName>
        <label>割引率</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <label>適用割引率種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>グループ</fullName>
                </value>
                <value>
                    <fullName>団体</fullName>
                </value>
                <value>
                    <fullName>優良</fullName>
                </value>
                <value>
                    <fullName>グループ・団体</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InternalAffairs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>内務担当</label>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会員契約 (内務担当)</relationshipLabel>
        <relationshipName>MDMemebrContractPIC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会員契約</relationshipLabel>
        <relationshipName>ResponsibleMenbershipContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_MDContractInvoice.cls
global with sharing class wb_MDContractInvoice {
    public wb_Membership__c theContract {get;set;} 
    public  List<wb_MembershipDetail__c> theContractDetail {get;set;} 
    public string filename  {get;set;}
    
    public String xlsHeader{
        get{
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
    public void getURLparameters(){
        
        if (apexpages.currentpage() != null ) {
            if (apexpages.currentpage().getparameters().get('Id') !='') {
                Id theId = apexpages.currentpage().getparameters().get('Id');
                theContract = [select Id, Name from wb_Membership__c where id=:theId];
            }
        }
    }
        

    
    public wb_MDContractInvoice() {
        
        getURLparameters();
        
        If (theContract != null){
            filename  = 'MDContractData' + theContract.name + '.xls' ;
        } else
            filename  = 'MDContractData.xls';
        
        
      //  wb_Membership__c c = [select Id from wb_Membership__c where id ='a0o5D000000Q41X'];
        
        getHeader(theContract);
        getDetail(theContract);
    }
    
    public wb_MDContractInvoice( wb_Membership__c c ) {
               
        
    }
    
    public void getHeader(wb_Membership__c c){
        theContract = [select Id,
                       ContractDistrict__c,
                       Name,
                       //  ContractCompany__c,
                       ContractCompany__r.CompanyCd__c,
                       //  ContractCompany__r.name,
                       ContractExpiryDate__c,
                       ContractCompany__r.EigyoTanto__c,
                       ContractCompany__r.NaimuTanto__c,
                       Sales__c,
                       InternalAffairs__c,
                       DiscountType__c,
                       DiscountPercentage__c,
                       ContractCompany__r.Id,
                       ContractCompany__r.Name,
                       ContractCompany__r.CompanyNameEng__c,
                       ContractCompany__r.OfficeAdd__c,
                       ContractCompany__r.Phone,
                       ContractCompany__r.Fax,
                       ContractCompany__r.President__c,
                       ContractCompany__r.Shimei__c,
                       ContractCompany__r.Busho__c,
                       ContractCompany__r.Yakushoku__c,
                       ContractCompany__r.SubShimei__c,
                       ContractCompany__r.SubBusho__c,
                       ContractCompany__r.SubYakushoku__c,
                       Sales__r.Name, 
                       Sales__r.SeiMeiRoma__c,  
                       InternalAffairs__r.Name,
                       InternalAffairs__r.SeiMeiRoma__c,
                       
                       // CompanyKeiyakuNo__r.SeikyuCompanyName__r.Name, 
                       //   CompanyKeiyakuNo__r.SeikyuCompanyName__r.CompanyNameEng__c, 
                       ContractCompany__r.AffiliatedCompanyName__r.Name,
                       ContractCompany__r.AffiliatedCompanyName__r.AffiliatedCompanyNameEng__c,
                       ContractCompany__r.GroupName__r.Name,
                       ContractCompany__r.GroupName__r.GroupNameEng__c
                       
                       from wb_Membership__c where id =: c.id];
    }
    
    public void getDetail(wb_Membership__c c){
        theContractDetail = [select Id, Name, 
                             Individual__r.name,
                             Individual__r.FirstNameRoma__c,  MemberNo__c, 
                             MembershipPlan__c,  MembershipEndDate__c,  Individual__r.Address__c,   Individual__r.Tel__c, 
                             Individual__r.Mobile__c,  
                             Individual__r.EmailAddress__c, Individual__r.MailDelivery__c,
                             WorkingCompany__r.Id, 
                             WorkingCompany__r.Name, 
                             WorkingCompany__r.CompanyNameEng__c,
                             WorkingCompany__r.OfficeAdd__c, 
                             WorkingCompany__r.Phone,
                             WorkingCompany__r.Fax, 
                             WorkingCompany__r.President__c, 
                             WorkingCompany__r.Shimei__c, 
                             WorkingCompany__r.Busho__c, 
                             WorkingCompany__r.Yakushoku__c, 
                             WorkingCompany__r.SubShimei__c, 
                             WorkingCompany__r.SubBusho__c,
                             WorkingCompany__r.SubYakushoku__c,
                             WorkingCompany__r.EigyoTanto__r.SeiMeiRoma__c, 
                             WorkingCompany__r.EigyoTanto__r.Name, 
                             WorkingCompany__r.NaimuTanto__r.SeiMeiRoma__c, 
                             WorkingCompany__r.NaimuTanto__r.Name
                             from wb_MembershipDetail__c
                             where Membership__c =: c.id];
        
    }
    
}