unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonalInfoDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>個人情報開示承認の有無</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <label>エリア</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>アジア</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>BudgetRate__c</fullName>
        <label>予算レート</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>LKR</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>南京</fullName>
                </value>
                <value>
                    <fullName>合肥</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
                <value>
                    <fullName>東京</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから契約会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HXmTEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuDate__c</fullName>
        <label>契約日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <formula>TEXT(KeiyakuCompanyName__r.Region_and_Area__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（会社情報）エリア</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyuArea__c</fullName>
        <label>請求書発行地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
                <value>
                    <fullName>コロンボ</fullName>
                </value>
                <value>
                    <fullName>クアラルンプール</fullName>
                </value>
                <value>
                    <fullName>バンコク</fullName>
                </value>
                <value>
                    <fullName>メキシコシティ</fullName>
                </value>
                <value>
                    <fullName>東京</fullName>
                </value>
                <value>
                    <fullName>大阪</fullName>
                </value>
                <value>
                    <fullName>名古屋</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SeikyuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから請求会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>請求先会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (請求先会社名称)</relationshipLabel>
        <relationshipName>R00N10000000Htk4EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>R00N10000000I9MMEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuDate__c</fullName>
        <formula>MemberShimei__r.KeiyakuDate__c</formula>
        <label>契約日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>続柄</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>夫</fullName>
                </value>
                <value>
                    <fullName>妻</fullName>
                </value>
                <value>
                    <fullName>息子</fullName>
                </value>
                <value>
                    <fullName>娘</fullName>
                </value>
                <value>
                    <fullName>父</fullName>
                </value>
                <value>
                    <fullName>母</fullName>
                </value>
                <value>
                    <fullName>兄弟</fullName>
                </value>
                <value>
                    <fullName>姉妹</fullName>
                </value>
                <value>
                    <fullName>親戚</fullName>
                </value>
                <value>
                    <fullName>知人</fullName>
                </value>
                <value>
                    <fullName>飼犬</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HUqkEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuDate__c</fullName>
        <label>契約日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>続柄</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>会員本人</fullName>
                    <default>true</default>
                    <label>会員本人</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_BudgetRate__c.object
<CustomObject>
    <description>WellBe Budget Exchange Rates</description>
    <fields>
        <fullName>FromDate__c</fullName>
        <label>開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>レート</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ToCurrency__c</fullName>
        <label>切替通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToDate__c</fullName>
        <label>終了日</label>
        <type>Date</type>
    </fields>
    <label>予算レート</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>予算レート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_MemberInfo_HealthCheck_Test.cls
@isTest
public class wb_MemberInfo_HealthCheck_Test {
  

    @isTest static void wb_MemberInfo_HealthCheck_Test() {
     
        Test.startTest();
         List<ContractInfo__c> contract;
        Account a = new Account(name='ABC',PersonalInfoDisclosure__c=true);
        insert a;
        DateTime dT = System.now();
        DateTime fD = dT.addDays(-30);
        DateTime tD = dT.addDays(30);
        Date fDate = date.newinstance(fD.year(), fD.month(), fD.day());
        Date tDate = date.newinstance(tD.year(), tD.month(), tD.day());
        
        wb_BudgetRate__c r = new wb_BudgetRate__c(ToCurrency__c='JPY', Rate__c = 120.3, FromDate__c= fDate, ToDate__c=tDate);
        insert r;
        ContractInfo__c c = new ContractInfo__c(KeiyakuArea__c='北京',SeikyuArea__c='東京',
                                                MankiDate__c=Date.today(),KeiyakuDate__c=Date.today(),
                                                Currency__c = 'JPY',
                                                KeiyakuCompanyName__c=a.id,SeikyuCompanyName__c=a.id );
        //contract = new List<ContractInfo__c>();

       // contract.add(c);
        insert c;
        ContractInfo__c con = [select BudgetRate__c from ContractInfo__c where id =:c.id ];
          MemberInfo__c MemberInfo = new MemberInfo__c( NAME='BEF',
                                                     MANKIDATE__C = system.today(),
                                                     KEIYAKUDATE__C=system.today(),
         											 COMPANYKEIYAKUNO__C=c.id,
                                                     KEIYAKUCOMPANYNAME__C=a.id,
                                                     RELATIONSHIP__C='会員本人',
                                                     REGION_AND_AREA__C='アジア',
                                                     COMMODITY__C='メディック',
                                                     KEIYAKUKEITAI__C='法人／家族Global Plus Member',
                                                     SHOZOKUAREA__C='香港',
                                                     JURISDICTION__C='香港',
                                                     KINMUCOMPANY__C=a.id,
                                                     COUNTRYNAME__C='香港',
                                                       SeiRoma__c='A', MeiRoma__c='B'
                                                    );
        insert MemberInfo;
        
        FamilyInfo__c FamilyInfo = new FamilyInfo__c( NAME='BEF-W',
                                                    // MANKIDATE__C = system.today(),
                                                    // KEIYAKUDATE__C=system.today(),
                                                    // COMPANYKEIYAKUNO__C=c.id,
                                                    // KEIYAKUCOMPANYNAME__C=a.id,
                                                     RELATIONSHIP__C='妻',
                                                     MemberShimei__c =MemberInfo.id,
                                                     REGION_AND_AREA__C='アジア',
                                                     COMMODITY__C='メディック',
                                                   //  KEIYAKUKEITAI__C='法人／単身Global Plus Member',
                                                     SHOZOKUAREA__C='香港',
                                                     JURISDICTION__C='香港',
                                                    // KINMUCOMPANY__C=a.id,
                                                     COUNTRYNAME__C='香港',
                                                     SeiRoma__c='A', MeiRoma__c='B'
                                                    );
           insert FamilyInfo;
        PageReference pageRef = Page.wb_Service;
        Test.setCurrentPage(pageRef);
        system.debug(MemberInfo);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(MemberInfo);
        
        wb_MemberInfo_HealthCheck sc_a = new wb_MemberInfo_HealthCheck(sc);
        sc_a.MemberInfo = MemberInfo;
        sc_a.Edit();
        sc_a.View();
        
        PageReference pageRef2 = Page.wb_Service;
        Test.setCurrentPage(pageRef2);
        system.debug(FamilyInfo);
        ApexPages.Standardcontroller sc2 = new ApexPages.Standardcontroller(FamilyInfo);
        
        wb_FamilyInfo_HealthCheck sc_2 = new wb_FamilyInfo_HealthCheck(sc2);
        sc_2.FamilyInfo = FamilyInfo;
        sc_2.Edit();
        sc_2.View();
       

    }
    
}