unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Busho__c</fullName>
        <label>メディック担当者部署</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficeAdd__c</fullName>
        <label>住所</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficePostcd__c</fullName>
        <label>郵便番号</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>President__c</fullName>
        <label>代表者</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shimei__c</fullName>
        <label>メディック担当者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubBusho__c</fullName>
        <label>メディック実務担当部署</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShimei__c</fullName>
        <label>メディック実務担当</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubYakushoku__c</fullName>
        <label>メディック実務担当役職</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yakushoku__c</fullName>
        <label>メディック担当者役職</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Shimei__c.object
<CustomObject>
    <fields>
        <fullName>Busho__c</fullName>
        <label>部署</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>営業</fullName>
                </value>
                <value>
                    <fullName>総合サービス</fullName>
                </value>
                <value>
                    <fullName>危機管理情報</fullName>
                </value>
                <value>
                    <fullName>商品企画開発</fullName>
                </value>
                <value>
                    <fullName>健診</fullName>
                </value>
                <value>
                    <fullName>医療保険査定</fullName>
                </value>
                <value>
                    <fullName>自動車保険査定</fullName>
                </value>
                <value>
                    <fullName>公估</fullName>
                </value>
                <value>
                    <fullName>事務管理</fullName>
                </value>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>人事総務</fullName>
                </value>
                <value>
                    <fullName>財務</fullName>
                </value>
                <value>
                    <fullName>教育研修</fullName>
                </value>
                <value>
                    <fullName>業務統括</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>Global Business</fullName>
                </value>
                <value>
                    <fullName>システム</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yakushoku__c</fullName>
        <label>役職</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>代表取締役</fullName>
                </value>
                <value>
                    <fullName>取締役</fullName>
                </value>
                <value>
                    <fullName>執行役員</fullName>
                </value>
                <value>
                    <fullName>董事</fullName>
                </value>
                <value>
                    <fullName>監事</fullName>
                </value>
                <value>
                    <fullName>本部長</fullName>
                </value>
                <value>
                    <fullName>営業総監</fullName>
                </value>
                <value>
                    <fullName>所長</fullName>
                </value>
                <value>
                    <fullName>支店長</fullName>
                </value>
                <value>
                    <fullName>部長</fullName>
                </value>
                <value>
                    <fullName>次長</fullName>
                </value>
                <value>
                    <fullName>課長</fullName>
                </value>
                <value>
                    <fullName>総経理</fullName>
                </value>
                <value>
                    <fullName>主任</fullName>
                </value>
                <value>
                    <fullName>リーダー</fullName>
                </value>
                <value>
                    <fullName>Managing Director</fullName>
                </value>
                <value>
                    <fullName>President Director</fullName>
                </value>
                <value>
                    <fullName>General Director</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>社員名簿</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_Account.cls
@RestResource(urlMapping='/Account/*')
global with sharing class wb_soap_Account {
    global class Company{
        global string Id; 
        global string Name;
        global string OfficePostcd;
        global string OfficeAdd;
        global string Message;
        
        public Company( id theId, string theName, 
                       string theOfficePostcd, string theOfficeAdd, string theMessage )
        {
            Id = theId; 
            Name= theName;
            OfficePostcd = theOfficePostcd;
            OfficeAdd=theOfficeAdd;
            Message= theMessage;
        }
    }
    
    @HttpGet
    global static List<Company> getCompany() {
        
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String req = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        system.debug('req:'+req);
        if ( req.indexOf('=') > 1){
            string reqType = req.left( req.indexOf('='));
            string reqInfo = req.right(req.length() - req.indexOf('=') - 1);
            if ( reqType=='LIST') {
                return GetCompanyList(reqInfo);
            } else if ( reqType=='ID')
                return GetCompany(Id.valueOf(reqInfo));
            else 
                return null;
        } else
            return null;            
        

    }
    
    public static List<Company> GetCompanyList(string Info){
        List<Company> CompanyList = new List<Company>();
        for ( Account a:[select id, name from Account order by lastmodifieddate desc limit 10]){
            CompanyList.add( new Company(a.id, a.name, null, null,null));
        }
        return CompanyList;
    }
    
     public static List<Company> GetCompany(Id CompID){
         List<Company> CompanyList = new List<Company>();
         account a =[select id, name, OfficePostcd__c,OfficeAdd__c,President__c,Phone,Fax,Busho__c,Yakushoku__c,Shimei__c,SubBusho__c,SubYakushoku__c,SubShimei__c
                     from account where id =:CompID];
         CompanyList.add( new Company(a.id, a.name, a.OfficePostcd__c, a.OfficeAdd__c, null));
         return CompanyList;
     }
    
    @HttpPatch
    global static List<Company> updateCompany(String CompanyId, String OfficePostcd) {
        List<Company> CompanyList = new List<Company>();
        try {
            account a =[select id, name, OfficePostcd__c,OfficeAdd__c,President__c,Phone,Fax,Busho__c,Yakushoku__c,Shimei__c,SubBusho__c,SubYakushoku__c,SubShimei__c
                        from account where id =:CompanyId];
            if ( a != null)
                a.OfficePostcd__c = OfficePostcd;
            update a;
            CompanyList.add(new Company(a.id, a.name, a.OfficePostcd__c, a.OfficeAdd__c,'update success'));
            return CompanyList;
        }
        catch(Exception e) {
            CompanyList.add(new Company(CompanyId, null, OfficePostcd, null,'update failed'));
            return CompanyList;
        }
 
    }

}