unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BlShimei__c</fullName>
        <label>BL担当者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficeAdd__c</fullName>
        <label>住所</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/BL__c.object
<CustomObject>
    <fields>
        <fullName>BranchOfInsurance__c</fullName>
        <label>保険種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>財産保険</fullName>
                </value>
                <value>
                    <fullName>財産一切保険</fullName>
                </value>
                <value>
                    <fullName>公衆責任保険</fullName>
                </value>
                <value>
                    <fullName>機械保険</fullName>
                </value>
                <value>
                    <fullName>現金保険</fullName>
                </value>
                <value>
                    <fullName>コンピュータ保険</fullName>
                </value>
                <value>
                    <fullName>オフィスパッケージ</fullName>
                </value>
                <value>
                    <fullName>団体傷害/医療保険</fullName>
                </value>
                <value>
                    <fullName>雇主責任保険</fullName>
                </value>
                <value>
                    <fullName>雇主工傷</fullName>
                </value>
                <value>
                    <fullName>PL保険</fullName>
                </value>
                <value>
                    <fullName>職業責任</fullName>
                </value>
                <value>
                    <fullName>店舗賠償責任</fullName>
                </value>
                <value>
                    <fullName>総合賠償責任保険</fullName>
                </value>
                <value>
                    <fullName>物流</fullName>
                </value>
                <value>
                    <fullName>運送賠償</fullName>
                </value>
                <value>
                    <fullName>ゴルファー</fullName>
                </value>
                <value>
                    <fullName>住宅総合</fullName>
                </value>
                <value>
                    <fullName>利益保険</fullName>
                </value>
                <value>
                    <fullName>建設工事保険</fullName>
                </value>
                <value>
                    <fullName>組立工事保険</fullName>
                </value>
                <value>
                    <fullName>逆OTA</fullName>
                </value>
                <value>
                    <fullName>個人意外傷害</fullName>
                </value>
                <value>
                    <fullName>食品責任保険</fullName>
                </value>
                <value>
                    <fullName>信用保険</fullName>
                </value>
                <value>
                    <fullName>OTA（香港）</fullName>
                </value>
                <value>
                    <fullName>自動車保険(香港)</fullName>
                </value>
                <value>
                    <fullName>操業停止損害保険（香港）</fullName>
                </value>
                <value>
                    <fullName>搭乗者傷害保険（香港）</fullName>
                </value>
                <value>
                    <fullName>バイク保険</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>保険料通貨</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsuranceAmount__c</fullName>
        <label>保険料</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InsuranceCompanyName__c</fullName>
        <label>保険会社名称</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>損保ジャパン（中国）</fullName>
                </value>
                <value>
                    <fullName>三井住友（中国）</fullName>
                </value>
                <value>
                    <fullName>日本興亜（中国）</fullName>
                </value>
                <value>
                    <fullName>東京海上日動（中国）</fullName>
                </value>
                <value>
                    <fullName>あいおい（中国）</fullName>
                </value>
                <value>
                    <fullName>平安</fullName>
                </value>
                <value>
                    <fullName>太平洋</fullName>
                </value>
                <value>
                    <fullName>PICC</fullName>
                </value>
                <value>
                    <fullName>民安（中国）</fullName>
                </value>
                <value>
                    <fullName>華泰財産</fullName>
                </value>
                <value>
                    <fullName>中国人寿財産</fullName>
                </value>
                <value>
                    <fullName>陽光人寿</fullName>
                </value>
                <value>
                    <fullName>平安養老</fullName>
                </value>
                <value>
                    <fullName>美亜（AIG）</fullName>
                </value>
                <value>
                    <fullName>LIBERTY（香港）</fullName>
                </value>
                <value>
                    <fullName>AIA（香港）</fullName>
                </value>
                <value>
                    <fullName>AIU（香港）</fullName>
                </value>
                <value>
                    <fullName>AXA（香港）</fullName>
                </value>
                <value>
                    <fullName>BlueCross（香港）</fullName>
                </value>
                <value>
                    <fullName>民安（香港）</fullName>
                </value>
                <value>
                    <fullName>三井住友（香港）</fullName>
                </value>
                <value>
                    <fullName>日本興亜（香港）</fullName>
                </value>
                <value>
                    <fullName>PICC（香港）</fullName>
                </value>
                <value>
                    <fullName>損保ジャパン（香港）</fullName>
                </value>
                <value>
                    <fullName>東京海上日動（香港）</fullName>
                </value>
                <value>
                    <fullName>Zurich（香港）</fullName>
                </value>
                <value>
                    <fullName>AIG（香港）</fullName>
                </value>
                <value>
                    <fullName>SJNK（香港）</fullName>
                </value>
                <value>
                    <fullName>UIC</fullName>
                </value>
                <value>
                    <fullName>MALAYAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsuranceContent__c</fullName>
        <label>種目詳細</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InsuranceManki__c</fullName>
        <inlineHelpText>OPEN POLICYの場合
満期日があるものは、
満期日を入力し、
満期日がないものは、
空欄にしてください。</inlineHelpText>
        <label>保険満期（24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InsuranceShiki__c</fullName>
        <label>保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>保険種目</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約者（被保険者）</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BL(契約者（被保険者）)</relationshipLabel>
        <relationshipName>BL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BL (契約会社名称)</relationshipLabel>
        <relationshipName>BL1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NoticeTanto__c</fullName>
        <label>通知担当者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>BL</label>
    <nameField>
        <displayFormat>BL{000000}</displayFormat>
        <label>BL番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_BLs_List_Export.cls
public class wb_BLs_List_Export {
    ApexPages.StandardController Controller;
    public string myName{get;set;} // The Output file name
    
    public List<BLsList> theBLsList{get;set;} 
    
    public class BLsList {
        
        public List<Header> theHeader{get;set;} 
        public List<wb_bl_Insurance> InsuraceList{get;set;}
        
        BLsList( ){
            theHeader = new  List<Header>();
            InsuraceList = new List<wb_bl_Insurance>();
//            theHeader = H;
//            InsuraceList = D;
        }
        
        public void Fill( string BLid ){
           // system.debug('BLid:' + BLid);
            
            BL__c b = [select KeiyakuCompanyName__r.name, KeiyakuCompanyName__r.OfficeAdd__c,
                       Insurant__r.name, Insurant__r.OfficeAdd__c, 
                       NoticeTanto__c, KeiyakuCompanyName__r.BlShimei__c,
                       InsuranceCompanyName__c, InsuranceShiki__c, InsuranceManki__c, Insurance__c, InsuranceContent__c,  Currency__c, InsuranceAmount__c
                       from BL__c where id =:BLid ];
            theHeader = new List<Header>();
            String type='BL__c';
            Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
            Schema.SObjectType leadSchema = schemaMap.get(type);
            Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
            
            theHeader.add( new Header(fieldMap.get('KeiyakuCompanyName__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.name));
            
            type='Account';
            
            leadSchema = schemaMap.get(type);
            fieldMap = leadSchema.getDescribe().fields.getMap();
            
            theHeader.add( new Header(fieldMap.get('OfficeAdd__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.OfficeAdd__c));
            
            type='BL__c';
            
            leadSchema = schemaMap.get(type);
            fieldMap = leadSchema.getDescribe().fields.getMap();
            
            theHeader.add( new Header(fieldMap.get('Insurant__c').getDescribe().getLabel(),b.Insurant__r.name));
            
            type='Account';
            
            leadSchema = schemaMap.get(type);
            fieldMap = leadSchema.getDescribe().fields.getMap();
            
            
            theHeader.add( new Header(fieldMap.get('OfficeAdd__c').getDescribe().getLabel(),b.Insurant__r.OfficeAdd__c));
            theHeader.add( new Header(fieldMap.get('BlShimei__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.BlShimei__c));
            
            type='BL__c';
            
            leadSchema = schemaMap.get(type);
            fieldMap = leadSchema.getDescribe().fields.getMap();
            theHeader.add( new Header(fieldMap.get('NoticeTanto__c').getDescribe().getLabel(),b.NoticeTanto__c));
            
              InsuraceList = new list<wb_bl_Insurance>();
            
            InsuraceList.add( new wb_bl_Insurance( b.InsuranceCompanyName__c, b.InsuranceShiki__c, b.InsuranceManki__c,
                                                  b.Insurance__c, b.InsuranceContent__c));
            if ( b.InsuranceAmount__c != null) {
                Decimal input = b.InsuranceAmount__c;
                String output =  String.valueOf(input.format());
                InsuraceList[InsuraceList.size()-1].theContent.add( new wb_bl_InsuranceContent('保険料',  b.Currency__c + ' ' + output));
            } else
                InsuraceList[InsuraceList.size()-1].theContent.add( new wb_bl_InsuranceContent('保険料',  null));
                
        }
        
        
    }
    
    public List<Header> theHeader{get;set;} 
    public class Header{
        public string Item {get;set;}
        public string value {get;set;}
        
        public Header(string i,string v){
            Item = i;
            value = v;
        }
    }
    
    
    public list<wb_bl_Insurance> InsuraceList{get;set;}
    
    public wb_BLs_List_Export(ApexPages.StandardController Controller){
        this.Controller = Controller;
        //list <BL__c> bl = [SELECT id FROM BL__c where name ='BL011109' ];
        //  BL__c bl = (BL__c) stdController.getRecord();
        //bl = [select id, name from BL__c where id =:bl.id];
        
        Id[] items = ApexPages.currentPage().getParameters().get('items').split(',');
        
        theBLsList = new  List<BLsList>();
        myName = '';
        for (BL__c bl:[select id, name from BL__c where id=:items] ){
            myName += bl.Name; 
            BLsList r = new BLsList();
            r.fill(bl.id);
             theBLsList.add( r );
              system.debug('BL:' + bl.Name);
        }
        
        
    }
    
    /*
    public void FillHeader( string BLid ){
        system.debug('BLid:' + BLid);
        
        BL__c b = [select KeiyakuCompanyName__r.name, KeiyakuCompanyName__r.OfficeAdd__c,
                   Insurant__r.name, Insurant__r.OfficeAdd__c, 
                   NoticeTanto__c, KeiyakuCompanyName__r.BlShimei__c from BL__c where id =:BLid ];
        theHeader = new List<Header>();
        String type='BL__c';
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType leadSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
        
        theHeader.add( new Header(fieldMap.get('KeiyakuCompanyName__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.name));
        
        type='Account';
        
        leadSchema = schemaMap.get(type);
        fieldMap = leadSchema.getDescribe().fields.getMap();
        
        theHeader.add( new Header(fieldMap.get('OfficeAdd__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.OfficeAdd__c));
        
        type='BL__c';
        
        leadSchema = schemaMap.get(type);
        fieldMap = leadSchema.getDescribe().fields.getMap();
        
        theHeader.add( new Header(fieldMap.get('Insurant__c').getDescribe().getLabel(),b.Insurant__r.name));
        
        type='Account';
        
        leadSchema = schemaMap.get(type);
        fieldMap = leadSchema.getDescribe().fields.getMap();
        
        
        theHeader.add( new Header(fieldMap.get('OfficeAdd__c').getDescribe().getLabel(),b.Insurant__r.OfficeAdd__c));
        theHeader.add( new Header(fieldMap.get('BlShimei__c').getDescribe().getLabel(),b.KeiyakuCompanyName__r.BlShimei__c));
        
        type='BL__c';
        
        leadSchema = schemaMap.get(type);
        fieldMap = leadSchema.getDescribe().fields.getMap();
        theHeader.add( new Header(fieldMap.get('NoticeTanto__c').getDescribe().getLabel(),b.NoticeTanto__c));
        
        
        
    }
    public void FillDetail( BL__c Dtl)
    {
        InsuraceList = new list<wb_bl_Insurance>();
        BL__c b  = [select InsuranceCompanyName__c, InsuranceShiki__c, InsuranceManki__c, Insurance__c, InsuranceContent__c 
                    from BL__c where id =: Dtl.id];
        //system.debug('InsuranceContent__c:' + b.InsuranceContent__c);
        InsuraceList.add( new wb_bl_Insurance( b.InsuranceCompanyName__c, b.InsuranceShiki__c, b.InsuranceManki__c,
                                              b.Insurance__c, b.InsuranceContent__c));
        
    }*/
    /*
    public void FillDetail( list <BL__c> Dtl) {
        
        string bl_id;
        for ( BL__c b:Dtl){
            if ( bl_id == null)
                bl_id = '\'' +  b.id + '\'';
            else
                bl_id += ',' + '\'' +  b.id + '\'';
        }     
        
        
        
        InsuraceList = new list<wb_bl_Insurance>();
        string Sql = 'select InsuranceCompanyName__c, InsuranceShiki__c, InsuranceManki__c, BranchOfInsurance__c, InsuranceContent__c ';
        Sql +=' from BL__c where id in (' + bl_id +')';
        
        
        
        list<BL__c> BL = Database.query(Sql);
        
        for ( BL__c b: BL){
            
            InsuraceList.add( new wb_bl_Insurance( b.InsuranceCompanyName__c, b.InsuranceShiki__c, b.InsuranceManki__c,
                                                  b.BranchOfInsurance__c, b.InsuranceContent__c));
            
        }
    }
    */
    
    
}