unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CountryName__c</fullName>
        <label>国名</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region_and_Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>中国</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>日本</fullName>
                </value>
                <value>
                    <fullName>ベトナム</fullName>
                </value>
                <value>
                    <fullName>インド</fullName>
                </value>
                <value>
                    <fullName>インドネシア</fullName>
                </value>
                <value>
                    <fullName>フィリピン</fullName>
                </value>
                <value>
                    <fullName>カンボジア</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ミャンマー</fullName>
                </value>
                <value>
                    <fullName>スリランカ</fullName>
                </value>
                <value>
                    <fullName>マレーシア</fullName>
                </value>
                <value>
                    <fullName>タイ</fullName>
                </value>
                <value>
                    <fullName>韓国</fullName>
                </value>
                <value>
                    <fullName>台湾</fullName>
                </value>
                <value>
                    <fullName>ラオス</fullName>
                </value>
                <value>
                    <fullName>バングラデシュ</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>メキシコ</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <label>エリア</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>アジア</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>CountryName__c</fullName>
        <formula>TEXT(KeiyakuCompanyName__r.CountryName__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（会社情報）国名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <formula>TEXT(KeiyakuCompanyName__r.Region_and_Area__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（会社情報）エリア</label>
        <type>Text</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>商品</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>メディック</fullName>
                </value>
                <value>
                    <fullName>Prime Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <formula>MemberShimei__r.KinmuCompany__r.Name</formula>
        <label>勤務先会社</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberKubunB__c</fullName>
        <formula>CASE(  Commodity__c  , 
&quot;メディック&quot;, IF ( TaikaiDate__c &lt;= TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;留学生&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;チャイナボウル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;ベトナムメディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;メディフル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;Medi-X&quot;, IF ( TaikaiDate__c &lt;= TODAY() , &quot;Medi-X退会者&quot;, &quot;Medi-X会員&quot;), 
&quot;&quot;)</formula>
        <label>会員区分B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <label>エリア</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>アジア</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceAreaCd__c</fullName>
        <formula>CASE( KeiyakuKeitai__c , 
&quot;法人／家族Global Plus Member&quot;,&quot;GP&quot;,
&quot;個人／家族Global Plus Member&quot;,&quot;GP&quot;, 
&quot;法人／家族Global Member&quot;,&quot;G&quot;,
&quot;法人／家族China&quot;, &quot;C&quot;, 
&quot;個人／家族China&quot;, &quot;C&quot;, 
&quot;法人／家族Asian&quot;, &quot;A&quot;, 
&quot;個人／家族Asian&quot;, &quot;A&quot;, 
&quot;法人／家族&quot;,&quot;F&quot;,
&quot;チャイナボウルファミリー&quot;,&quot;CB&quot;,
&quot;法人／家族Asian B Plan&quot;, &quot;AB&quot;, 
&quot;&quot;)</formula>
        <label>サービスエリアコード</label>
        <type>Text</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>商品</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>メディック</fullName>
                </value>
                <value>
                    <fullName>チャイナボウル</fullName>
                </value>
                <value>
                    <fullName>Prime Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HuCZEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MemberKubunB__c</fullName>
        <formula>CASE( Commodity__c ,
&quot;メディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;留学生&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;チャイナボウル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;ベトナムメディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;メディフル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;Medi-X&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;Medi-X退会者&quot;, &quot;Medi-X会員&quot;),
&quot;&quot;)</formula>
        <label>会員区分B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region_and_Area__c</fullName>
        <label>エリア</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>アジア</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceAreaCd__c</fullName>
        <formula>CASE( KeiyakuKeitai__c , 
&quot;法人／単身Global Plus Member&quot;,&quot;GP&quot;,
&quot;法人／家族Global Plus Member&quot;,&quot;GP&quot;,
&quot;個人／単身Global Plus Member&quot;,&quot;GP&quot;,
&quot;個人／家族Global Plus Member&quot;,&quot;GP&quot;,
&quot;法人／単身Global Member&quot;,&quot;G&quot;,
&quot;法人／家族Global Member&quot;,&quot;G&quot;,
&quot;法人／無記名Biz Trip Pass&quot;,&quot;B&quot;,
&quot;法人／無記名Visitor Pass&quot;,&quot;V&quot;,
&quot;法人／単身Asian&quot;, &quot;A&quot;, 
&quot;法人／家族Asian&quot;, &quot;A&quot;, 
&quot;法人／無記名Asian&quot;, &quot;A&quot;, 
&quot;個人／単身Asian&quot;, &quot;A&quot;, 
&quot;個人／家族Asian&quot;, &quot;A&quot;, 
&quot;法人／単身&quot;, &quot;CB&quot;, 
&quot;法人／包括&quot;, &quot;&quot;,
&quot;法人／単身Asian B Plan&quot;, &quot;AB&quot;, 
&quot;法人／家族Asian B Plan&quot;, &quot;AB&quot;, 
&quot;法人／無記名Asian Biz Trip Plan&quot;, &quot;ABiz&quot;, 
&quot;C&quot;)</formula>
        <label>サービスエリアコード</label>
        <type>Text</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_soap_log__c.object
<CustomObject>
    <fields>
        <fullName>MemberInfo__c</fullName>
        <label>MemberInfo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>MemberNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SOAPログ</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SOAPログ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_MobileAppMembershipCheck_2ndPhs.cls
@RestResource(urlMapping='/2ndPhs/MobileAppMembershipCheck/*')
global with sharing class wb_soap_MobileAppMembershipCheck_2ndPhs {
    
    global class MembershipStatus{
        global string Id; 
        global string Status;
        global string Commodity;
        global string lastmodifieddate; 
        global wb_soap_MobileAppMemberInfo_2ndPhs.AreaControl AreaControl;
        global string ServiceAreaCode; 
        global string Type;
       public MembershipStatus (string theID, string theStatus,datetime dt){
            Id = theID;
            Status = theStatus;
            if ( dt != null) {
           // String formatedDt = dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
           // lastmodifieddate = formatedDt;
            lastmodifieddate = dt.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            }
        } 
        
        public MembershipStatus (MemberInfo__c I){
            Id = I.Id;
            Status = I.MemberKubunB__c;
            Commodity =  I.Commodity__c;
            datetime dt = I.lastmodifieddate;
            if ( dt != null) {
           // String formatedDt = dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
           // lastmodifieddate = formatedDt;
           lastmodifieddate = dt.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            }
             ServiceAreaCode = I.ServiceAreaCd__c;
             AreaControl = new wb_soap_MobileAppMemberInfo_2ndPhs.AreaControl(I);
            Type = 'M';
        }
        
        public MembershipStatus (FamilyInfo__c I){
            Id = I.Id;
            Status = I.MemberKubunB__c;
            Commodity =  I.Commodity__c;
            datetime dt = I.lastmodifieddate;
            if ( dt != null) {
                //String formatedDt = dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
               // lastmodifieddate = formatedDt;
               lastmodifieddate = dt.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            }
             ServiceAreaCode = I.ServiceAreaCd__c;
            AreaControl = new wb_soap_MobileAppMemberInfo_2ndPhs.AreaControl(I);
            Type = 'F';
        }
    }


    global class MemberID{
        global string Id;
        public MemberID(String i){
            Id = i;
        }
    }     

    @HttpGet
    global static List<MembershipStatus> getMembershipStatusParam() {
  //  global static string getMembershipStatusParam() {
        RestRequest req = RestContext.request;
        //system.debug(req);
      //  return String.valueOf( req);
        
        string lastmodifieddate;
        string dtype;
        if ( req.params.get('lastmodifieddate') != null) {
            lastmodifieddate= req.params.get('lastmodifieddate');
              dtype = req.params.get('type');
          //  if (lastmodifieddate != null ) {
               Datetime dt1 = Datetime.valueOf(lastmodifieddate); //= date.parse(mlastmodifieddate); //Datetime.valueOf(plastmodifieddate);
               return getStatus(dt1, dtype);
          /*  } else {
                   dtype = req.params.get('type');
                 return getStatus(null, dtype );
            }*/
        } else {
            dtype = req.params.get('type');
            return getStatus(null, dtype );
        }
      //  return null; 
        
    } 
    
    global static  List<MembershipStatus> getStatus(datetime plastmodifieddate, string dtype){
         
        List<MembershipStatus> MS = new  List<MembershipStatus>();       
        if (dtype == 'M') {
        List<MemberInfo__c>  M = [select id, MemberNo__c, CompanyKeiyakuNo__r.MankiDate__c, MemberKubunB__c,lastmodifieddate,
                                  //KinmuCompany__r.Region_and_Area__c, KinmuCompany__r.CountryName__c, KinmuCompany__r.Jurisdiction__c, KinmuCompany__r.ShozokuArea__c,
                                  Region_and_Area__c, CountryName__c, Jurisdiction__c, ShozokuArea__c,
                                  Commodity__c, ServiceAreaCd__c
                                  from MemberInfo__c 
                                  where lastmodifieddate >=:plastmodifieddate order by lastmodifieddate limit 5000];
        
            for ( MemberInfo__c l:M){
                MS.add( new MembershipStatus(l));
            } 
        } else if (dtype == 'F'){
        
        
        List<FamilyInfo__c>  F =  [select id, MemberShimei__r.CompanyKeiyakuNo__r.MankiDate__c,
                                   MemberKubunB__c, lastmodifieddate,
                                   //MemberShimei__r.KinmuCompany__r.Region_and_Area__c, MemberShimei__r.KinmuCompany__r.CountryName__c, 
                                   //MemberShimei__r.KinmuCompany__r.Jurisdiction__c, MemberShimei__r.KinmuCompany__r.ShozokuArea__c,
                                   Region_and_Area__c, CountryName__c, Jurisdiction__c, ShozokuArea__c,
                                   Commodity__c,  ServiceAreaCd__c
                                   from FamilyInfo__c 
                                   where lastmodifieddate >=:plastmodifieddate order by lastmodifieddate limit 5000];
        
        for ( FamilyInfo__c l:F){
            MS.add( new MembershipStatus(l));
        } 
            
        }
        
        return MS;
    }
    
        
    @HttpPost
    global static List<MembershipStatus> getMembershipStatus( List<MemberID> MemberList){
        
        List <String> IDs = New List <String>();
   		List <String> FoundIDs = New List <String>();
        
        for ( MemberID l:MemberList){
            IDs.add(l.Id );
        } 
        
        List<MembershipStatus> MS = new  List<MembershipStatus>();        
        List<MemberInfo__c>  M =  [select id, MemberNo__c, CompanyKeiyakuNo__r.MankiDate__c, MemberKubunB__c,lastmodifieddate,
                                  // KinmuCompany__r.Region_and_Area__c, KinmuCompany__r.CountryName__c, KinmuCompany__r.Jurisdiction__c, KinmuCompany__r.ShozokuArea__c,
                                   Region_and_Area__c, CountryName__c, Jurisdiction__c, ShozokuArea__c,
                                   Commodity__c, ServiceAreaCd__c
                                   from MemberInfo__c 
                                   where Id =:IDs];
        
        for ( MemberInfo__c l:M){
           // MS.add( new MembershipStatus(l.Id, l.MemberKubunB__c,l.lastmodifieddate));
             MS.add( new MembershipStatus(l));
            FoundIDs.add(l.Id);
        } 
        
        
        List<FamilyInfo__c>  F =  [select id, MemberShimei__r.CompanyKeiyakuNo__r.MankiDate__c,
                                   MemberKubunB__c, lastmodifieddate,
                                   //MemberShimei__r.KinmuCompany__r.Region_and_Area__c, MemberShimei__r.KinmuCompany__r.CountryName__c, 
                                   //MemberShimei__r.KinmuCompany__r.Jurisdiction__c, MemberShimei__r.KinmuCompany__r.ShozokuArea__c,
                                   Region_and_Area__c, CountryName__c, Jurisdiction__c, ShozokuArea__c,
                                   Commodity__c,  ServiceAreaCd__c
                                   from FamilyInfo__c 
                                   where Id =:IDs];
        
        for ( FamilyInfo__c l:F){
            //MS.add( new MembershipStatus(l.Id, l.MemberKubunB__c,l.lastmodifieddate));
            MS.add( new MembershipStatus(l));
            FoundIDs.add(l.Id);
        } 
        
        for ( MemberID l:MemberList){
            if ( !FoundIDs.contains(l.Id)){
                MS.add( new MembershipStatus(l.Id, 'Not Exist',null));
            }
        }
        
      //  String str = JSON.serialize(FoundIDs); 
     //   InsertLog(str);
        InsertLog(FoundIDs);
        return MS;
    }
    /*
    public static void InsertLog( string Str ){
             
            insert new wb_soap_log__c(LastAcessDate__c= System.today(),JStr__c=Str,Type__c ='2ND');

        
    }
    */
     public static void InsertLog( List<string> IDs ){
         
         List <String> LogIDs = New List <String>();
         
         for ( integer i = 0; i < IDs.size(); i ++ ){
             
             if (math.mod(i + 1, 1000) == 0 ) {
                 LogIDs.add(IDs[i]);        
                 string str = JSON.serialize(LogIDs);
                 insert new wb_soap_log__c(LastAcessDate__c= System.today(),JStr__c=Str,Type__c ='2ND');
                 LogIDs = New List <String>();
                 
             } else {
                 LogIDs.add(IDs[i]);
             }
         }
         
         if (LogIDs.size() > 0 ){
              string str = JSON.serialize(LogIDs);
              insert new wb_soap_log__c(LastAcessDate__c= System.today(),JStr__c=Str,Type__c ='2ND');
         }
         
     }


}