unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyCd__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>会社コード</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CompanyNameEng__c</fullName>
        <inlineHelpText>ローマ字入力ではなく、英文名称がわかる場合のみ入力します。</inlineHelpText>
        <label>会社名称(英語名)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（営業担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmmEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>管轄地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CountryName__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>台北</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>東京</fullName>
                </value>
                <value>
                    <fullName>大阪</fullName>
                </value>
                <value>
                    <fullName>名古屋</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
                <value>
                    <fullName>バンコク</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>コロンボ</fullName>
                </value>
                <value>
                    <fullName>クアラルンプール</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>メキシコシティ</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（内務担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmrEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>契約情報 (営業担当)</relationshipLabel>
        <relationshipName>R00N10000000HYtbEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <formula>TEXT(KeiyakuCompanyName__r.Jurisdiction__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（会社情報）管轄地区</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>南京</fullName>
                </value>
                <value>
                    <fullName>合肥</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから契約会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HXmTEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>契約情報 (内務担当)</relationshipLabel>
        <relationshipName>R00N10000000HYm4EAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Shimei__c.object
<CustomObject>
    <fields>
        <fullName>MeiRoma__c</fullName>
        <label>名（ローマ字）</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeiMeiRoma__c</fullName>
        <formula>MeiRoma__c &amp;&quot; &quot;&amp; SeiRoma__c</formula>
        <label>姓名（ローマ字）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeiRoma__c</fullName>
        <label>姓（ローマ字）</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>社員名簿</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/ContractInfoBatchProcessController.cls
public class ContractInfoBatchProcessController
{ 
  public boolean isEnglish {get; set;}  
  public boolean showResultsBlock {set;get;}  
  public date PresentInsuranceShiki{set;get;}   
  public List<ContractInfo__c> results {set;get;}
  public List<ContractInfo__c> searchResults {set;get;}
  public List<UpdateTable> newSearchResults {set;get;}
  public ContractInfo__c inputLookUp{set;get;}
  public String KeiyakuArea{set;get;}
  public String EigyoTanto{set;get;}
  public String NaimuTanto{set;get;}
  
  public Account accountDataFromPage{set;get;}
  public ContractInfo__c contractDataFromPage{set;get;}

    public ContractInfoBatchProcessController(ApexPages.StandardController con)
    {  
        showResultsBlock = false;
        isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language
        this.contractDataFromPage = new ContractInfo__c ();
        this.accountDataFromPage = new Account();
        inputLookUp = new ContractInfo__c();
        newSearchResults = new List<UpdateTable>(); 
    }
    
    public ContractInfoBatchProcessController(ApexPages.StandardSetController controller) {
        showResultsBlock = false;
        isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language
        this.contractDataFromPage = new ContractInfo__c ();
        this.accountDataFromPage = new Account();
        inputLookUp = new ContractInfo__c();
        newSearchResults = new List<UpdateTable>(); 
    }

    public void search(){
        //get input date from look up fields
        KeiyakuArea = contractDataFromPage.KeiyakuArea__c;
        //20180502 EigyoTanto = accountDataFromPage.EigyoTanto__c;
        //20180502 NaimuTanto = accountDataFromPage.NaimuTanto__c;
        EigyoTanto = contractDataFromPage.EigyoTanto__c;
        NaimuTanto = contractDataFromPage.NaimuTanto__c;
        //run soql query 
        query(EigyoTanto, NaimuTanto);
    }
    //&& EigyoTanto!=null && NaimuTanto!=null
    public void query(String EigyoTanto, String NaimuTanto){
        if(KeiyakuArea != null){
        showResultsBlock = true; //tag to show the results 
        /*
        searchResults = [select KeiyakuCompanyName__r.EigyoTanto__r.SeiRoma__c,KeiyakuCompanyName__r.EigyoTanto__r.MeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.SeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.MeiRoma__c,KeiyakuCompanyName__r.EigyoTanto__r.SeiMeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.SeiMeiRoma__c, NaimuTanto__r.SeiMeiRoma__c,EigyoTanto__r.SeiMeiRoma__c,KeiyakuCompanyName__r.CompanyNameEng__c,KeiyakuArea__c,KeiyakuCompanyName__r.EigyoTanto__c,EigyoTanto__c,KeiyakuCompanyName__r.NaimuTanto__c,NaimuTanto__c,KeiyakuCompanyName__r.Jurisdiction__c,KeiyakuCompanyName__r.CompanyCd__c,KeiyakuCompanyName__c,MankiDate__c,TaikaiDate__c from ContractInfo__c
        where KeiyakuArea__c =:KeiyakuArea and (KeiyakuCompanyName__r.EigyoTanto__c =:EigyoTanto or KeiyakuCompanyName__r.EigyoTanto__c =null) and (KeiyakuCompanyName__r.NaimuTanto__c =:NaimuTanto or KeiyakuCompanyName__r.NaimuTanto__c = null) and TaikaiDate__c = null order by KeiyakuCompanyName__r.Jurisdiction__c,KeiyakuCompanyName__r.EigyoTanto__c,KeiyakuCompanyName__r.NaimuTanto__c,KeiyakuCompanyName__r.CompanyCd__c];
        */
        String soql = 'select id,KeiyakuCompanyName__r.EigyoTanto__r.SeiRoma__c,KeiyakuCompanyName__r.EigyoTanto__r.MeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.SeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.MeiRoma__c,KeiyakuCompanyName__r.EigyoTanto__r.SeiMeiRoma__c,KeiyakuCompanyName__r.NaimuTanto__r.SeiMeiRoma__c, NaimuTanto__r.SeiMeiRoma__c,EigyoTanto__r.SeiMeiRoma__c,KeiyakuCompanyName__r.CompanyNameEng__c,KeiyakuArea__c,KeiyakuCompanyName__r.EigyoTanto__c,EigyoTanto__c,KeiyakuCompanyName__r.NaimuTanto__c,NaimuTanto__c,KeiyakuCompanyName__r.Jurisdiction__c,KeiyakuCompanyName__r.CompanyCd__c,KeiyakuCompanyName__c,MankiDate__c,TaikaiDate__c from ContractInfo__c where KeiyakuArea__c =\'' +KeiyakuArea+'\' and TaikaiDate__c = null';
        if(EigyoTanto!=null){
            //20180502 soql = soql + ' and KeiyakuCompanyName__r.EigyoTanto__c = '+'\''+EigyoTanto+'\'';
            soql = soql + ' and EigyoTanto__c = '+'\''+EigyoTanto+'\'';
        }
        if(NaimuTanto!=null){
            //20180502 soql = soql + ' and KeiyakuCompanyName__r.NaimuTanto__c = '+'\''+NaimuTanto+'\'';
            soql = soql + ' and NaimuTanto__c = '+'\''+NaimuTanto+'\'';
            }
        
        soql = soql + ' order by KeiyakuCompanyName__r.Jurisdiction__c,KeiyakuCompanyName__r.EigyoTanto__c,KeiyakuCompanyName__r.NaimuTanto__c,KeiyakuCompanyName__r.CompanyCd__c';
        system.debug(soql);
        
        searchResults = Database.query(soql);
        system.debug(searchResults );
        newSearchResults = new List<UpdateTable>();   // clear all old search data in the search tabl
        
          // add records to the newSearchResults list (search result table display in page)
          for(ContractInfo__c a:searchResults){
            UpdateTable records = new UpdateTable();           
            records.ContractInfoData = a;        
            newSearchResults.add(records);  
          }        
        }
        else{
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.ErrorMessageSearch);  
            ApexPages.addMessage(myMsg);       
        }     
    }
     
    public void updateRecord(){
      List<ContractInfo__c> updateList = new List<ContractInfo__c>();
      List<Id> accountCompanyIdList = new List<Id>();
      List<ContractInfo__c> contractDataList = new List<ContractInfo__c>();
      
      for(UpdateTable c:newSearchResults){   
         if(c.InchargeCheckbox){          
             accountCompanyIdList.add(c.ContractInfoData.Id);     
         }           
      }                                 
        
       //20180502  contractDataList  = [select EigyoTanto__r.SeiMeiRoma__c,NaimuTanto__r.SeiMeiRoma__c from ContractInfo__c where id in: accountCompanyIdList];
        contractDataList  = [select id, EigyoTanto__r.SeiMeiRoma__c,NaimuTanto__r.SeiMeiRoma__c, EigyoTanto__c, NaimuTanto__c from ContractInfo__c where id in: accountCompanyIdList];
        for(ContractInfo__c d:contractDataList){                
            if (inputLookUp.EigyoTanto__c!=null){
                d.EigyoTanto__c = inputLookUp.EigyoTanto__c;
            }           
            if(inputLookUp.NaimuTanto__c!=null){
                d.NaimuTanto__c = inputLookUp.NaimuTanto__c;
            }
        }                
        update contractDataList;    
        search();    
        //query(inputLookUp.EigyoTanto__c, inputLookUp.NaimuTanto__c); //update the newSearchResults list for update the changed result table
    }      
      
    public void selectAll (){
        for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = true;
        }
    }
    
    public void releaseAll (){
        for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = false;
        }  
    } 
 
    public void closeSearchTable(){
        showResultsBlock = false;    
    } 
    
    //go back to the view list 
    public PageReference back(){    
        String id= null;
        if(ApexPages.currentPage().getParameters().get('retURL')!=null){
            id = ApexPages.currentPage().getParameters().get('retURL').right(15);
        }
        system.debug(id);
        String spaceDelimeted = '/a0A?fcf='+id;
        PageReference reference = new PageReference(spaceDelimeted );
        system.debug(spaceDelimeted );
        reference.setRedirect(true);
        return reference;
    }

    public class UpdateTable {
        public Boolean InchargeCheckbox {set;get;}
        public ContractInfo__c ContractInfoData {set;get;}
    }
}