unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNameEng__c</fullName>
        <inlineHelpText>ローマ字入力ではなく、英文名称がわかる場合のみ入力します。</inlineHelpText>
        <label>会社名称(英語名)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Ichiroheian__c.object
<CustomObject>
    <fields>
        <fullName>CancelDate__c</fullName>
        <label>（搭乗）保険解約日（24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IchiroHeianNo__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>システム登録番号</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>InsuranceShuki__c</fullName>
        <label>（搭乗）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>（搭乗）契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KeiyakuCountry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>成都</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>杭州</fullName>
                </value>
                <value>
                    <fullName>寧波</fullName>
                </value>
                <value>
                    <fullName>平湖</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>華北</fullName>
                </value>
                <value>
                    <fullName>華中</fullName>
                </value>
                <value>
                    <fullName>江蘇</fullName>
                </value>
                <value>
                    <fullName>華南</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>旧（一路/安全）契約会社名称　2011/1/26　一路・安全・自動車の契約会社として使用する</description>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車保険関連 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HfleEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuCountry__c</fullName>
        <label>（搭乗）契約国</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WOAgency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>中国</fullName>
                </value>
                <value>
                    <fullName>ベトナム</fullName>
                </value>
                <value>
                    <fullName>インドネシア</fullName>
                </value>
                <value>
                    <fullName>タイ</fullName>
                </value>
                <value>
                    <fullName>フィリピン</fullName>
                </value>
                <value>
                    <fullName>マレーシア</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PresentInsuranceShiki__c</fullName>
        <label>（搭乗）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShiyoCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>実際に車を使用する会社を選択します。</inlineHelpText>
        <label>使用会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000I8NVEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WOAgency__c</fullName>
        <label>（搭乗）契約店</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>代理店</fullName>
                </value>
                <value>
                    <fullName>ブローカー</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WOCommodityName__c</fullName>
        <label>（搭乗）商品名称</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WOInsuranceCompany__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安全万里</fullName>
                </value>
                <value>
                    <fullName>安全万里Ｚ</fullName>
                </value>
                <value>
                    <fullName>安全万里V</fullName>
                </value>
                <value>
                    <fullName>一路平安</fullName>
                </value>
                <value>
                    <fullName>Safety Line</fullName>
                </value>
                <value>
                    <fullName>暢行中華</fullName>
                </value>
                <value>
                    <fullName>暢行無憂</fullName>
                </value>
                <value>
                    <fullName>搭乗者団体意外傷害</fullName>
                </value>
                <value>
                    <fullName>搭乗者傷害保険</fullName>
                </value>
                <value>
                    <fullName>Well Drive(IDN)</fullName>
                </value>
                <value>
                    <fullName>Well Drive(THA)</fullName>
                </value>
                <value>
                    <fullName>Well Drive(MYS)</fullName>
                </value>
                <value>
                    <fullName>Well Drive(PHL)</fullName>
                </value>
                <value>
                    <fullName>Well Drive(VNM)</fullName>
                </value>
                <value>
                    <fullName>Well Drive(MYS)-1</fullName>
                </value>
                <value>
                    <fullName>Well Drive(MYS)-2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WOInsuranceCompany__c</fullName>
        <label>（搭乗）保険会社名</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KeiyakuArea__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>太平洋</fullName>
                </value>
                <value>
                    <fullName>平安</fullName>
                </value>
                <value>
                    <fullName>UIC</fullName>
                </value>
                <value>
                    <fullName>華泰</fullName>
                </value>
                <value>
                    <fullName>東京海上</fullName>
                </value>
                <value>
                    <fullName>三井住友海上（中国）</fullName>
                </value>
                <value>
                    <fullName>Tokio Marine(Indonesia)</fullName>
                </value>
                <value>
                    <fullName>Tokio Marine(Malaysia)</fullName>
                </value>
                <value>
                    <fullName>Tokio Marine(Thailand)</fullName>
                </value>
                <value>
                    <fullName>Tokio Marine(Vietnam)</fullName>
                </value>
                <value>
                    <fullName>MALAYAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WOInsuranceShukiAlpha__c</fullName>
        <label>（OP）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WOPresentInsuranceShikiAlpha__c</fullName>
        <label>（OP）現保険始期</label>
        <type>Date</type>
    </fields>
    <label>自動車保険関連</label>
    <nameField>
        <label>登録番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CarInsuranceBatchProcessController.cls
public class CarInsuranceBatchProcessController
{ 
  public boolean isEnglish {get; set;}  
  public boolean showResults {set;get;}     
  public List<Ichiroheian__c> results {set;get;}
  public List<Ichiroheian__c> searchResults {set;get;}
  public Ichiroheian__c inputText {set;get;}
  public List<UpdateTable> newSearchResults {set;get;}
  public Ichiroheian__c cs {set;get;}
    
  // New Options for searching 20170125
    public String SelectedWOAgency{set;get;}
    public String SelectedKeiyakuCountry{set;get;}
    public String SelectedKeiyakuArea{set;get;}
    public String SelectedWOInsuranceCompany{set;get;}
    public String SelectedWOCommodityName{set;get;}

    public SelectOption[] WOAgencyOptions {get;set;}
    public SelectOption[] KeiyakuCountryOptions {get;set;}
    Public SelectOption[] KeiyakuAreaOptions {get;set;}
    public SelectOption[] WOInsuranceCompanyOptions {get;set;}
    Public SelectOption[] WOCommodityNameOptions {get;set;}
    
    public SelectOption[] getWOAgencyOptions(){
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','-None-'));  
        for (AggregateResult l : [ SELECT WOAgency__c , count(id)
                                  FROM Ichiroheian__c
                                  where WOAgency__c <> null
                                  group by WOAgency__c	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('WOAgency__c')), String.valueOf(l.get('WOAgency__c')) ));  
                                  }       
        return opt;
    }
    public void fetchKeiyakuCountryOptions(){
		KeiyakuCountryOptions = getKeiyakuCountryOptions();  
        KeiyakuAreaOptions = getKeiyakuAreaOptions();
        WOInsuranceCompanyOptions=getWOInsuranceCompanyOptions();
         WOCommodityNameOptions=getWOCommodityNameOptions();
    }
    public SelectOption[] getKeiyakuCountryOptions(){
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','-None-'));  
        if (! String.isBlank(SelectedWOAgency)){
            for (AggregateResult l : [ SELECT KeiyakuCountry__c , count(id)
                                      FROM Ichiroheian__c
                                      where KeiyakuCountry__c <> null and WOAgency__c =:SelectedWOAgency
                                      group by KeiyakuCountry__c	]) {  
                                          opt.add(new SelectOption(String.valueOf(l.get('KeiyakuCountry__c')), String.valueOf(l.get('KeiyakuCountry__c')) ));  
                                      }       
        }

        return opt;
    }
    public void fetchKeiyakuAreaOptions(){
        KeiyakuAreaOptions = getKeiyakuAreaOptions();
        WOInsuranceCompanyOptions=getWOInsuranceCompanyOptions();
         WOCommodityNameOptions=getWOCommodityNameOptions();
    }
    public SelectOption[] getKeiyakuAreaOptions(){
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','-None-'));  
        if (! String.isBlank(SelectedWOAgency) && ! String.isBlank(SelectedKeiyakuCountry) ){
            for (AggregateResult l : [ SELECT KeiyakuArea__c , count(id)
                                      FROM Ichiroheian__c
                                      where KeiyakuArea__c <> null and WOAgency__c =:SelectedWOAgency and KeiyakuCountry__c =:SelectedKeiyakuCountry
                                      group by KeiyakuArea__c	]) {  
                                          opt.add(new SelectOption(String.valueOf(l.get('KeiyakuArea__c')), String.valueOf(l.get('KeiyakuArea__c')) ));  
                                      }       
        }
        return opt;
    }
    public void fetchWOInsuranceCompanyOptions(){
        WOInsuranceCompanyOptions=getWOInsuranceCompanyOptions();
         WOCommodityNameOptions=getWOCommodityNameOptions();
    }
    public SelectOption[] getWOInsuranceCompanyOptions (){
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','-None-'));  
        if (! String.isBlank(SelectedWOAgency) && ! String.isBlank(SelectedKeiyakuCountry) && ! String.isBlank(SelectedKeiyakuArea) ){
            for (AggregateResult l : [ SELECT WOInsuranceCompany__c , count(id)
                                      FROM Ichiroheian__c
                                      where WOInsuranceCompany__c <> null and WOAgency__c =:SelectedWOAgency and KeiyakuCountry__c =:SelectedKeiyakuCountry
                                      and KeiyakuArea__c =:SelectedKeiyakuArea
                                      group by WOInsuranceCompany__c	]) {  
                                          opt.add(new SelectOption(String.valueOf(l.get('WOInsuranceCompany__c')), String.valueOf(l.get('WOInsuranceCompany__c')) ));  
                                      }     
        }
        return opt;
    }
    public void fetchWOCommodityNameOptions(){
        WOCommodityNameOptions=getWOCommodityNameOptions();
    }
    public SelectOption[] getWOCommodityNameOptions (){
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','-None-'));  
           if (! String.isBlank(SelectedWOAgency) && ! String.isBlank(SelectedKeiyakuCountry) && ! String.isBlank(SelectedKeiyakuArea) && ! String.isBlank(SelectedWOInsuranceCompany)){
        for (AggregateResult l : [ SELECT WOCommodityName__c , count(id)
                                  FROM Ichiroheian__c
                                   where WOCommodityName__c <> null and WOAgency__c =:SelectedWOAgency and KeiyakuCountry__c =:SelectedKeiyakuCountry
                                      and KeiyakuArea__c =:SelectedKeiyakuArea and WOInsuranceCompany__c =:SelectedWOInsuranceCompany
                                  group by WOCommodityName__c	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('WOCommodityName__c')), String.valueOf(l.get('WOCommodityName__c')) ));  
                                  }  
           }
        return opt;
    }
  
  public CarInsuranceBatchProcessController(ApexPages.StandardSetController controller) {
      isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language
      newSearchResults = new List<UpdateTable>();  
      inputText = new Ichiroheian__c();
     // this.cs = (Ichiroheian__c) con.getRecord();
    	this.cs = new Ichiroheian__c();
      showResults = false;
      // Option Initialization 
      WOAgencyOptions = getWOAgencyOptions();
      KeiyakuCountryOptions =getKeiyakuCountryOptions();
      KeiyakuAreaOptions = getKeiyakuAreaOptions();
      WOCommodityNameOptions = getWOCommodityNameOptions(); 
      WOInsuranceCompanyOptions = getWOInsuranceCompanyOptions(); 
    }
    
  public CarInsuranceBatchProcessController (ApexPages.StandardController con)
  {  
    isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language
    newSearchResults = new List<UpdateTable>();  
    inputText = new Ichiroheian__c();
    this.cs = (Ichiroheian__c) con.getRecord();
    showResults = false;
    // Option Initialization 
      WOAgencyOptions = getWOAgencyOptions();
      KeiyakuCountryOptions =getKeiyakuCountryOptions();
      KeiyakuAreaOptions = getKeiyakuAreaOptions();
      WOCommodityNameOptions = getWOCommodityNameOptions(); 
      WOInsuranceCompanyOptions = getWOInsuranceCompanyOptions(); 
  }
  
  public void search(){
     
     // 20170125 if(cs.WOAgency__c!=null && cs.KeiyakuArea__c!=null && cs.InsuranceShuki__c!=null && cs.WOInsuranceCompany__c!=null && cs.WOCommodityName__c!=null){
       showResults = true; //tag to show the results 
       newSearchResults = new List<UpdateTable>(); // clear all old search data in the search table
      // 20170125
       string searchResultStr;
       searchResultStr = 'select WoAgency__c,Name,PresentInsuranceShiki__c,WOPresentInsuranceShikiAlpha__c,KeiyakuArea__c,KeiyakuCompanyName__r.CompanyNameEng__c,KeiyakuCompanyName__c,IchiroHeianNo__c,ShiyoCompanyName__c,ShiyoCompanyName__r.CompanyNameEng__c,InsuranceShuki__c,Wocommodityname__c,WOInsuranceCompany__c,WOInsuranceShukiAlpha__c ,CancelDate__c from Ichiroheian__c ';
      string conditionStr;  
      if(! String.isBlank(SelectedWOAgency)) {
          conditionStr =  ' WOAgency__c =\'' +SelectedWOAgency + '\'' ;
      }
      if(! String.isBlank(SelectedKeiyakuCountry)) {
          if (conditionStr!=null ) {
		      conditionStr += ' and KeiyakuCountry__c =\'' +SelectedKeiyakuCountry + '\'' ;
          } else {
              conditionStr =  ' KeiyakuCountry__c =\'' +SelectedKeiyakuCountry + '\'' ;
          }
      }
      if(! String.isBlank(SelectedKeiyakuArea)) {
          if (conditionStr!=null ) {
              conditionStr += ' and KeiyakuArea__c =\'' +SelectedKeiyakuArea + '\'' ;
          } else {
              conditionStr =  ' KeiyakuArea__c =\'' +SelectedKeiyakuArea + '\'' ;
          }
      } 
      if (cs != null) {
          if(cs.InsuranceShuki__c!=null) {
              string mm =  String.valueOf(cs.InsuranceShuki__c.month()+100);
              mm = mm.right(2);
              string dd =  String.valueOf(cs.InsuranceShuki__c.day()+100);
              dd = dd.right(2);
              string d = String.valueOf(cs.InsuranceShuki__c.year() ) +'-'+ mm +'-'+ dd;
              if (conditionStr!=null ) {
                  
                  conditionStr += ' and InsuranceShuki__c = '+ d +' ' ;
              } else {
                  conditionStr =  ' InsuranceShuki__c = '+ d +' ' ;
              }
          }      
      }
      if(! String.isBlank(SelectedWOInsuranceCompany)) {
          if (conditionStr!=null ) {
              conditionStr += ' and WOInsuranceCompany__c =\'' +SelectedWOInsuranceCompany + '\'' ;
          } else {
              conditionStr =  ' WOInsuranceCompany__c =\'' +SelectedWOInsuranceCompany + '\'' ;
          }
      }
      if(! String.isBlank(SelectedWOCommodityName)) {
          if (conditionStr!=null ) {
              conditionStr += ' and WOCommodityName__c =\'' +SelectedWOCommodityName + '\'' ;
          } else {
              conditionStr =  ' WOCommodityName__c =\'' +SelectedWOCommodityName + '\'' ;
          }
      }
      
  	/* 20190410
     if (conditionStr==null) {
          searchResultStr += ' where CancelDate__c!=null ORDER BY WoAgency__c '; }
      else {  searchResultStr+=' where ' + conditionStr + ' and CancelDate__c!=null ORDER BY WoAgency__c ';}
      */
      
      if (conditionStr==null) {
          searchResultStr += ' where CancelDate__c=null ORDER BY WoAgency__c '; }
      else {  searchResultStr+=' where ' + conditionStr + ' and CancelDate__c=null ORDER BY WoAgency__c ';}
      
      
     if (conditionStr!= null)
		system.debug(conditionStr);
      
       searchResults = Database.query(searchResultStr);
      // 20170125 searchResults = [select WoAgency__c,Name,PresentInsuranceShiki__c,WOPresentInsuranceShikiAlpha__c,KeiyakuArea__c,KeiyakuCompanyName__r.CompanyNameEng__c,KeiyakuCompanyName__c,IchiroHeianNo__c,ShiyoCompanyName__c,ShiyoCompanyName__r.CompanyNameEng__c,InsuranceShuki__c,Wocommodityname__c,WOInsuranceCompany__c,WOInsuranceShukiAlpha__c ,CancelDate__c from Ichiroheian__c
      // 20170125 where WoAgency__c =:cs.WoAgency__c and KeiyakuArea__c =: cs.KeiyakuArea__c and WOCommodityName__c=: cs.WOCommodityName__c and InsuranceShuki__c =:cs.InsuranceShuki__c and CancelDate__c=null ORDER BY KeiyakuArea__c ,KeiyakuCompanyName__c,ShiyoCompanyName__c,Name ];
       
          for(Ichiroheian__c a:searchResults){
            UpdateTable records = new UpdateTable();           
            records.IchiroheianData = a;    
            records.InchargeCheckbox = true; //the PIC Update checkbox default true     
            newSearchResults.add(records);  
          }
   // 20170125  }
   //   else{
  //           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.ErrorMessageSearch);  
  //           ApexPages.addMessage(myMsg);
  //           newSearchResults = new List<UpdateTable>(); //clear all search data
  //    }
  }

  public void selectAll (){
      for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = true;
         b.opCheckbox = true;
      }
  }
  
  public void releaseAll (){
      for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = false;
         b.opCheckbox = false;
      }    
  }  
  
  public void closeSearchTable(){  
     showResults = false;
  }
  
  public PageReference back(){
  
     String id = null;   
     if(ApexPages.currentPage().getParameters().get('retURL')!=null){
         id = ApexPages.currentPage().getParameters().get('retURL').right(15); //get pervious page id
     }
     String spaceDelimeted = '/a0D?fcf='+id;
     PageReference reference = new PageReference(spaceDelimeted);
     system.debug(spaceDelimeted );
     reference.setRedirect(true);
     return reference;
  }

  public void updateRecord(){
      List<Ichiroheian__c> updateList = new List<Ichiroheian__c>();
      List<Ichiroheian__c> updateList2 = new List<Ichiroheian__c>();
      for(UpdateTable c:newSearchResults ){
          // check the PIC Update checkbox click and put the input text data in list for update
          if(c.InchargeCheckbox){
            if (inputText.PresentInsuranceShiki__c!=null){
                c.IchiroheianData.PresentInsuranceShiki__c = inputText.PresentInsuranceShiki__c;
            }
            if(inputText.InsuranceShuki__c!=null){
                c.IchiroheianData.InsuranceShuki__c = inputText.InsuranceShuki__c;  
            }
            updateList.add(c.IchiroheianData);
          }           
          // check the (OP) Update checkbox click and put the input text data in list for update
          if(c.opCheckbox){
            if (inputText.WOPresentInsuranceShikiAlpha__c!=null){
                c.IchiroheianData.WOPresentInsuranceShikiAlpha__c = inputText.WOPresentInsuranceShikiAlpha__c;
            }
            if (inputText.WOInsuranceShukiAlpha__c!=null){
                c.IchiroheianData.WOInsuranceShukiAlpha__c = inputText.WOInsuranceShukiAlpha__c;  
            }
            updateList2.add(c.IchiroheianData);
          }                            
           //updateList.add(c.IchiroheianData);
        }
        
        if(updateList.size()>0){    
            update updateList;    
        }
        if(updateList2.size()>0){
            update updateList2;
        }
  }
  
    public class UpdateTable {
        public Boolean InchargeCheckbox {set;get;}
        public Boolean opCheckbox {set;get;}
        public Ichiroheian__c IchiroheianData {set;get;}
    }
    


}