unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNameEng__c</fullName>
        <inlineHelpText>ローマ字入力ではなく、英文名称がわかる場合のみ入力します。</inlineHelpText>
        <label>会社名称(英語名)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから契約会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HXmTEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>商品</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>メディック</fullName>
                </value>
                <value>
                    <fullName>チャイナボウル</fullName>
                </value>
                <value>
                    <fullName>Prime Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HUqkEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HuCZEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MemberKubunB__c</fullName>
        <formula>CASE( Commodity__c ,
&quot;メディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;留学生&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;チャイナボウル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;ベトナムメディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;メディフル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;Medi-X&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;Medi-X退会者&quot;, &quot;Medi-X会員&quot;),
&quot;&quot;)</formula>
        <label>会員区分B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SeiMeiRoma__c</fullName>
        <formula>MeiRoma__c &amp; &quot; &quot; &amp;  SeiRoma__c</formula>
        <label>姓名（ローマ字）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/MankiDateBatchProcessController.cls
public class MankiDateBatchProcessController
{ 
  public boolean isEnglish {get; set;}  
  //public boolean showResults {set;get;}  
  public boolean showResultsBlock {set;get;}  
  //public List<MemberInfo__c> results {set;get;}
  public List<MemberInfo__c> searchResults {set;get;}   
  //public List<ContractInfo__c> mankiDate {set;get;}
  public List<UpdateTable> newSearchResults {set;get;}
  //public String companyKeiyakuNo {set;get;} 
  public ContractInfo__c outputData {set;get;}
  public ContractInfo__c updateData {set;get;}  
  public Account accountData {set;get;}
  public ContractInfo__c thisRecord;
  public List<String> recordName {set;get;} 
  //public String thisRecordName {set;get;} 

    public MankiDateBatchProcessController(ApexPages.StandardController con){
        this.thisRecord = (ContractInfo__c)con.getRecord();
        isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language 
        newSearchResults = new List<UpdateTable>(); 
        outputData = new ContractInfo__c();
        updateData = new ContractInfo__c();
        accountData = new Account();
        recordName = new List<String>();
        
        List<ContractInfo__c> thisRecordName = [select name from ContractInfo__c where id =:thisRecord.id];
        for(ContractInfo__c a:thisRecordName){
            recordName.add(a.name);
        }
        query(); 
    }
    
     public void query(){
        List<ContractInfo__c> contractList = [select KeiyakuCompanyName__c,KeiyakuCompanyName__r.name,MankiDate__c from ContractInfo__c where name in: recordName]; 
        List<String> keiyakuCompanyName = new List<String>();
        
        for(ContractInfo__c b:contractList){       
            outputData.MankiDate__c = b.MankiDate__c;
            keiyakuCompanyName.add(b.KeiyakuCompanyName__r.name);
            //outputData.KeiyakuCompanyName__r.CompanyNameEng__c = b.KeiyakuCompanyName__r.CompanyNameEng__c;
        }
        
        List<Account> accountList = [select CompanyNameEng__c,name from Account where name in:keiyakuCompanyName];
        if(isEnglish){
            for(Account a:accountList){
                accountData.CompanyNameEng__c = a.CompanyNameEng__c;
            }        
        }else{
            for(Account a:accountList){
                accountData.name = a.name;
            }
        }

            showResultsBlock = true; //tag to show the results 
            searchResults = [select id,MemberNo__c,Name,CompanyKeiyakuNo__c,MankiDate__c,Commodity__c,SeiMeiRoma__c,KinmuCompany__r.CompanyNameEng__c,KinmuCompany__c from memberInfo__c where CompanyKeiyakuNo__r.Name in: recordName and (TaikaiDate__c = null or TaikaiDate__c >= TODAY) and MemberKubunB__c != '退会者' order by KinmuCompany__c,Name];
           
            newSearchResults = new List<UpdateTable>();   // clear all old search data in the search tabl  
            // add records to the newSearchResults list (search result table display in page)
            for(MemberInfo__c a:searchResults){
                UpdateTable records = new UpdateTable();           
                records.memberData = a;        
                newSearchResults.add(records); 
            } 
        

        selectAll();         
     }
   
    public void updateRecord(){       
          
          Boolean checkBoxClicked = false; 
          list<ContractInfo__c> contractMankiDate = [select id,MankiDate__c from ContractInfo__c where name =:recordName];
          for(ContractInfo__c b:contractMankiDate){
             b.MankiDate__c = updateData.MankiDate__c;
          }
                   
          List<MemberInfo__c> updateList = new List<MemberInfo__c>();
          for(UpdateTable c:newSearchResults){         
            if(c.InchargeCheckbox){                       
                if (updateData.MankiDate__c!=null){
                    c.memberData.MankiDate__c = updateData.MankiDate__c;                 
                }                                   
               updateList.add(c.memberData);
               checkBoxClicked = true;
            }                    
         }  
              if(checkBoxClicked == true){
                  update contractMankiDate;
              }
              update updateList; 
              query();      
              releaseAll();
    }
      
    public void selectAll(){
      for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = true;
      }         
    }
    
    public void releaseAll(){
      for(UpdateTable b:newSearchResults){
         b.InchargeCheckbox = false;
      }      
    } 
 
    public void closeSearchTable(){
        showResultsBlock = false;       
    } 
    
    //go back to the view list 
    public PageReference back(){     
    /*
        String id = ApexPages.currentPage().getParameters().get('retURL').right(15);
        String spaceDelimeted = '/a08?fcf='+id; 
        PageReference reference = new PageReference(spaceDelimeted);
        reference.setRedirect(true);
    */
        String id = ApexPages.currentPage().getParameters().get('id');
        String spaceDelimeted = id; 
        PageReference reference = new PageReference('/'+spaceDelimeted);
        reference.setRedirect(true);    
    
        return reference;
    }

     public class UpdateTable {
         public Boolean InchargeCheckbox {set;get;}
         public MemberInfo__c memberData {set;get;}
         public ContractInfo__c contractData {set;get;}
    } 

}