unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>管轄地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CountryName__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>台北</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>東京</fullName>
                </value>
                <value>
                    <fullName>大阪</fullName>
                </value>
                <value>
                    <fullName>名古屋</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
                <value>
                    <fullName>バンコク</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>コロンボ</fullName>
                </value>
                <value>
                    <fullName>クアラルンプール</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>メキシコシティ</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>AffiliationDistrict__c</fullName>
        <formula>TEXT(WorkingCompany__r.ShozokuArea__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>所属地区</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChronicDisease__c</fullName>
        <label>持病</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>苦情区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>なし</fullName>
                </value>
                <value>
                    <fullName>少ない</fullName>
                </value>
                <value>
                    <fullName>やや多い</fullName>
                </value>
                <value>
                    <fullName>多い</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentMemberNo__c</fullName>
        <label>現メンバー番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <label>生年月日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FamilyRelationship__c</fullName>
        <label>家族関係</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>妻</fullName>
                </value>
                <value>
                    <fullName>息子</fullName>
                </value>
                <value>
                    <fullName>娘</fullName>
                </value>
                <value>
                    <fullName>長男</fullName>
                </value>
                <value>
                    <fullName>次男</fullName>
                </value>
                <value>
                    <fullName>長女</fullName>
                </value>
                <value>
                    <fullName>次女</fullName>
                </value>
                <value>
                    <fullName>三女</fullName>
                </value>
                <value>
                    <fullName>三男</fullName>
                </value>
                <value>
                    <fullName>会員本人</fullName>
                </value>
                <value>
                    <fullName>兄弟</fullName>
                </value>
                <value>
                    <fullName>四女</fullName>
                </value>
                <value>
                    <fullName>四男</fullName>
                </value>
                <value>
                    <fullName>夫</fullName>
                </value>
                <value>
                    <fullName>妹</fullName>
                </value>
                <value>
                    <fullName>孫</fullName>
                </value>
                <value>
                    <fullName>弟</fullName>
                </value>
                <value>
                    <fullName>従妹</fullName>
                </value>
                <value>
                    <fullName>母</fullName>
                </value>
                <value>
                    <fullName>父</fullName>
                </value>
                <value>
                    <fullName>甥</fullName>
                </value>
                <value>
                    <fullName>知人</fullName>
                </value>
                <value>
                    <fullName>義妹</fullName>
                </value>
                <value>
                    <fullName>義母</fullName>
                </value>
                <value>
                    <fullName>義父</fullName>
                </value>
                <value>
                    <fullName>親戚</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <formula>TEXT(WorkingCompany__r.Jurisdiction__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>管轄地区</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>携帯TEL</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>家族</relationshipLabel>
        <relationshipName>FamilyMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>役職</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>性別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_MemberNo__c</fullName>
        <formula>MembershipDetail__r.MemberNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>分類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>新規</fullName>
                </value>
                <value>
                    <fullName>継続</fullName>
                </value>
                <value>
                    <fullName>追加</fullName>
                </value>
                <value>
                    <fullName>交替</fullName>
                </value>
                <value>
                    <fullName>変更</fullName>
                </value>
                <value>
                    <fullName>解約変更</fullName>
                </value>
                <value>
                    <fullName>移行</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MemberNo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>CardPrefix__c</fullName>
        <label>カード接頭</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>データタイプ</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceClassification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員</fullName>
                </value>
                <value>
                    <fullName>健診</fullName>
                </value>
                <value>
                    <fullName>車保</fullName>
                </value>
                <value>
                    <fullName>搭乗</fullName>
                </value>
                <value>
                    <fullName>強制</fullName>
                </value>
                <value>
                    <fullName>任意</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>現地医療</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceFee__c</fullName>
        <label>サービス費</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>サービス</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_Individual.cls
public class wb_Individual {
    private ApexPages.StandardController standardController;
    public string MyHome='/a0n/o'; 
    public wb_Individual__c Individual {get;set;}
    public List<wb_Individual__c> CurrentFamilyMembers {get;set;}
    public List<wb_Individual__c> NewFamilyMembers {get;set;}
    public List<wb_Individual__c> WholeFamily {get;set;}
    public integer NoofFamilyMembers {get;set;}
    
    public String FormTag { get; set; }
    public List<wb_Individual__c> searchresults {get;set;}
    public List<String> str_searchresults {get;set;}
    public List<SelectOption> str_searchresultOptions {get;set;}
    public string searchString{get;set;}
    public Account WorkFor{get;set;}
    
    public List<wb_Service__c> MDService {get;set;}
    public List<aTableRow> theEmployeeRows { get; set; }
    
    public wb_MembershipDetail__c MembershipPeriod { get; set; }
    public class aTableRow {
        public Boolean IsSelected { get; set; }
        public Boolean HavingFamily { get; set; }
        public string FamilyMessage { get; set; }
        public wb_Individual__c theEmployee { get; set; }
        public Id MyService { get; set; }
        public List<wb_Service__c> theService { get; set; }
        
        public SelectOption[] ServiceOptions {get; set;}
        
        public SelectOption[] getServiceOptions() {  
            
            List<SelectOption>  opt = new  List<SelectOption>();
            opt.add(new SelectOption('','--None--'));  
            
            if (theService != null) {
            for (  wb_Service__c s: theService) {
                if ( s.DataType__c =='単身' || s.DataType__c =='家族' )
                    opt.add(new SelectOption(s.id, s.Service__c + s.DataType__c));
            }
            }
            
            return opt;  
        }  
        
        
        public aTableRow(Boolean b, wb_Individual__c em, List<wb_Service__c> Service, string ServiceID ) {
            theEmployee = em;
            HavingFamily = b;
            if ( HavingFamily == true)
                FamilyMessage = '家族有り';
            else
                FamilyMessage = '家族無し';
            theService = Service;
            ServiceOptions = getServiceOptions();
            if ( ServiceID != null ) {
            if (ServiceID.length() > 0)
                MyService = ServiceID;
            }
        }
    }
    
    public void fetchSelectedList(){
        
    }
    
    public List<wb_Service__c> getServiceMaster(){
        
        return [SELECT id, Service__c, CardPrefix__c, Currency__c, ServiceFee__c,  
                DataType__c
                FROM wb_Service__c
                where ServiceClassification__c = '会員' and Enable__c = true];
        
    }
    
    public string CallerRowID { get; set; }
    public string CallerRowIndex  { get; set; }
    public string CallerServiceID  { get; set; }
    public string CallerWorkingCompID { get; set; }
    public string CallerStartDate { get; set; }
    public string CallerMode { get; set; }
    public string CallerDateRequest { get; set; }
    public wb_Individual(ApexPages.StandardController stdController){
        string Id = ApexPages.currentPage().getParameters().get('Id');
        
        //system.debug('id:' +Id);
        
        this.standardController = stdController;
        Individual = (wb_Individual__c) stdController.getRecord();
        
        GetMyselfandFamily();
        
        NewFamilyMembers = new List<wb_Individual__c>();
        
        
    }
    
    public wb_Individual(){
        CallerRowID = apexpages.currentpage().getparameters().get('pv0');
        CallerRowIndex = apexpages.currentpage().getparameters().get('pv1');
        CallerServiceID = apexpages.currentpage().getparameters().get('pv2');
        CallerWorkingCompID = apexpages.currentpage().getparameters().get('pv3');
        CallerStartDate = apexpages.currentpage().getparameters().get('pv4');
        CallerMode = apexpages.currentpage().getparameters().get('pv5');
        CallerDateRequest = apexpages.currentpage().getparameters().get('pv6');
        //system.debug('id:' +Id);
        //system.debug('pv:' +CallerRowID + ':' + CallerRowIndex + ':' + CallerServiceID + ':' + CallerWorkingCompID +':' + CallerStartDate);
        MDService = getServiceMaster();
        system.debug(MDService);
        MembershipPeriod = new wb_MembershipDetail__c();
        //MembershipPeriod.MembershipStartDate__c = CallerStartDate;
        // String mm=CallerStartDate.subString(0,2);
        // String dd=CallerStartDate.subString(6,8);
        // String yy=CallerStartDate.subString(0,4);
        if (CallerStartDate.length()>0){
            String[] newdates = CallerStartDate.split('/');
            MembershipPeriod.MembershipStartDate__c = Date.newInstance(integer.valueOf(newdates[0]), 
                                                                       integer.valueOf(newdates[1]), 
                                                                       integer.valueOf(newdates[2]));
        }
        //if ()
        if (CallerWorkingCompID.length() > 0 ){
            if ( [ select id from account where id =:CallerWorkingCompID].size() > 0 )
                WorkFor = [select id, name from account where id =:CallerWorkingCompID];
        }

        Individual = new wb_Individual__c();
        if ( WorkFor != null) 
            Individual.WorkingCompany__c = WorkFor.id;             
        
        
        NewFamilyMembers = new List<wb_Individual__c>();
    }
    
     
     
    public void GetMyselfandFamily(){
        
        if ( Individual.id != null ) {
            Individual =[SELECT PostalCode__c, Parent__c, Complaint__c, //Jurisdiction__c, 
                         DateOfBirth__c, Member__r.f_MemberNo__c, // CurrentMemberNo__c, 
                         Name, 
                         Mobile__c, ChronicDisease__c, //AffiliationDistrict__c, 
                         WorkingCompany__r.Jurisdiction__c,
                         Sex__c, Position__c, FamilyRelationship__c, FamilyNo__c, 
                         LastNameRoma__c, LastNameKana__c, CountryCallingCodes__c, //Country__c, 
                         FirstNameRoma__c, FirstNameKana__c, 
                         //Classification__c, 
                         WorkingCompany__c, HealthCheckSystemNo__c, Address__c, //MembershipStartDate__c, 
                        // MembershipEndDate__c, 
                         MailDelivery__c, EmailAddress__c, Id, AC_Information__c,
                         Note__c
                         // DeptAfterWithdrawal__c, 
                         // ReturningHomeCountryCoverage__c ,
                         // PositionAfterWithdrawal__c, 
                         // CompanyAfterWithdrawal__c 
                         FROM wb_Individual__c where id =:Individual.id ];
            
            RefreshFamily();
            
        }
        
        else {
            
            Individual = new wb_Individual__c(FamilyNo__c ='0');
            WholeFamily = new List<wb_Individual__c>();
            
        }
    }
    
    public void RefreshFamily(){
        
        WholeFamily = new List<wb_Individual__c>();
        GetCurrentFamilyMembers();
        CombineCurrentnNewMembers();
        
    } 
    
    public void CombineCurrentnNewMembers(){
        WholeFamily = new List<wb_Individual__c>();
        
        if ( CurrentFamilyMembers != null ) {
            for ( wb_Individual__c f:CurrentFamilyMembers){
                WholeFamily.add(f);
            }
        }
        if ( NewFamilyMembers != null ) {
            for ( wb_Individual__c f:NewFamilyMembers){
                WholeFamily.add(f);
            }
        }
        
        NoofFamilyMembers = WholeFamily.size();
    }
    
    public void GetCurrentFamilyMembers(){
        CurrentFamilyMembers = new List<wb_Individual__c>();
        CurrentFamilyMembers = [select id, Parent__c, Name, Sex__c, FirstNameKana__c, LastNameKana__c,
                                FirstNameRoma__c, LastNameRoma__c, DateOfBirth__c, Address__c, EmailAddress__c,
                                MailDelivery__c,
                                //Tel__c, Fax__c, 
                                FamilyNo__c, FamilyRelationship__c
                                from wb_Individual__c where Parent__c =:Individual.id ];
    }
    
     
    
    public void NewFamilyMember() {
        
        if ( Individual.name <> null && Individual.id == null ) {
            Individual.FamilyNo__c ='0';
            upsert Individual;
        }
        
        
        if (Individual.id <> null){
            GetCurrentFamilyMembers();
            
            Integer n = CurrentFamilyMembers.size() + NewFamilyMembers.size();
            
            
            NewFamilyMembers.add( new wb_Individual__c(Parent__c=Individual.id, FamilyNo__c =  string.valueOf( n + 1)) );
            CombineCurrentnNewMembers();
            
        }
        
        return;
    }
    
    
    public PageReference validate()
    {
        
        if(Individual.Name == null )
            Individual.Name.addError('氏名を入力してください!');
        return null;    
        
    }
    
    public PageReference UpdateRecords(){
        
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        if (Individual.id == null) {
            Individual.FamilyNo__c ='0';
            insert Individual;
            
            
            return new PageReference(sfdcBaseURL +MyHome);
            
        }
        else {
            update Individual;
            update CurrentFamilyMembers;
            insert NewFamilyMembers;
            
            //update Family;
            
            // return new PageReference('https://cs6.salesforce.com/' + Individual.id);
            return new PageReference(sfdcBaseURL +'/'+ Individual.id);
        }
        
    }
    
    public void UpdateRecordsAndStay(){
        
        
        if (Individual.id == null) {
            Individual.FamilyNo__c ='0';
            insert Individual;
            
            
            return ;
            
        }
        else {
            update Individual;
            //update CurrentFamilyMembers;
            upsert NewFamilyMembers;
            return ;
        }
        
    }
     
    
    public PageReference Cancel(){
        
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        if (Individual.id == null) {
            
            return new PageReference(sfdcBaseURL +MyHome);
            
        }
        else {
            
            return new PageReference(sfdcBaseURL +'/'+ Individual.id);
        }
        
    }
    
    public PageReference Home(){
        
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        return new PageReference(sfdcBaseURL +MyHome);
        
    }
    
    public PageReference Edit(){
        
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        system.debug(sfdcBaseURL +'/apex/wb_individual_Edit?id'+ Individual.id );
        
        return new PageReference(sfdcBaseURL +'/apex/wb_individual_Edit?id='+ Individual.id);
        
        
    }
    
    public PageReference validateAndUpdate()
    {
        // Validate and redisplay if errors
        validate();
        if(ApexPages.hasMessages(ApexPages.Severity.Error))
            return null;
        
        return  UpdateRecords();
    }
    
    // performs the keyword search
    public PageReference search() {
        runSearch();
        return null;
    }
    // prepare the query and issue the search command
    private void runSearch() {
        // TODO prepare query string for complex serarches & prevent injections
        if (WorkFor != null)
            searchresults = performSearch( WorkFor.name);    
        else
            searchresults = performSearch( null);
        
        theEmployeeRows = new List<aTableRow>();
        List<id> Parent=new List<id>();
        
        // str_searchresults = new List<string>();
        // str_searchresultOptions = new List<SelectOption>();
        if ( searchresults != null) {
            for ( wb_Individual__c r:searchresults){
                theEmployeeRows.add(new aTableRow(false, r, MDService, CallerServiceID));
                Parent.add(r.id);
                //str_searchresultOptions.add(new SelectOption (r.id,r.name));
            }
        }
        
        
        AggregateResult[] AgR = [SELECT Parent__c, count(id)
                                 FROM wb_Individual__c
                                 where Parent__c in: Parent
                                 group by Parent__c];
        
        for (AggregateResult c:AgR){
            for( aTableRow r:theEmployeeRows){
                if ( r.theEmployee.id == c.get('Parent__c'))   {
                    if ((Integer) c.get('expr0') > 0 ) {
                        r.HavingFamily = true;
                        r.FamilyMessage = '家族有り';
                    }
                    
                }
            }
        }            
        // system.debug('searchresults:' + searchresults.size() + ' :' + str_searchresults.size());
    } 
    
    // run the search and return the records found. 
    private List<wb_Individual__c> performSearch(string searchString) {
        
        
        List<wb_Individual__c> WorkingCompanyIndividualList;
        
        String soqlW = 'select id, name, Member__r.f_MemberNo__c, WorkingCompany__r.name from wb_Individual__c';
        // String soqlW = 'select id, name, WorkingCompany__r.name from wb_Individual__c';
        
        if(searchString != '' && searchString != null) {
            soqlW = soqlW +  ' where WorkingCompany__r.name =  \'' + searchString +'\' ';
            
        } else
        {
            soqlW = soqlW +  ' where Parent__c = null ';
        }
        
        //  soqlW = soqlW + ' limit 2 ';
        
        System.debug(soqlW);
        
        WorkingCompanyIndividualList = database.query(soqlW);
        
        List<wb_Individual__c> IndividualList =new List<wb_Individual__c>();
        
        IndividualList.addAll(WorkingCompanyIndividualList);
        
        return IndividualList;
        
    }
    
    // used by the visualforce page to send the link to the right dom element
    public string getFormTag() {
        return System.currentPageReference().getParameters().get('frm');
    }
    
    // used by the visualforce page to send the link to the right dom element for the text box
    public string getTextBox() {
        return System.currentPageReference().getParameters().get('txt');
    }
    
    
}