unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CountryName__c</fullName>
        <label>国名</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region_and_Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>中国</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>日本</fullName>
                </value>
                <value>
                    <fullName>ベトナム</fullName>
                </value>
                <value>
                    <fullName>インド</fullName>
                </value>
                <value>
                    <fullName>インドネシア</fullName>
                </value>
                <value>
                    <fullName>フィリピン</fullName>
                </value>
                <value>
                    <fullName>カンボジア</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ミャンマー</fullName>
                </value>
                <value>
                    <fullName>スリランカ</fullName>
                </value>
                <value>
                    <fullName>マレーシア</fullName>
                </value>
                <value>
                    <fullName>タイ</fullName>
                </value>
                <value>
                    <fullName>韓国</fullName>
                </value>
                <value>
                    <fullName>台湾</fullName>
                </value>
                <value>
                    <fullName>ラオス</fullName>
                </value>
                <value>
                    <fullName>バングラデシュ</fullName>
                </value>
                <value>
                    <fullName>北米</fullName>
                </value>
                <value>
                    <fullName>メキシコ</fullName>
                </value>
                <value>
                    <fullName>中南米</fullName>
                </value>
                <value>
                    <fullName>欧州</fullName>
                </value>
                <value>
                    <fullName>オセアニア</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>中東</fullName>
                </value>
                <value>
                    <fullName>アフリカ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CountryName__c</fullName>
        <label>国名</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>華北</fullName>
                </value>
                <value>
                    <fullName>華中</fullName>
                </value>
                <value>
                    <fullName>華南</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>マカオ</fullName>
                </value>
                <value>
                    <fullName>ベトナム</fullName>
                </value>
                <value>
                    <fullName>インド</fullName>
                </value>
                <value>
                    <fullName>インドネシア</fullName>
                </value>
                <value>
                    <fullName>フィリピン</fullName>
                </value>
                <value>
                    <fullName>カンボジア</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>スリランカ</fullName>
                </value>
                <value>
                    <fullName>ミャンマー</fullName>
                </value>
                <value>
                    <fullName>タイ</fullName>
                </value>
                <value>
                    <fullName>マレーシア</fullName>
                </value>
                <value>
                    <fullName>日本</fullName>
                </value>
                <value>
                    <fullName>韓国</fullName>
                </value>
                <value>
                    <fullName>台湾</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>家族</relationshipLabel>
        <relationshipName>FamilyMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>If(ISBLANK(Parent__c),
Member__r.f_Classification__c,
If(ISBLANK(Parent__r.Member__r.f_Classification__c),
&apos;&apos;,
Parent__r.Member__r.f_Classification__c + &apos;家族&apos;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MedicalInsurance__c.object
<CustomObject>
    <fields>
        <fullName>MedicalDivision__c</fullName>
        <label>医療区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OTA</fullName>
                </value>
                <value>
                    <fullName>現地医療</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>医療保険</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>医療保険</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MedicalInsuranceDetail__c.object
<CustomObject>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>医療保険対象</relationshipLabel>
        <relationshipName>CompanyOfMedicalInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>医療保険対象</relationshipLabel>
        <relationshipName>IndividualMedicalInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InsuranceEndDate__c</fullName>
        <label>保険満期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>保険種類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安心生活</fullName>
                </value>
                <value>
                    <fullName>安心NHST</fullName>
                </value>
                <value>
                    <fullName>駐在中国</fullName>
                </value>
                <value>
                    <fullName>チャイナボウル</fullName>
                </value>
                <value>
                    <fullName>優You</fullName>
                </value>
                <value>
                    <fullName>新優You</fullName>
                </value>
                <value>
                    <fullName>Medi-X</fullName>
                </value>
                <value>
                    <fullName>ウェルライフ</fullName>
                </value>
                <value>
                    <fullName>OM-S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MedicalInsurance__c</fullName>
        <label>医療保険</label>
        <referenceTo>wb_MedicalInsurance__c</referenceTo>
        <relationshipLabel>医療保険対象</relationshipLabel>
        <relationshipName>MedicalInsuranceDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>if(IsNull(Individual__r.f_Classification__c),
Individual__r.Parent__r.f_Classification__c,
Individual__r.f_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>会員区分</label>
        <type>Text</type>
    </fields>
    <label>医療保険対象</label>
    <nameField>
        <label>医療保険対象番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>if(IsBlank(r_EffectiveUntil__c),&apos;&apos;,if(r_EffectiveUntil__c&gt;= TODAY(),&apos;会員&apos;,&apos;退会者&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_rpt_MemberLocalMedicalService.cls
public class wb_rpt_MemberLocalMedicalService {
    
    public wb_MedicalInsuranceDetail__c ReportingCondition{get;set;}
    
    public List<wb_MedicalInsuranceDetail__c> LocalMedicalInsuranceIndividual{get;set;}
    
    public wb_rpt_MemberLocalMedicalService(){
        
        ReportingCondition = new wb_MedicalInsuranceDetail__c();
    }
    
    public void execute(){
        
        List<Id> IndIDs = new List<Id>();
        LocalMedicalInsuranceIndividual=
            [select  Individual__r.Parent__c, Individual__c,
             ContractCompany__r.name, ContractCompany__r.CountryName__c,
             InsuranceEndDate__c, Insurance__c
             from wb_MedicalInsuranceDetail__c 
             where InsuranceEndDate__c > 2017-01-01
             and MedicalInsurance__r.MedicalDivision__c ='現地医療' and 
             ( Individual__r.f_Classification__c ='会員' or Individual__r.Parent__r.f_Classification__c ='会員' )];
        
        for ( wb_MedicalInsuranceDetail__c lmsi:LocalMedicalInsuranceIndividual) 
        {
            if ( lmsi.Individual__r.Parent__c != null )
                IndIDs.add(lmsi.Individual__r.Parent__c);
            else
                IndIDs.add(lmsi.Individual__c);
        }
       
        List<wb_Member__c> Members =
            [select Individual__c, MembershipDetail__r.Membership__r.ContractCompany__c, 
             MembershipDetail__r.Membership__r.ContractCountry__c
             from wb_Member__c
             where Individual__c =:IndIDs 
             order by Individual__c];
        
       // List<Contact> contacts = [SELECT Name, Id FROM Contact ORDER BY Id LIMIT 10]; // We'll reorder by Name later
        Map<String, wb_Member__c> MembersMap = new Map<String, wb_Member__c>(); // Reversed for sorting
        List<String> sortThis = new List<String>();
        
        for(wb_Member__c m : Members)
        {
            MembersMap.put(string.valueof(m.Individual__c), m); // For simplicity in this example, we assume the name is unique
            sortThis.add(string.valueof(m.Individual__c));
        }
        
        sortThis.sort(); // Sort by Name in this case    
        List<wb_Member__c> SortedMembers = new List<wb_Member__c>();
        
        for(String s : sortThis)
        {
            SortedMembers.add(MembersMap.get(s));
        }
        
        wb_Member__c theMember;
        for ( wb_MedicalInsuranceDetail__c lmsi:LocalMedicalInsuranceIndividual) {
            
            if ( lmsi.Individual__r.Parent__c != null ) {
               theMember = Search(String.Valueof(lmsi.Individual__r.Parent__c),SortedMembers);
                
            }
            else {
                theMember = Search(string.valueof(lmsi.Individual__c),SortedMembers);
            }
            system.debug(theMember);
            system.debug(lmsi);
            if (theMember != null){
                if (theMember.MembershipDetail__r.Membership__r.ContractCompany__c != null)
                	lmsi.ContractCompany__r.name = theMember.MembershipDetail__r.Membership__r.ContractCompany__c;
                if (theMember.MembershipDetail__r.Membership__r.ContractCountry__c != null)
                	lmsi.ContractCompany__r.CountryName__c = theMember.MembershipDetail__r.Membership__r.ContractCountry__c;
            }
            
        }
        

    }
    
        
    public wb_Member__c Search(string Pid, List<wb_Member__c> Index){
		system.debug(Pid);
        system.debug(Index);
        Integer low = 0;
        Integer high = Index.size();
        if (Index.size()>0 && Pid != null){
            boolean found = false;
            while (found == false && high != low ){
                string pivot = String.valueof(Index[low + (high-low)/2].Individual__c);
                system.debug(pivot);
                system.debug(Pid);
                if ( pivot == Pid){
                    found = true;
                    return Index[low + (high-low)/2];
                }
                else if (pivot > Pid){
                    high = low + (high-low)/2;
                } else {
                    if (low == low + (high-low)/2){
                        return null;
                    }
                    else{
                        high = high - (high-low)/2;
                    }
                }
            }
        } 
        
        return null;
    }
    

}