unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AffiliatedCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業グループ</label>
        <referenceTo>AffiliatedCompany__c</referenceTo>
        <relationshipLabel>会社情報</relationshipLabel>
        <relationshipName>R00N10000000uu4tEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CompanyCd__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>会社コード</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/BL__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BL (契約会社名称)</relationshipLabel>
        <relationshipName>BL1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BL</label>
    <nameField>
        <displayFormat>BL{000000}</displayFormat>
        <label>BL番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>法人契約の場合は、
虫メガネから契約会社名称を
検索して選択します。

個人契約の場合は、
虫メガネから「個人契約」を
検索して選択します。</inlineHelpText>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>契約情報 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HXmTEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>R00N10000000I9MMEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuKeitai__c</fullName>
        <label>契約形態</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Commodity__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>法人／家族Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>個人／家族Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>法人／家族Global Member</fullName>
                </value>
                <value>
                    <fullName>法人／家族China</fullName>
                </value>
                <value>
                    <fullName>個人／家族China</fullName>
                </value>
                <value>
                    <fullName>法人／家族Asian</fullName>
                </value>
                <value>
                    <fullName>個人／家族Asian</fullName>
                </value>
                <value>
                    <fullName>法人／家族C&amp;V</fullName>
                </value>
                <value>
                    <fullName>個人／家族C&amp;V</fullName>
                </value>
                <value>
                    <fullName>法人／家族Asian B Plan</fullName>
                </value>
                <value>
                    <fullName>法人／家族</fullName>
                </value>
                <value>
                    <fullName>個人／家族</fullName>
                </value>
                <value>
                    <fullName>チャイナボウルファミリー</fullName>
                </value>
                <value>
                    <fullName>法人／家族Medi-X</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <formula>MemberShimei__r.KinmuCompany__r.Name</formula>
        <label>勤務先会社</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>FamilyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OtaAgency__c</fullName>
        <label>取扱</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WB扱い</fullName>
                </value>
                <value>
                    <fullName>WB以外</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OtaInsuranceShuki__c</fullName>
        <label>保険満期</label>
        <type>Date</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Ichiroheian__c.object
<CustomObject>
    <fields>
        <fullName>InsuranceShuki__c</fullName>
        <label>（搭乗）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>旧（一路/安全）契約会社名称　2011/1/26　一路・安全・自動車の契約会社として使用する</description>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車保険関連 (契約会社名称)</relationshipLabel>
        <relationshipName>R00N10000000HfleEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>自動車保険関連</label>
    <nameField>
        <label>登録番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Kenshin__c.object
<CustomObject>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <formula>IF ( MemberShimei__c   &lt;&gt;  &quot;&quot;, 
MemberShimei__r.KinmuCompany__r.Name,
MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.Name )</formula>
        <label>勤務先会社</label>
        <type>Text</type>
    </fields>
    <label>健診</label>
    <nameField>
        <displayFormat>K{0000000}</displayFormat>
        <label>健診番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HUqkEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuKeitai__c</fullName>
        <label>契約形態</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Commodity__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>法人／単身Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>法人／家族Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>個人／単身Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>個人／家族Global Plus Member</fullName>
                </value>
                <value>
                    <fullName>法人／単身Global Member</fullName>
                </value>
                <value>
                    <fullName>法人／家族Global Member</fullName>
                </value>
                <value>
                    <fullName>法人／無記名Biz Trip Pass</fullName>
                </value>
                <value>
                    <fullName>法人／無記名Visitor Pass</fullName>
                </value>
                <value>
                    <fullName>法人／単身China</fullName>
                </value>
                <value>
                    <fullName>法人／家族China</fullName>
                </value>
                <value>
                    <fullName>法人／無記名China</fullName>
                </value>
                <value>
                    <fullName>個人／単身China</fullName>
                </value>
                <value>
                    <fullName>個人／家族China</fullName>
                </value>
                <value>
                    <fullName>法人／単身Asian</fullName>
                </value>
                <value>
                    <fullName>法人／家族Asian</fullName>
                </value>
                <value>
                    <fullName>法人／無記名Asian</fullName>
                </value>
                <value>
                    <fullName>個人／単身Asian</fullName>
                </value>
                <value>
                    <fullName>個人／家族Asian</fullName>
                </value>
                <value>
                    <fullName>法人／単身C&amp;V</fullName>
                </value>
                <value>
                    <fullName>法人／家族C&amp;V</fullName>
                </value>
                <value>
                    <fullName>法人／無記名C&amp;V</fullName>
                </value>
                <value>
                    <fullName>個人／単身C&amp;V</fullName>
                </value>
                <value>
                    <fullName>個人／家族C&amp;V</fullName>
                </value>
                <value>
                    <fullName>法人／単身Asian B Plan</fullName>
                </value>
                <value>
                    <fullName>法人／家族Asian B Plan</fullName>
                </value>
                <value>
                    <fullName>法人／無記名Asian B Plan</fullName>
                </value>
                <value>
                    <fullName>法人／無記名Asian Biz Trip Plan</fullName>
                </value>
                <value>
                    <fullName>法人／単身</fullName>
                </value>
                <value>
                    <fullName>法人／家族</fullName>
                </value>
                <value>
                    <fullName>法人／無記名</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KinmuCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N10000000HuCZEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OtaAgency__c</fullName>
        <label>取扱</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WB扱い</fullName>
                </value>
                <value>
                    <fullName>WB以外</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OtaInsuranceShuki__c</fullName>
        <label>保険満期</label>
        <type>Date</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/GroupReportController.cls
public class GroupReportController
{ 
  private ApexPages.StandardController m_con;
  private AffiliatedCompany__c m_group;
  public GroupData Data {get; set;}
  public List<GroupData.Row> Rows {get; set;}
  
  public GroupReportController(ApexPages.StandardController con)
  {
    m_con = con;
    m_group = (AffiliatedCompany__c)con.getRecord();
    Data = new GroupData();
    Rows = Data.Rows;
  }
  
  public void Init()
  {
    List<MemberInfo__c> members;
    List<string> mids = new List<string>();
    List<string> fids = new List<string>();

     List<Id> kids = new list<Id>();
    for(Account a : [select Id from Account where AffiliatedCompanyName__c=:m_group.Id])
        kids.add(a.Id);
    
    members = [select Id, KeiyakuKeitai__c, OtaAgency__c, OtaInsuranceShuki__c, (select Id from FamilyMembers__r), 
        KeiyakuCompanyName__r.Id, KeiyakuCompanyName__r.Name, 
        KinmuCompany__r.Id, KinmuCompany__r.Name, KinmuCompany__r.CompanyCd__c, KinmuCompany__r.ShozokuArea__c, KinmuCompany__r.EigyoTanto__r.Name
        from MemberInfo__c 
        where (KinmuCompany__c in :kids)
        and (TaikaiDate__c=:null or TaikaiDate__c>:system.today())
        order by KinmuCompany__r.CompanyCd__c, KeiyakuCompanyName__r.Name];
        
    GroupData.Row r = null;
    
    for(integer i=0; i<members.size(); i++)    
    {
      MemberInfo__c m = members[i]; 
      mids.add(m.Id);
      r = null;
      for(integer j=0; j<Rows.size(); j++)
      {
        if(Rows[j].Match(m.KinmuCompany__r, m.KeiyakuCompanyName__r))
        {
          r = Rows[j];
          break;
        }
      }
      if(r==null)
      {
        r = Data.addRow(m.KinmuCompany__r, m.KeiyakuCompanyName__r);
      }
            
      if(m.KeiyakuKeitai__c.indexOf('単身')>=0)
        r.KeitaiCdS = r.KeitaiCdS + 1;
      else if(m.KeiyakuKeitai__c.indexOf('家族')>=0)
        r.KeitaiCdF = r.KeitaiCdF + 1;
      else if(m.KeiyakuKeitai__c.indexOf('無記名')>=0)
        r.KeitaiCdM = r.KeitaiCdM + 1;
        
      if(m.FamilyMembers__r!=null)  
        for(integer j=0; j<m.FamilyMembers__r.size(); j++)
          fids.add(m.FamilyMembers__r[j].Id);
      
      if((m.OtaAgency__c=='WB扱い')&&(m.OtaInsuranceShuki__c>=system.today()))
        r.OtaAgency = true;
    }
      
    
    List< Ichiroheian__c> ics;
   
    ics = [select Id, 
        ShiyoCompanyName__r.Id, ShiyoCompanyName__r.Name, ShiyoCompanyName__r.CompanyCd__c,
        ShiyoCompanyName__r.ShozokuArea__c, ShiyoCompanyName__r.EigyoTanto__r.Name
        from Ichiroheian__c 
        where ShiyoCompanyName__c in :kids 
        and InsuranceShuki__c>=:system.today()
        and CancelDate__c=:null
        order by ShiyoCompanyName__r.CompanyCd__c];
        
    for(integer i=0; i<ics.size(); i++)    
    {
      Ichiroheian__c ic = ics[i]; 
      r = null;
      for(integer j=0; j<Rows.size(); j++)
      {
        if(Rows[j].Match(ic.ShiyoCompanyName__r))
        {
          r = Rows[j];
          r.Ichiroheian = r.Ichiroheian+1;
        }
      }
      if(r==null)
      {
        r = Data.addRow(ic.ShiyoCompanyName__r, ic.ShiyoCompanyName__r);
        r.Ichiroheian = r.Ichiroheian+1;
      }
    }
    
    
    ics = [select Id, 
        ShiyoCompanyName__r.Id, ShiyoCompanyName__r.Name, ShiyoCompanyName__r.CompanyCd__c,
        ShiyoCompanyName__r.ShozokuArea__c, ShiyoCompanyName__r.EigyoTanto__r.Name
        from Ichiroheian__c 
        where ShiyoCompanyName__c in :kids
        and (    (OI_InsuranceShuki__c>=:system.today() and OI_InsuranceCancel__c=:null)
              or (VI_InsuranceShuki__c>=:system.today() and VI_InsuranceCancel__c=:null) )
        order by ShiyoCompanyName__r.CompanyCd__c];
        
    for(integer i=0; i<ics.size(); i++)    
    {
      Ichiroheian__c ic = ics[i]; 
      r = null;
      for(integer j=0; j<Rows.size(); j++)
      {
        if(Rows[j].Match(ic.ShiyoCompanyName__r))
        {
          r = Rows[j];
          r.OIIchiroheian = r.OIIchiroheian+1;
        }
      }
      if(r==null)
      {
        r = Data.addRow(ic.ShiyoCompanyName__r, ic.ShiyoCompanyName__r);
        r.OIIchiroheian = r.OIIchiroheian+1;
      }
    }
    
    
    List<BL__c> bls = [select Id, 
        Insurant__r.Id, Insurant__r.Name, Insurant__r.CompanyCd__c,
        Insurant__r.ShozokuArea__c, Insurant__r.EigyoTanto__r.Name
        from BL__c
        where Insurant__c in :kids
        and CancelDate__c=:null and InsuranceManki__c>=:system.today()
        order by Insurant__r.CompanyCd__c];
    
    for(integer i=0; i<bls.size(); i++)    
    {
      BL__c bl = bls[i]; 
      r = null;
      for(integer j=0; j<Rows.size(); j++)
      {
        if(Rows[j].Match(bl.Insurant__r))
        {
          r = Rows[j];
          r.BL = true;
        }
      }
      if(r==null)
      {
        r = Data.addRow(bl.Insurant__r, bl.Insurant__r);
        r.BL = true;
      }
    }
      
      
    date sd = date.newInstance(system.today().year()-1, 1, 1);
    date ed = date.newInstance(system.today().year(), 1, 1);  
    List<Kenshin__c> kss;
    
    kss = [select Id,
        MemberShimei__r.KeiyakuCompanyName__r.Id, MemberShimei__r.KeiyakuCompanyName__r.Name, 
        MemberShimei__r.KinmuCompany__r.Id, MemberShimei__r.KinmuCompany__r.Name, 
        MemberShimei__r.KinmuCompany__r.ShozokuArea__c, MemberShimei__r.KinmuCompany__r.EigyoTanto__r.Name,
        MemberShimei__r.KinmuCompany__r.CompanyCd__c,
        MemberFamilyShimei__r.MemberShimei__r.KeiyakuCompanyName__r.Id, MemberFamilyShimei__r.MemberShimei__r.KeiyakuCompanyName__r.Name, 
        MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.Id, MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.Name, 
        MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.CompanyCd__c,
        MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.ShozokuArea__c, MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r.EigyoTanto__r.Name
        from Kenshin__c
        where (MemberShimei__r.KinmuCompany__c in :kids or MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__c in :kids)
        and (KenshinDate__c>=:sd)
        and (KenshinDate__c<:ed)
        and (CancelDate__c=:null)];
        

    for(integer i=0; i<kss.size(); i++)    
    {
      Kenshin__c ks = kss[i]; 
      r = null;
      for(integer j=0; j<Rows.size(); j++)
      {
        if(ks.MemberShimei__r!=null)
        {
        
            if(Rows[j].Match(ks.MemberShimei__r.KinmuCompany__r))
            {
              r = Rows[j];
              r.Kenshin = r.Kenshin+1;
            }
        }
        else if(ks.MemberFamilyShimei__r!=null)
        {
            if(ks.MemberFamilyShimei__r.MemberShimei__r!=null)
                if(Rows[j].Match(ks.MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r))
                {
                  r = Rows[j];
                  r.Kenshin = r.Kenshin+1;
                }
        }
      }
      System.debug('r ' + r);
      if(r==null)
      {
      System.debug(ks.MemberShimei__r);
        if(ks.MemberShimei__r!=null){
          //system.debug('in first');
          r = Data.addRow(ks.MemberShimei__r.KinmuCompany__r, ks.MemberShimei__r.KinmuCompany__r);  
        }     
        else if(ks.MemberFamilyShimei__r!=null){
          system.debug('in second');
          r = Data.addRow(ks.MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r, ks.MemberFamilyShimei__r.MemberShimei__r.KinmuCompany__r);       
        }
        if(r!=null)
          r.Kenshin = r.Kenshin+1;
      }
    }
  }
  
  /*
  static testMethod void GroupReportController_Test()
  {
    AffiliatedCompany__c gp = TestUtil.createTestGroup();
    Account acKinmu = TestUtil.createTestAccount('KinmuTest');
    Account acKinmu2 = TestUtil.createTestAccount('KinmuTest2');
    Account acKeiyaku = TestUtil.createTestAccount('KeiyakuTest');
    Account acKeiyaku2 = TestUtil.createTestAccount('KeiyakuTest2');
    ContractInfo__c ci = TestUtil.createTestContract(acKeiyaku.Id);
    ContractInfo__c ci2 = TestUtil.createTestContract(acKeiyaku2.Id);
    Account acKeiyakuCompany = TestUtil.createTestAccount('KeiyakuCompanyTest');
    MemberInfo__c mi = TestUtil.createTestMemberInfo(acKinmu.Id, ci.Id, acKeiyakuCompany.Id);
    MemberInfo__c mi2 = TestUtil.createTestMemberInfo(acKinmu.Id, ci.Id, acKeiyakuCompany.Id);
    Ichiroheian__c i1 = TestUtil.createTestIchiroheian(acKeiyaku.Id);
    Ichiroheian__c i2 = TestUtil.createTestIchiroheian(acKeiyaku.Id);
    BL__c bl1 = TestUtil.createTestBL(acKeiyaku.Id);
    BL__c bl2 = TestUtil.createTestBL(acKeiyaku.Id);
    Kenshin__c k1 = TestUtil.createTestKenshin(mi.Id);
    Kenshin__c k2 = TestUtil.createTestKenshin(mi.Id);
    acKinmu.AffiliatedCompanyName__c = gp.Id;
    update(acKinmu);
    acKeiyaku.AffiliatedCompanyName__c = gp.Id;
    update(acKeiyaku);
    acKinmu2.AffiliatedCompanyName__c = gp.Id;
    update(acKinmu);
    acKeiyaku2.AffiliatedCompanyName__c = gp.Id;
    update(acKeiyaku);
    mi.KeiyakuKeitai__c = '法人／家族';
    mi.OtaAgency__c = 'WB扱い';
    mi.OtaInsuranceShuki__c = system.today();
    update(mi);
    mi2.KeiyakuKeitai__c = '法人／無記名';
    update(mi2);
    i1.OI_InsuranceShuki__c = system.today();
    update(i1);
    i2.OI_InsuranceShuki__c = system.today();
    update(i2);
      
    ApexPages.StandardController scon = new ApexPages.StandardController(gp);
    GroupReportController con = new GroupReportController(scon);
    con.init();
  
  }
  */
}