unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（営業担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmmEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WB内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>会社情報（内務担当）</relationshipLabel>
        <relationshipName>R00N10000000HYmrEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shimei__c</fullName>
        <label>メディック担当者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>契約情報 (営業担当)</relationshipLabel>
        <relationshipName>R00N10000000HYtbEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>南京</fullName>
                </value>
                <value>
                    <fullName>合肥</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
                <value>
                    <fullName>東京</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>契約情報 (内務担当)</relationshipLabel>
        <relationshipName>R00N10000000HYm4EAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shimei__c</fullName>
        <inlineHelpText>法人契約の場合は、
担当者名を入力します。

個人契約の場合は、
契約個人名を入力します。</inlineHelpText>
        <label>氏名</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Shimei__c.object
<CustomObject>
    <label>社員名簿</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/ContractInfoBatchProcessController_Test.cls
@isTest
public class ContractInfoBatchProcessController_Test {
    
    static testMethod void ContractInfoBatchProcessControllerTest(){
        Account acKinmu = TestUtil.createTestAccount('KinmuTest');
        ContractInfo__c ci = TestUtil.createTestContract(acKinmu.Id);
        ci.KeiyakuArea__c = '東京';
        Shimei__c SalesA = TestUtil.createShimei('SA','001','SA','SA','正社員','WB Japan',
                                                '日本','営業','営業内務','WB Japan','東京',system.today(),
                                                '女','日本',system.today());
        Shimei__c SalesB = TestUtil.createShimei('SB','002','SB','SB','正社員','WB Japan',
                                                '日本','営業','営業内務','WB Japan','東京',system.today(),
                                                '女','日本',system.today());
        Shimei__c ClerkA = TestUtil.createShimei('CA','003','CA','CA','正社員','WB Japan',
                                                '日本','営業','営業内務','WB Japan','東京',system.today(),
                                                '女','日本',system.today());
       // Shimei__c ClerkB = TestUtil.createShimei('CB');
        ci.EigyoTanto__c = SalesA.ID;
        ci.NaimuTanto__c = ClerkA.ID;
        update ci;
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new ContractInfo__c());
        ContractInfoBatchProcessController ContractBatchProcess = new ContractInfoBatchProcessController(sc);
        ContractBatchProcess.contractDataFromPage.KeiyakuArea__c = '東京';
        ContractBatchProcess.contractDataFromPage.EigyoTanto__c = SalesA.ID;
        ContractBatchProcess.search();
        ContractBatchProcess.inputLookUp.EigyoTanto__c = SalesB.Id;
        ContractBatchProcess.selectAll();
        ContractBatchProcess.updateRecord();
        ContractBatchProcess.contractDataFromPage.EigyoTanto__c = SalesB.ID;
        ContractBatchProcess.search();
        ContractBatchProcess.releaseAll();
        
      
    }


}