unpackaged/objects/AffiliatedHospital__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Area__c</fullName>
        <label>(契約情報) エリア</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Category__c</fullName>
        <label>(契約情報) 病院区分</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>総合</fullName>
                </value>
                <value>
                    <fullName>専門</fullName>
                </value>
                <value>
                    <fullName>クリニック</fullName>
                </value>
                <value>
                    <fullName>歯科</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Country__c</fullName>
        <label>(契約情報) 国</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>中国</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>マカオ</fullName>
                </value>
                <value>
                    <fullName>ベトナム</fullName>
                </value>
                <value>
                    <fullName>インド</fullName>
                </value>
                <value>
                    <fullName>インドネシア</fullName>
                </value>
                <value>
                    <fullName>フィリピン</fullName>
                </value>
                <value>
                    <fullName>カンボジア</fullName>
                </value>
                <value>
                    <fullName>ミャンマー</fullName>
                </value>
                <value>
                    <fullName>ラオス</fullName>
                </value>
                <value>
                    <fullName>スリランカ</fullName>
                </value>
                <value>
                    <fullName>マレーシア</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>タイ</fullName>
                </value>
                <value>
                    <fullName>韓国</fullName>
                </value>
                <value>
                    <fullName>台湾</fullName>
                </value>
                <value>
                    <fullName>オーストラリア</fullName>
                </value>
                <value>
                    <fullName>メキシコ</fullName>
                </value>
                <value>
                    <fullName>イギリス</fullName>
                </value>
                <value>
                    <fullName>ドイツ</fullName>
                </value>
                <value>
                    <fullName>フランス</fullName>
                </value>
                <value>
                    <fullName>オランダ</fullName>
                </value>
                <value>
                    <fullName>ロシア</fullName>
                </value>
                <value>
                    <fullName>UAE</fullName>
                </value>
                <value>
                    <fullName>ブラジル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_HospitalName__c</fullName>
        <label>(契約情報) 病院名</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_HospitalPopularName__c</fullName>
        <label>(契約情報) 病院名(通称)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Region__c</fullName>
        <label>(契約情報) 州／県</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Zone__c</fullName>
        <label>(契約情報) 地区</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Sort_Order__c</fullName>
        <formula>Case(Contract_Country__c,
&quot;中国&quot;,10,
&quot;香港&quot;,20,
&quot;マカオ&quot;,30,
&quot;シンガポール&quot;,40,
&quot;マレーシア&quot;,50,
&quot;タイ&quot;,60,
&quot;ミャンマー&quot;,70,
&quot;カンボジア&quot;,80,
&quot;ベトナム&quot;,90,
&quot;インド&quot;,100,
&quot;スリランカ&quot;,110,
&quot;インドネシア&quot;,120,
&quot;フィリピン&quot;,130,
&quot;メキシコ&quot;,200,
&quot;台湾&quot;,300,
&quot;韓国&quot;,310,
&quot;ラオス&quot;,320,
&quot;バングラデシュ&quot;,330,
&quot;オーストラリア&quot;,400,
&quot;イギリス&quot;,500,
&quot;ドイツ&quot;,510,
&quot;ロシア&quot;,600,
&quot;UAE&quot;,700,
900)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（表示順）国番号</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HospitalInfo_24HoursRemarks__c</fullName>
        <label>(病院情報) 24時間対応(注意文)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HospitalInfo_24Hours__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>※24時間対応の病院は、「受診場所」が24時間対応とは限りません。</fullName>
                </value>
                <value>
                    <fullName>※病院のHPで開院時間をご確認ください。</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HospitalInfo_24Hours__c</fullName>
        <label>(病院情報) 24時間対応</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>24時間</fullName>
                </value>
                <value>
                    <fullName>昼間./場合により夜間</fullName>
                </value>
                <value>
                    <fullName>昼間のみ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HospitalInfo_HospitalStaffLanguage__c</fullName>
        <label>(病院情報) 病院スタッフ言語</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>病院スタッフ日本語可</fullName>
                </value>
                <value>
                    <fullName>病院スタッフ英語可</fullName>
                </value>
                <value>
                    <fullName>病院スタッフ日英可</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HospitalInfo_MedicalDepartment__c</fullName>
        <label>(病院情報) 診療科目</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HospitalInfo_SurgeryHours__c</fullName>
        <label>(病院情報) 診察時間</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HospitalInfo_VisitTo__c</fullName>
        <label>(病院情報) 受診場所</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Address__c</fullName>
        <label>病院住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Category_Order__c</fullName>
        <formula>case(Contract_Category__c,
&quot;総合&quot;,1,
&quot;専門&quot;,2,
&quot;クリニック&quot;,3,
&quot;歯科&quot;,4,
9)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（表示順）病院区分番号</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hospital_Sort_Order__c</fullName>
        <label>（表示順）病院番号</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hospital_Tel__c</fullName>
        <label>病院電話番号</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Longitude_Latitude__c</fullName>
        <label>病院場所 緯度経度</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_HPDeleteRequestedDate__c</fullName>
        <label>(HP_ハンドブック掲載) HP削除依頼日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_HPPostRequestedDate__c</fullName>
        <label>(HP_ハンドブック掲載) HP掲載依頼日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region_Sort_Order__c</fullName>
        <label>（表示順）州／県番号</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WBStaff_StationedHospital__c</fullName>
        <label>(WBスタッフ) 病院常駐有無</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>常駐（平日/一部土日）</fullName>
                </value>
                <value>
                    <fullName>常駐（平日のみ）</fullName>
                </value>
                <value>
                    <fullName>ご依頼時派遣</fullName>
                </value>
                <value>
                    <fullName>予約手配のみ</fullName>
                </value>
                <value>
                    <fullName>予約手配のみ（病院日本語可）</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WBStaff_StationedTime__c</fullName>
        <label>(WBスタッフ) 病院常駐時間</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Zone_Sort_Order__c</fullName>
        <label>（表示順）地区番号</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>appDeletedDate__c</fullName>
        <label>（アプリ）削除日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>appPostingDate__c</fullName>
        <label>（アプリ）掲載日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>f_AppDeleteTarget__c</fullName>
        <formula>if ( OR( 
AND( Not ISBLANK(Post_HPDeleteRequestedDate__c), ISBLANK(appDeletedDate__c)) 
, AND( Not ISBLANK(Post_HPDeleteRequestedDate__c), Post_HPPostRequestedDate__c &gt; appDeletedDate__c) 
) 
, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>f_AppDeleteTarget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>f_AppPostingTarget__c</fullName>
        <formula>if ( OR ( Post_HPPostRequestedDate__c &gt; appPostingDate__c, 
AND( AND(ISBLANK(appPostingDate__c), ISBLANK(appDeletedDate__c)) , NOT ISBLANK(Post_HPPostRequestedDate__c) ) 
) , true, false)

/*
if ( OR ( Post_HPPostRequestedDate__c &gt; appPostingDate__c, 
AND( ISBLANK(appPostingDate__c), NOT ISBLANK(Post_HPPostRequestedDate__c) ) 
) , true, false)
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>f_AppPostingTarget</label>
        <type>Checkbox</type>
    </fields>
    <label>提携病院</label>
    <nameField>
        <displayFormat>HOSP-{00000}</displayFormat>
        <label>提携病院番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/APIDebugLog__c.object
<CustomObject>
    <fields>
        <fullName>Log__c</fullName>
        <label>ログ</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>API Debug　Log</label>
    <nameField>
        <label>API 名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_AffiliatedHospital_2ndPhs.cls
@RestResource(urlMapping='/2ndPhs/AffiliatedHospital/*')
global with sharing class wb_soap_AffiliatedHospital_2ndPhs {
    
    global class AffiliatedHospital{
        global Id Id; 
        
        global string ContractHospitalName;
        global string ContractHospitalPopularName;
        
        global string ContractArea;
        global string ContractCountry;   
        global string ContractRegion;
        global string ContractZone;
        global string ContractCategory;
        
        global string HospitalAddress;
        global string HospitalTel;
        global string HospitalInfo24Hours;
        global string HospitalInfo24HoursRemarks;
        global string HospitalInfoMedicalDepartment;
        global string HospitalInfoSurgeryHours;
        global string HospitalInfoVisitTo;
        global string HospitalInfoHospitalStaffLanguage;
        
        global string WBStaffStationedHospital;
        global string WBStaffStationedTime;
        global string LongitudeLatitude;
        
        global string HospitalCategoryOrder;    
        global string HospitalSortOrder;
        global string CountrySortOrder;
        global string RegionSortOrder;
        global string ZoneSortOrder;
        
        public AffiliatedHospital(AffiliatedHospital__c h){
            Id = h.Id;
            
            ContractHospitalName= h.Contract_HospitalName__c;
            ContractHospitalPopularName= h.Contract_HospitalPopularName__c;
            
            
            ContractArea= h.Contract_Area__c;
            ContractCountry= h.Contract_Country__c;
            ContractZone= h.Contract_Zone__c;
            ContractRegion= h.Contract_Region__c;
            ContractCategory= h.Contract_Category__c;
            
            HospitalAddress	= h.Hospital_Address__c;
            HospitalTel= h.Hospital_Tel__c;
            HospitalInfo24Hours	= h.HospitalInfo_24Hours__c;
            HospitalInfo24HoursRemarks = h.HospitalInfo_24HoursRemarks__c;
            HospitalInfoMedicalDepartment= h.HospitalInfo_MedicalDepartment__c;
            HospitalInfoVisitTo	= h.HospitalInfo_VisitTo__c;
            HospitalInfoSurgeryHours= h.HospitalInfo_SurgeryHours__c;
            HospitalInfoHospitalStaffLanguage= h.HospitalInfo_HospitalStaffLanguage__c;
            
            WBStaffStationedHospital= h.WBStaff_StationedHospital__c;
            WBStaffStationedTime= h.WBStaff_StationedTime__c;
            LongitudeLatitude= h.Longitude_Latitude__c;
            
            HospitalCategoryOrder= string.valueOf(h.Hospital_Category_Order__c);
            HospitalSortOrder= string.valueOf(h.Hospital_Sort_Order__c);
            
            CountrySortOrder= string.valueOf( h.Country_Sort_Order__c);    
            RegionSortOrder= string.valueOf(h.Region_Sort_Order__c);
            //ZoneSortOrder = h.Contract_Zone__c;
            ZoneSortOrder= string.valueOf(h.Zone_Sort_Order__c);
            
        }
        
    }
    
    
    @HttpGet
    global static List<AffiliatedHospital> getAffiliatedHospitalInfo() {

        
        RestRequest req = RestContext.request;
        
        string HospitalName;
        if ( req.params.get('HospitalName') != null)
            HospitalName= req.params.get('HospitalName');
        
        string Country;
        if (  req.params.get('Country') != null)
            Country =  req.params.get('Country') ;
        date PostRequestDate;
        if (req.params.get('PostRequestDate') != null)
            PostRequestDate = date.parse(req.params.get('PostRequestDate'));
        date DeleteRequestDate;
        if (req.params.get('DeleteRequestDate')!=null)
            DeleteRequestDate = date.parse(req.params.get('DeleteRequestDate'));
        
      //  insert new APIDebugLog__c(Log__c='@@@ params HospitalName= '+HospitalName+' Country='+Country+' PostRequestDate='+PostRequestDate);
        
        string wheresql;
        
        if (HospitalName != null) {
 
             wheresql = '  Contract_HospitalName__c like \'%' + HospitalName + '%\' ' ; 
        }
        
        if (Country != null) {
            if (wheresql == null)
       
            	wheresql = ' Contract_Country__c like \'%' + Country + '%\'  ' ; 
            else 
          
            	wheresql = wheresql + ' and Contract_Country__c like \'%' + Country + '%\' ' ; 
        }
        
        
        
        if (PostRequestDate != null) {
     
            Datetime dt = datetime.newInstance(PostRequestDate.year(), PostRequestDate.month(),PostRequestDate.day());
            String formattedDate = dt.format('YYYY-MM-dd');
            
            if (wheresql == null)
       
                wheresql = '  Post_HPPostRequestedDate__c >= ' + formattedDate + ' and f_AppPostingTarget__c = true  '  ; 
            else 
                wheresql = wheresql + ' and  Post_HPPostRequestedDate__c >= ' + formattedDate + ' and f_AppPostingTarget__c = true  ';  
        }
        
        if (DeleteRequestDate != null) {
            // Datetime dt = new Datetime(PostingRequestDate);
            Datetime dt = datetime.newInstance(DeleteRequestDate.year(), DeleteRequestDate.month(),DeleteRequestDate.day());
            String formattedDate = dt.format('YYYY-MM-dd');
            
            if (wheresql == null)
                wheresql = ' Post_HPDeleteRequestedDate__c >= ' + formattedDate + ' and f_AppDeleteTarget__c = true ' ; 
            else 
                wheresql = wheresql + ' and Post_HPDeleteRequestedDate__c >= ' + formattedDate + ' and f_AppDeleteTarget__c = true ' ;  
        }
        
        if (PostRequestDate !=null && DeleteRequestDate != null )
            return null;
        
        List<AffiliatedHospital__c> HospitalList = new List<AffiliatedHospital__c>();
        
        
        
        
        if (wheresql != null ){
  
            string soql = ' select id, Zone_Sort_Order__c, WBStaff_StationedTime__c, WBStaff_StationedHospital__c, Region_Sort_Order__c, ';
            soql = soql + ' Longitude_Latitude__c,Hospital_Tel__c,Hospital_Sort_Order__c,HospitalInfo_VisitTo__c,HospitalInfo_SurgeryHours__c,';
            soql = soql + ' HospitalInfo_MedicalDepartment__c,HospitalInfo_HospitalStaffLanguage__c,HospitalInfo_24Hours__c,HospitalInfo_24HoursRemarks__c,';
            soql = soql + ' Hospital_Category_Order__c,Hospital_Address__c,Country_Sort_Order__c,Contract_Zone__c,Contract_Region__c,';
            soql = soql + ' Contract_HospitalPopularName__c,Contract_HospitalName__c,Contract_Country__c,Contract_Category__c,Contract_Area__c';
            soql = soql + ' from AffiliatedHospital__c where ' + wheresql ; //+ ' limit 3';
           // insert new APIDebugLog__c(Log__c=soql);
            HospitalList = Database.query(soql);
            
        }
        
        List<AffiliatedHospital> Lst = new List<AffiliatedHospital>();
        if (HospitalList.size()>0) {
            
            
            for (AffiliatedHospital__c h:HospitalList){
                // Lst.add(new AffiliatedHospital(h,HospitalInfo_24HoursRemarksList) );
                Lst.add(new AffiliatedHospital(h) );
            } 
        }
        
        
        return  Lst;
        
    }
    
    global class SimularGroup{
        global string Area;
        global string Country;
        global string Region;
        global string Zone;
        global string Category;
    }
    
    global class SimularHospital{
        
        global string ContractArea;
        global string ContractCountry;   
        global string ContractRegion;
        global string ContractZone;
        global string ContractCategory;
        
        global Id Id; 
        global string ContractHospitalName;
        global string HospitalSortOrder;
        
        
        
        public SimularHospital(AffiliatedHospital__c h){
            
            ContractArea= h.Contract_Area__c;
            ContractCountry= h.Contract_Country__c;
            ContractZone= h.Contract_Zone__c;
            ContractRegion= h.Contract_Region__c;
            ContractCategory= h.Contract_Category__c;
            
            Id = h.Id;
            
            ContractHospitalName= h.Contract_HospitalName__c;
            HospitalSortOrder= string.valueOf(h.Hospital_Sort_Order__c);
            
            
        }
        
    }
     
    
    @HttpPost
    global static List<SimularHospital> returnSimularHospitalInfo(SimularGroup HGroup){
        
        List<AffiliatedHospital__c> HospitalList = new List<AffiliatedHospital__c>();
        
        if (HGroup != null ){
            
         //   insert new APIDebugLog__c(Log__c=HGroup.Area);
            HospitalList = [select Contract_Area__c,Contract_Country__c,Contract_Zone__c,Contract_Region__c,Contract_Category__c,
                            Id,Contract_HospitalName__c,Hospital_Sort_Order__c
                            from AffiliatedHospital__c
                            where Contract_Area__c=: HGroup.Area  and Contract_Country__c =:HGroup.Country
                            and Contract_Region__c =:HGroup.Region  and Contract_Zone__c =:HGroup.Zone
                            and Contract_Category__c =:HGroup.Category ];
            /*
                            where Contract_Area__c=: HGroup.Area  and Contract_Country__c =:HGroup.Country
                            and Contract_Region__c =:HGroup.Region  and Contract_Zone__c =:HGroup.Region
                            and Contract_Category__c =:HGroup.Category ]; */
            
        }
        
        List<SimularHospital> Lst = new List<SimularHospital>();
        if (HospitalList.size()>0) {
            
            for (AffiliatedHospital__c h:HospitalList){
                
                Lst.add(new SimularHospital(h) );
            } 
        }
        
        
        return  Lst;
        
    }
    
    global class AffiliatedHospitalPatchStatus{
        global string Id; 
        global string Status; 
        AffiliatedHospitalPatchStatus(Id theID, string theStatus){
            Id = theID;
            Status = theStatus;
        }
    }   

    global class HospitalOrder{
        global Id Id; 
        global integer SortOrder;
    }   
    
    global class AffiliatedHospitalPatchDate{
        global Id Id; 
        global date theDate; 
        AffiliatedHospitalPatchDate(Id aID, date aDate){
            Id = aID;
            theDate = aDate;
        }
        global AffiliatedHospitalPatchDate(){
            
        }
    }   
    
    @HttpPatch

    global static List<AffiliatedHospitalPatchStatus> updateAffiliatedHospital
        (
            List<HospitalOrder> PatchSortOrder,
            List<AffiliatedHospitalPatchDate> PatchPostingDate,
            List<AffiliatedHospitalPatchDate> PatchDeletedDate
        )
    {    
        
        if (PatchSortOrder != null && PatchPostingDate == null && PatchDeletedDate == null){
            
            if ( PatchSortOrder.size() > 0) {
                SavePoint sp = Database.setSavepoint();
                try {
                    List<wb_utility_quicksort.IdIndex> UAHIdIndex = new  List<wb_utility_quicksort.IdIndex>();
                    Id aId;
                    
                    for ( integer i = 0; i < PatchSortOrder.size(); i++){
                        aId = Id.valueOf( PatchSortOrder[i].Id);
                        UAHIdIndex.add( new wb_utility_quicksort.IdIndex(aId,i));
                    }
                    
                    wb_utility_quicksort QS = new wb_utility_quicksort();
                    QS.sortList = UAHIdIndex;
                    QS.sortcustomObjList();
                    List<Id> AHUIds = new List<Id>();
                    
                    for( wb_utility_quicksort.IdIndex i:UAHIdIndex){
                        if (i.Id != null){
                            AHUIds.add(i.Id);
                        }
                    }
                    if ( AHUIds.size() > 0){
                        
                        List<AffiliatedHospital__c> AHU = [select id, Hospital_Sort_Order__c
                                                           from AffiliatedHospital__c 
                                                           where Id =:AHUIds order by Id];
                        integer i=0;
                        integer j=0;
                        
                        for ( ; i < UAHIdIndex.size() ; i ++) {
                            for ( ; j < AHU.size() && UAHIdIndex[i].Id >= AHU[j].id ; ){
                                if (UAHIdIndex[i].Id == AHU[j].id){
                     
                                    HospitalOrder AH = PatchSortOrder[UAHIdIndex[i].Idx];

                                    AHU[j].Hospital_Sort_Order__c = Decimal.valueof(AH.SortOrder) ;

                                    j++;
                                    
                                } else
                                    j ++;
                            }
                        }
                        
                        update AHU;
                        List<AffiliatedHospitalPatchStatus> Rst = new List<AffiliatedHospitalPatchStatus>();
                        for (AffiliatedHospital__c h:AHU){
                            Rst.add( new AffiliatedHospitalPatchStatus( h.Id, 'Sorting Order Updated to:' + string.valueof(h.Hospital_Sort_Order__c)));
                        }
                        return Rst;
                        
                    }
                    
                } catch(Exception e) {
                    Database.rollBack(sp);
                    return null;
                } 
                
            }
            
        } else if (PatchSortOrder != null && PatchPostingDate != null && PatchDeletedDate == null){
            SavePoint sp = Database.setSavepoint();
            try {
                
                List<AffiliatedHospitalPatchStatus> Rst = new List<AffiliatedHospitalPatchStatus>();
                
                List<wb_utility_quicksort.IdIndex> UAHIdIndex = new  List<wb_utility_quicksort.IdIndex>();
                Id aId;
                
                for ( integer i = 0; i < PatchSortOrder.size(); i++){
                    aId = Id.valueOf( PatchSortOrder[i].Id);
                    UAHIdIndex.add( new wb_utility_quicksort.IdIndex(aId,i));
                }
                
                wb_utility_quicksort QS = new wb_utility_quicksort();
                QS.sortList = UAHIdIndex;
                QS.sortcustomObjList();
                List<Id> AHUIds = new List<Id>();
                
                for( wb_utility_quicksort.IdIndex i:UAHIdIndex){
                    if (i.Id != null){
                        AHUIds.add(i.Id);
                    }
                }
                
                if ( AHUIds.size() > 0){
                    
                    List<AffiliatedHospital__c> AHU = [select id, Hospital_Sort_Order__c
                                                       from AffiliatedHospital__c 
                                                       where Id =:AHUIds order by Id];
                    integer i=0;
                    integer j=0;
                    
                    for ( ; i < UAHIdIndex.size() ; i ++) {
                        for ( ; j < AHU.size() && UAHIdIndex[i].Id >= AHU[j].id ; ){
                            if (UAHIdIndex[i].Id == AHU[j].id){
                                HospitalOrder AH = PatchSortOrder[UAHIdIndex[i].Idx];
                                AHU[j].Hospital_Sort_Order__c = Decimal.valueof(AH.SortOrder) ;
                                j++;
                            } else
                                j ++;
                        }
                    }
                    
                    update AHU;
                    //  List<AffiliatedHospitalPatchStatus> Rst = new List<AffiliatedHospitalPatchStatus>();
                    for (AffiliatedHospital__c h:AHU){
                        Rst.add( new AffiliatedHospitalPatchStatus( h.Id, 'Sorting Order Updated to:' + string.valueof(h.Hospital_Sort_Order__c)));
                    }
                    
                    
                    
                }
                
                UAHIdIndex = new  List<wb_utility_quicksort.IdIndex>();
                //Id aId;
                
                for ( integer i = 0; i < PatchPostingDate.size(); i++){
                    aId = Id.valueOf( PatchPostingDate[i].Id);
                    UAHIdIndex.add( new wb_utility_quicksort.IdIndex(aId,i));
                }
                
                QS = new wb_utility_quicksort();
                QS.sortList = UAHIdIndex;
                QS.sortcustomObjList();
                
                AHUIds = new List<Id>();
                
                for( wb_utility_quicksort.IdIndex i:UAHIdIndex){
                    if (i.Id != null){
                        AHUIds.add(i.Id);
                    }
                }
                
                if ( AHUIds.size() > 0){
                    
                    List<AffiliatedHospital__c> AHU = [select id, appPostingDate__c //, appDeletedDate__c
                                                       from AffiliatedHospital__c 
                                                       where Id =:AHUIds 
                                                       order by Id];
                    integer i=0;
                    integer j=0;
                    
                    for ( ; i < UAHIdIndex.size() ; i ++) {
                        
                        for ( ; j < AHU.size() && UAHIdIndex[i].Id >= AHU[j].id ; ){
                            
                            if (UAHIdIndex[i].Id == AHU[j].id){
                                
                                AffiliatedHospitalPatchDate AH = PatchPostingDate[UAHIdIndex[i].Idx];
                                
                                AHU[j].appPostingDate__c = AH.theDate;
                                
                                j++;
                                
                            } else
                                j ++;
                        }
                        
                    }
                    
                    update AHU;
                    
                    for (AffiliatedHospital__c h:AHU){
                        Rst.add( new AffiliatedHospitalPatchStatus( h.Id, 'Posting Date updated to:' + string.valueof(h.appPostingDate__c)));
                        
                    }
                    
                }
                return Rst;
                
            } catch(Exception e) {
                Database.rollBack(sp);
                return null;
            } 
            
        }
        else if (PatchSortOrder == null && PatchPostingDate != null && PatchDeletedDate == null)
        {
            return updateAffiliatedHospitalDate(PatchPostingDate,'PostingDate');
        }
        else if (PatchSortOrder == null && PatchPostingDate == null && PatchDeletedDate != null){
            return updateAffiliatedHospitalDate(PatchDeletedDate,'DeletedDate' );
        }
        
        
        return null;
    }
    
    
    
    static List<AffiliatedHospitalPatchStatus> updateAffiliatedHospitalDate( List<AffiliatedHospitalPatchDate> PD, string field){
        
        if (PD.size() > 0 ){
            
            SavePoint sp = Database.setSavepoint();
            try {
                
                List<AffiliatedHospitalPatchStatus> Rst = new List<AffiliatedHospitalPatchStatus>();
                
                List<wb_utility_quicksort.IdIndex> UAHIdIndex = new  List<wb_utility_quicksort.IdIndex>();
                Id aId;
                
                for ( integer i = 0; i < PD.size(); i++){
                    aId = Id.valueOf( PD[i].Id);
                    UAHIdIndex.add( new wb_utility_quicksort.IdIndex(aId,i));
                }
                
                wb_utility_quicksort QS = new wb_utility_quicksort();
                QS.sortList = UAHIdIndex;
                QS.sortcustomObjList();
                
                List<Id> AHUIds = new List<Id>();
                
                for( wb_utility_quicksort.IdIndex i:UAHIdIndex){
                    if (i.Id != null){
                        AHUIds.add(i.Id);
                    }
                }
                
                if ( AHUIds.size() > 0){
                    
                    List<AffiliatedHospital__c> AHU = [select id, appPostingDate__c, appDeletedDate__c
                                                       from AffiliatedHospital__c 
                                                       where Id =:AHUIds 
                                                       order by Id];
                    integer i=0;
                    integer j=0;
                    
                    for ( ; i < UAHIdIndex.size() ; i ++) {
                        
                        
                        for ( ; j < AHU.size() && UAHIdIndex[i].Id >= AHU[j].id ; ){
                            
                            
                            if (UAHIdIndex[i].Id == AHU[j].id){
                                
                                AffiliatedHospitalPatchDate AH = PD[UAHIdIndex[i].Idx];
                                if ( field =='PostingDate')
                                    AHU[j].appPostingDate__c = AH.theDate;
                                else if ( field =='DeletedDate')
                                    AHU[j].appDeletedDate__c = AH.theDate;
                                
                                j++;
                                
                            } else
                                j ++;
                        }
                        
                    }
                    
                    update AHU;
                    
                    for (AffiliatedHospital__c h:AHU){
                        if ( field =='PostingDate')
                            Rst.add( new AffiliatedHospitalPatchStatus( h.Id, 'Posting Date updated to:' + string.valueof(h.appPostingDate__c)));
                        else if ( field =='DeletedDate')
                            Rst.add( new AffiliatedHospitalPatchStatus( h.Id, 'Deleted Date updated to:' + string.valueof(h.appDeletedDate__c)));
                    }
                    
                    return Rst;
                }
                
            } catch(Exception e) {
                Database.rollBack(sp);
                return null;
            } 
            
        }
        
        return null;
    }
    
}