unpackaged/objects/BL__c.object
<CustomObject>
    <fields>
        <fullName>ShozokuArea__c</fullName>
        <label>所属地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KeiyakuArea__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>杭州</fullName>
                </value>
                <value>
                    <fullName>平湖</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>山東省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ハイフォン</fullName>
                </value>
                <value>
                    <fullName>ダナン</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>セブ</fullName>
                </value>
                <value>
                    <fullName>クアラルンプール</fullName>
                </value>
                <value>
                    <fullName>ペナン</fullName>
                </value>
                <value>
                    <fullName>ジョホールバル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BL</label>
    <nameField>
        <displayFormat>BL{000000}</displayFormat>
        <label>BL番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_BLs_List.cls
public class wb_BLs_List {
    ApexPages.StandardController stdController;
    ApexPages.StandardSetController Controller;
    public List<BL__c> BLs {get;set;}
    
    public boolean openPopup {get;set;} // To open  window in Java
    public PageReference myTargetUrl {get;set;}
    public List<BLRow> BLList {get;set;}
    
    public class BLRow {
        public Boolean isSelected { get; set; }
        public BL__c theBL { get; set; }
        public BLRow( BL__c bl) {
            theBL = bl;
            isSelected = false;
        }
    }
    
    public SelectOption[] ShozokuAreaOption {get;set;}
    
    public string selectedShozokuAreaOption {get;set;}
    
    public wb_BLs_List(ApexPages.StandardController stdController){
        this.stdController = stdController;
        ShozokuAreaOption = getShozokuAreaOption();
    }
    
    public wb_BLs_List(ApexPages.StandardSetController stdSetController) {
        // if you wish, do something with stdSetController.getSelected()
        this.Controller = stdSetController;
        ShozokuAreaOption = getShozokuAreaOption();
        openPopup = false;
    }
    
    public SelectOption[] getShozokuAreaOption() {  
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','--None--'));  
        
        for (AggregateResult l : [ SELECT ShozokuArea__c, count(id) 
                                  FROM BL__c
                                  where ShozokuArea__c <> null
                                  group by ShozokuArea__c	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('ShozokuArea__c')), String.valueOf(l.get('ShozokuArea__c')) ));  
                                  }        
        
        return opt;  
    } 
    
    public void getBLs(){
        BLList = new List<BLRow>();
        for(BL__c bl:[select id, name from BL__c where ShozokuArea__c=:selectedShozokuAreaOption  ]){
            BLList.add( new BLRow(bl) );
        }
    }
    
    public void BLsList(){
       // PageReference acctPage = Page.wb_BLs_List_Export;
        // PageReference acctPage = new  Page.wb_BLs_List_Export;
       // ApexPages.StandardSetcontroller ctl = new ApexPages.StandardSetcontroller(BLs);
       //   wb_BLs_List_Export BLsExport = new wb_BLs_List_Export(ctl);
        //BLsExport.setRedirect(true);
        //acctPage = BLsExport;
      //  return acctPage;
        Id[] items;
        items = new List<Id>();
        for ( BLRow b:BLList){
            if (b.isSelected==true){
                items.add(b.theBL.id);
            }
        }
        PageReference pr = new PageReference('/apex/wb_BLs_List_Export');
        pr.getParameters().put('items', String.join(items, ','));
        // pr.getParameters().put('key','value');
       // pr.setRedirect(true); // If you want a redirect. Do not set anything if you want a forward.
       openPopup = true;
        myTargetUrl = pr;

    }
    
}