unpackaged/objects/BL__c.object
<CustomObject>
    <fields>
        <fullName>BLNaimuTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BL内務担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>BL</relationshipLabel>
        <relationshipName>BL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BlEigyoTanto9__c</fullName>
        <label>BL営業担当者9</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BlEigyoTanto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BL営業担当</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shimei__c.StaffStatus__c</field>
                <operation>equals</operation>
                <value>在職者</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>BL (BL営業担当)</relationshipLabel>
        <relationshipName>BlEigyoTanto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BranchOfInsurance__c</fullName>
        <label>保険種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>財産保険</fullName>
                </value>
                <value>
                    <fullName>財産一切保険</fullName>
                </value>
                <value>
                    <fullName>公衆責任保険</fullName>
                </value>
                <value>
                    <fullName>機械保険</fullName>
                </value>
                <value>
                    <fullName>現金保険</fullName>
                </value>
                <value>
                    <fullName>コンピュータ保険</fullName>
                </value>
                <value>
                    <fullName>オフィスパッケージ</fullName>
                </value>
                <value>
                    <fullName>団体傷害/医療保険</fullName>
                </value>
                <value>
                    <fullName>雇主責任保険</fullName>
                </value>
                <value>
                    <fullName>雇主工傷</fullName>
                </value>
                <value>
                    <fullName>PL保険</fullName>
                </value>
                <value>
                    <fullName>職業責任</fullName>
                </value>
                <value>
                    <fullName>店舗賠償責任</fullName>
                </value>
                <value>
                    <fullName>総合賠償責任保険</fullName>
                </value>
                <value>
                    <fullName>物流</fullName>
                </value>
                <value>
                    <fullName>運送賠償</fullName>
                </value>
                <value>
                    <fullName>ゴルファー</fullName>
                </value>
                <value>
                    <fullName>住宅総合</fullName>
                </value>
                <value>
                    <fullName>利益保険</fullName>
                </value>
                <value>
                    <fullName>建設工事保険</fullName>
                </value>
                <value>
                    <fullName>組立工事保険</fullName>
                </value>
                <value>
                    <fullName>逆OTA</fullName>
                </value>
                <value>
                    <fullName>個人意外傷害</fullName>
                </value>
                <value>
                    <fullName>食品責任保険</fullName>
                </value>
                <value>
                    <fullName>信用保険</fullName>
                </value>
                <value>
                    <fullName>OTA（香港）</fullName>
                </value>
                <value>
                    <fullName>自動車保険(香港)</fullName>
                </value>
                <value>
                    <fullName>操業停止損害保険（香港）</fullName>
                </value>
                <value>
                    <fullName>搭乗者傷害保険（香港）</fullName>
                </value>
                <value>
                    <fullName>バイク保険</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BrokerKeiyakuStartDate__c</fullName>
        <label>Brokerにて契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>保険料通貨</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DPAppoint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DPアポイント</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EigyoTanto__c</fullName>
        <formula>KeiyakuCompanyName__r.EigyoTanto__r.Name</formula>
        <label>営業担当</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InsuranceAmount__c</fullName>
        <label>保険料</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InsuranceCompanyName__c</fullName>
        <label>保険会社名称</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>損保ジャパン（中国）</fullName>
                </value>
                <value>
                    <fullName>三井住友（中国）</fullName>
                </value>
                <value>
                    <fullName>日本興亜（中国）</fullName>
                </value>
                <value>
                    <fullName>東京海上日動（中国）</fullName>
                </value>
                <value>
                    <fullName>あいおい（中国）</fullName>
                </value>
                <value>
                    <fullName>平安</fullName>
                </value>
                <value>
                    <fullName>太平洋</fullName>
                </value>
                <value>
                    <fullName>PICC</fullName>
                </value>
                <value>
                    <fullName>民安（中国）</fullName>
                </value>
                <value>
                    <fullName>華泰財産</fullName>
                </value>
                <value>
                    <fullName>中国人寿財産</fullName>
                </value>
                <value>
                    <fullName>陽光人寿</fullName>
                </value>
                <value>
                    <fullName>平安養老</fullName>
                </value>
                <value>
                    <fullName>美亜（AIG）</fullName>
                </value>
                <value>
                    <fullName>LIBERTY（香港）</fullName>
                </value>
                <value>
                    <fullName>AIA（香港）</fullName>
                </value>
                <value>
                    <fullName>AIU（香港）</fullName>
                </value>
                <value>
                    <fullName>AXA（香港）</fullName>
                </value>
                <value>
                    <fullName>BlueCross（香港）</fullName>
                </value>
                <value>
                    <fullName>民安（香港）</fullName>
                </value>
                <value>
                    <fullName>三井住友（香港）</fullName>
                </value>
                <value>
                    <fullName>日本興亜（香港）</fullName>
                </value>
                <value>
                    <fullName>PICC（香港）</fullName>
                </value>
                <value>
                    <fullName>損保ジャパン（香港）</fullName>
                </value>
                <value>
                    <fullName>東京海上日動（香港）</fullName>
                </value>
                <value>
                    <fullName>Zurich（香港）</fullName>
                </value>
                <value>
                    <fullName>AIG（香港）</fullName>
                </value>
                <value>
                    <fullName>SJNK（香港）</fullName>
                </value>
                <value>
                    <fullName>UIC</fullName>
                </value>
                <value>
                    <fullName>MALAYAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsuranceManki__c</fullName>
        <inlineHelpText>OPEN POLICYの場合
満期日があるものは、
満期日を入力し、
満期日がないものは、
空欄にしてください。</inlineHelpText>
        <label>保険満期（24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InsuranceShikiMonth__c</fullName>
        <formula>TEXT( MONTH( InsuranceShiki__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保険始期月</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InsuranceShiki__c</fullName>
        <label>保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>保険種目</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約者（被保険者）</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BL(契約者（被保険者）)</relationshipLabel>
        <relationshipName>BL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Agency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>華北</fullName>
                </value>
                <value>
                    <fullName>華中</fullName>
                </value>
                <value>
                    <fullName>江蘇</fullName>
                </value>
                <value>
                    <fullName>華南</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>クアラルンプール</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeiyakuCompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BL (契約会社名称)</relationshipLabel>
        <relationshipName>BL1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>備考</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OpenPolicy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open Policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonalKeiyakuInsurant__c</fullName>
        <label>個人契約（被保険者）</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>BL</label>
    <nameField>
        <displayFormat>BL{000000}</displayFormat>
        <label>BL番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>子サービス</relationshipLabel>
        <relationshipName>ChildService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceClassification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員</fullName>
                </value>
                <value>
                    <fullName>健診</fullName>
                </value>
                <value>
                    <fullName>車保</fullName>
                </value>
                <value>
                    <fullName>搭乗</fullName>
                </value>
                <value>
                    <fullName>強制</fullName>
                </value>
                <value>
                    <fullName>任意</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>現地医療</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceCompany__c</fullName>
        <label>サービス会社</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>サービス</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_BL.cls
public class wb_BL {
    ApexPages.StandardController stdController;
    public BL__c BL {get;set;}
    public List<wb_Service__c> bl_service {get;set;}
    public List<wb_Service__c> bl_serviceContent {get;set;}
    
    
    public wb_bl_Insurance theInsurance {get;set;}

    
    
    Public SelectOption[] BranchOfInsuranceyOptions {get;set;}
    
    public wb_BL(ApexPages.StandardController stdController){
        this.stdController = stdController;
        BL = (BL__c) stdController.getRecord();
        if ( BL.id == null) {
            bl_service = new List<wb_Service__c>();
            bl_service = [select id, Service__c from wb_Service__c where ServiceCompany__c = 'ALL' 
                          and ParentService__c = null and ServiceClassification__c ='BL' ];
            bl_serviceContent = new List<wb_Service__c>();
            bl_serviceContent = [select id, Service__c, ParentService__c from wb_Service__c where ServiceCompany__c = 'ALL' 
                                 and ParentService__c <> null and ServiceClassification__c ='BL' ];
        } else {
            BL = [SELECT BLNaimuTanto__c, BlEigyoTanto__c, BlEigyoTanto9__c, Name, BrokerKeiyakuStartDate__c, DPAppoint__c, OpenPolicy__c, Id, 
                  InsuranceCompanyName__c, InsuranceShiki__c, InsuranceShikiMonth__c, InsuranceAmount__c, Currency__c, InsuranceManki__c, Insurance__c, 
                  BranchOfInsurance__c, PersonalKeiyakuInsurant__c, Note__c, EigyoTanto__c, KeiyakuCompanyName__c, KeiyakuArea__c, Agency__c, 
                  KeiyakuShubetsu__c, Insurant__c, ShozokuArea__c, CommissionAmount__c, CommissionRate__c, CommissionCurrency__c, Branch__c, 
                  TransferDate__c, CommodityName__c, InsuranceContent__c, PayRule__c, CancelDate__c, CancelReason__c, KeijoMonthBl__c, ShokenNo__c, 
                  NoticeRule__c, NoticeTanto__c, NoticeTantoMail__c, NoticeMonth__c, TransferBeforeInsuranceCompany__c
                  FROM BL__c where id =:BL.id];
            
        }
        
        BranchOfInsuranceyOptions = getBranchOfInsuranceyOptions();

        fetchInsuranceContent();

        
        
    }
    
    public SelectOption[] getBranchOfInsuranceyOptions() {  
        List<SelectOption>  opt = new  List<SelectOption>();

        opt.add(new SelectOption('','--None--'));  
        for (AggregateResult l : [ select  Service__c, count(id) 
                                  from wb_Service__c where ServiceCompany__c = 'ALL' 
                                  and ParentService__c = null and ServiceClassification__c ='BL'    
                                  group by Service__c	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('Service__c')), String.valueOf(l.get('Service__c')) ));  
                                  }        

        return opt;  
    }  
    
    public void fetchInsuranceContent(){
        system.debug(' BL.Insurance__c:' +  BL.Insurance__c + ' ' + BL.InsuranceContent__c);
        if (BL.InsuranceContent__c == null )
            theInsurance = new wb_bl_Insurance( BL.Insurance__c, bl_service, bl_serviceContent );
        else {
		//	system.debug(' BL.Insurance__c:' +  BL.Insurance__c);
            if ( BL.Insurance__c !=''){
                theInsurance = new wb_bl_Insurance(  BL.Insurance__c,BL.InsuranceContent__c );
                theInsurance.InsuranceItem( BL.Insurance__c,
                                           [select id, Service__c from wb_Service__c where ServiceCompany__c = 'ALL' 
                                            and ParentService__c = null and ServiceClassification__c ='BL' ],
                                           [select id, Service__c, ParentService__c from wb_Service__c where ServiceCompany__c = 'ALL' 
                                            and ParentService__c <> null and ServiceClassification__c ='BL' ] );
            }
            
        }
    }
    
    public void FieldValidation(){
        if (BL.InsuranceShiki__c== null)
            BL.InsuranceShiki__c.addError('エラー: 値を入力してください'); 
        if (BL.Currency__c== null)
            BL.Currency__c.addError('エラー: 値を入力してください'); 
        if (BL.CommissionRate__c== null)
            BL.CommissionRate__c.addError('エラー: 値を入力してください'); 
        if (BL.InsuranceAmount__c== null)
            BL.InsuranceAmount__c.addError('エラー: 値を入力してください'); 
        if (BL.CommissionCurrency__c== null)
            BL.CommissionCurrency__c.addError('エラー: 値を入力してください'); 
     
    }
    
    public PageReference PackInsuranceContentSave(){
        string InsuranceContent;
        for ( wb_bl_InsuranceContent ic:theInsurance.theContent ){
            if (InsuranceContent!=null) 
                InsuranceContent +=';' ;
            else  InsuranceContent ='';
            string theValue = ic.Value;
            theValue = theValue.replace('(', ' ').replace(')', ' ');
            theValue = theValue.replace(';', ' ');
            InsuranceContent += ic.ItemName +'(' + theValue +')' ;
            //system.debug('theValue:'+ theValue);
        }
       // system.debug('InsuranceContent:'+ InsuranceContent);
       // BL.Insurant__c=selectedInsurance;
        BL.InsuranceContent__c = InsuranceContent;
        
        if (BL.id == null) {
            insert BL;
            String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
            return new PageReference(sfdcBaseURL+'/apex/wb_BL?Id=' + BL.id);
            
            
        }
        else {
            system.debug('BranchOfInsurance__c' + BL.BranchOfInsurance__c);
			this.stdController.Save();            
            update BL;
            
            
            return null;
            
        }
    }
    
}