unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>南京</fullName>
                </value>
                <value>
                    <fullName>合肥</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShozokuArea__c</fullName>
        <formula>TEXT(KeiyakuCompanyName__r.ShozokuArea__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（会社情報）所属地区</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>商品</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>メディック</fullName>
                </value>
                <value>
                    <fullName>Prime Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>FamilyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShozokuArea__c</fullName>
        <label>所属地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Jurisdiction__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>内モンゴル</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>塘沽</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>山東省</fullName>
                </value>
                <value>
                    <fullName>煙台</fullName>
                </value>
                <value>
                    <fullName>黒龍江省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>長春</fullName>
                </value>
                <value>
                    <fullName>瀋陽</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>遼寧省</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>寧夏</fullName>
                </value>
                <value>
                    <fullName>新疆</fullName>
                </value>
                <value>
                    <fullName>西安</fullName>
                </value>
                <value>
                    <fullName>雲南省</fullName>
                </value>
                <value>
                    <fullName>貴州</fullName>
                </value>
                <value>
                    <fullName>平湖</fullName>
                </value>
                <value>
                    <fullName>鄭州</fullName>
                </value>
                <value>
                    <fullName>杭州</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>寧波</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>成都</fullName>
                </value>
                <value>
                    <fullName>重慶</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>商品</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>メディック</fullName>
                </value>
                <value>
                    <fullName>チャイナボウル</fullName>
                </value>
                <value>
                    <fullName>Prime Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShozokuArea__c</fullName>
        <label>所属地区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Jurisdiction__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>内モンゴル</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>塘沽</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>山東省</fullName>
                </value>
                <value>
                    <fullName>煙台</fullName>
                </value>
                <value>
                    <fullName>黒龍江省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>長春</fullName>
                </value>
                <value>
                    <fullName>瀋陽</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>遼寧省</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>寧夏</fullName>
                </value>
                <value>
                    <fullName>新疆</fullName>
                </value>
                <value>
                    <fullName>西安</fullName>
                </value>
                <value>
                    <fullName>雲南省</fullName>
                </value>
                <value>
                    <fullName>貴州</fullName>
                </value>
                <value>
                    <fullName>平湖</fullName>
                </value>
                <value>
                    <fullName>鄭州</fullName>
                </value>
                <value>
                    <fullName>杭州</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>寧波</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>成都</fullName>
                </value>
                <value>
                    <fullName>重慶</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Summary_of_members__c.object
<CustomObject>
    <description>To save the data by generating the excel from Summary of Members button in Company object.</description>
    <fields>
        <fullName>Area__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Summary of Members</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Summary of member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>Aggregate_Sheet_Affiliation</fullName>
        <active>true</active>
        <label>Aggregate Sheet(Affiliation)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Aggregate_Sheet_Contract</fullName>
        <active>true</active>
        <label>Aggregate Sheet(Contract)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/MDMemberReportUpdateFamilyInfoBatch.cls
global class MDMemberReportUpdateFamilyInfoBatch implements Database.Batchable<sObject>, Database.Stateful{

    public DataModel dm {get;set;}
    public List<SummaryRec> LSummary {set;get;}
    public Map<String, Integer> MArea {set;get;}
    public List<SummaryRec> LSummary2 {set;get;}
    public Map<String, Integer> MArea2 {set;get;}
    public Map<string,integer> MCode = new Map<string,integer>();  
    public Summary_of_members__c summaryDataAffiliation = new Summary_of_members__c();
    public Summary_of_members__c summaryDataContract = new Summary_of_members__c();
    public List<Summary_of_members__c> summaryAffiliationList = new List<Summary_of_members__c>();   
    public List<Summary_of_members__c> summaryContractList = new List<Summary_of_members__c>();  
    public Map<String,String> recordTypeNameIdMap = new Map<String,String>();
    public List<Summary_of_members__c> summaryDataList = new List<Summary_of_members__c>();
    
    global MDMemberReportUpdateFamilyInfoBatch (){
        summaryDataList = [select id,Area__c,Contract__c,recordtype.id from Summary_of_members__c];
    
        List<RecordType> recordTypeList =  [select id,developerName from recordType where SobjectType = 'Summary_of_members__c'];
        recordTypeNameIdMap = new Map<String,String>();
        for(RecordType recordType:recordTypeList){
            recordTypeNameIdMap.put(recordType.developerName,recordType.id);  
        }  
        system.debug(recordTypeNameIdMap);    
    
        Schema.DescribeFieldResult fieldResult = MemberInfo__c.ShozokuArea__c.getDescribe();
        List<Schema.PicklistEntry> LPicklistValue = fieldResult.getPicklistValues();
        
        LSummary = new List<SummaryRec>();
        MArea = new Map<String, Integer>();
        for(Schema.PicklistEntry picklist: LPicklistValue){
            LSummary.add(new SummaryRec(picklist.getValue()));
            MArea.put(picklist.getValue(),LSummary.size()-1);
        }
                
        Schema.DescribeFieldResult fieldResult2 = ContractInfo__c.KeiyakuArea__c.getDescribe();
        List<Schema.PicklistEntry> LPicklistValue2 = fieldResult2.getPicklistValues();
        
        LSummary2 = new List<SummaryRec>();
        MArea2 = new Map<String, Integer>();
        for(Schema.PicklistEntry picklist: LPicklistValue2){
            LSummary2.add(new SummaryRec(picklist.getValue()));
            MArea2.put(picklist.getValue(),LSummary2.size()-1);
        }                

    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(
        'SELECT MemberShimei__r.CompanyKeiyakuNo__r.KeiyakuArea__c, ShozokuArea__c FROM FamilyInfo__c where (TaikaiDate__c = null or TaikaiDate__c >= today) and (Commodity__c = \'メディック\' or Commodity__c = \'チャイナボウル\')');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(FamilyInfo__c Fam:(List<FamilyInfo__c>)scope){
                if(MArea.get(Fam.ShozokuArea__c) != null){
                    LSummary[MArea.get(Fam.ShozokuArea__c)].family++;
                }
                
                if(MArea2.get(Fam.MemberShimei__r.CompanyKeiyakuNo__r.KeiyakuArea__c) != null){
                    LSummary2[MArea2.get(Fam.MemberShimei__r.CompanyKeiyakuNo__r.KeiyakuArea__c)].family++;
                }    
        }   
    }

   global void finish(Database.BatchableContext BC){
        List<Summary_of_members__c> summaryDataList = [select id,Area__c,Contract__c,recordtype.id from Summary_of_members__c];
        dm = new DataModel();
        dm.data = new list<DataModel.Model>();       
        DataModel.Model model = new DataModel.Model();            
        model.data = new list<map<string,string>>();
        for(SummaryRec SRec: LSummary){
            map<string,string> rowdata = new map<string,string>();
            rowdata.put(System.Label.AffiliationArea,SRec.area);
            rowdata.put(System.Label.EntrainedFamily,String.valueof(SRec.family));
            model.data.add(rowdata);
        }
          
          if(model.data != null){        
              for(Map<String,String> rowdataList:model.data){ 
                   if(summaryDataList != null){   
                       summaryDataAffiliation = new Summary_of_members__c();  
                       for(Summary_of_members__c m:summaryDataList){
                           if(rowdataList.get(System.Label.AffiliationArea) == m.Area__c && m.recordtype.id == recordTypeNameIdMap.get('Aggregate_Sheet_Affiliation')){
                               summaryDataAffiliation.id = m.id;
                               summaryDataAffiliation.Family__c = rowdataList.get(System.Label.EntrainedFamily);
                               summaryDataAffiliation.RecordTypeId = recordTypeNameIdMap.get('Aggregate_Sheet_Affiliation');
                               summaryAffiliationList.add(summaryDataAffiliation);                                   
                           }
                       }  
                   }         
              }   
          }
        dm.data.add(model);
              
        model = new DataModel.Model();
        model.data = new list<map<string,string>>();
        for(SummaryRec SRec: LSummary2){
            map<string,string> rowdata = new map<string,string>();
            rowdata.put(System.Label.Contract,SRec.area);
            rowdata.put(System.Label.EntrainedFamily,String.valueof(SRec.family));
            model.data.add(rowdata);
        }
        
        system.debug(model);
        dm.data.add(model);
        
           if(model.data != null){
               for(Map<String,String> rowdataList:model.data){ 
                    if(summaryDataList!= null){  
                       summaryDataContract = new Summary_of_members__c();     
                       for(Summary_of_members__c m:summaryDataList){
                           if(rowdataList.get(System.Label.Contract) == m.Contract__c && m.recordtype.id == recordTypeNameIdMap.get('Aggregate_Sheet_Contract')){ 
                               summaryDataContract.id = m.id;
                               summaryDataContract.Family__c = rowdataList.get(System.Label.EntrainedFamily);  
                               summaryDataContract.RecordTypeId = recordTypeNameIdMap.get('Aggregate_Sheet_Contract');
                               summaryContractList.add(summaryDataContract);                               
                           }
                       }                        
                    }       
              }     
          }     
         
        /*                    
        LSummary = null;
        MArea = null;
        LSummary2 = null;
        MArea2 = null;   
        */     
        
        //update date in 'Summary_of_members__c' object's family           
        if(summaryContractList !=null){
            update summaryContractList;   
        }
        if(summaryAffiliationList != null){
            update summaryAffiliationList;      
        }  
   }
   
    public class SummaryRec{
        public string area {set;get;}
        public Integer family {set;get;}
        public Integer company {set;get;}
        
        public SummaryRec(String inArea){
            area = inArea;
            family = 0;
            company = 0;     
        }
    }    
}