unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuArea__c</fullName>
        <label>契約地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>南京</fullName>
                </value>
                <value>
                    <fullName>合肥</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>香港</fullName>
                </value>
                <value>
                    <fullName>ハノイ</fullName>
                </value>
                <value>
                    <fullName>ホーチミン</fullName>
                </value>
                <value>
                    <fullName>ニューデリー</fullName>
                </value>
                <value>
                    <fullName>チェンナイ</fullName>
                </value>
                <value>
                    <fullName>ジャカルタ</fullName>
                </value>
                <value>
                    <fullName>マニラ</fullName>
                </value>
                <value>
                    <fullName>プノンペン</fullName>
                </value>
                <value>
                    <fullName>シンガポール</fullName>
                </value>
                <value>
                    <fullName>ヤンゴン</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TaikaiDate__c</fullName>
        <label>退会日付</label>
        <type>Date</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/RenewalNoticeBatchProcessController.cls
public class RenewalNoticeBatchProcessController
{ 
    public boolean isEnglish {get; set;}  
    public ContractInfo__c pageData {set;get;}
    public ContractInfo__c pageData2 {set;get;}
    public List<ContractInfo__c> searchResults {set;get;}
    private List<SelectOption> m_options {set;get;}
    public string m_selTemplate {set;get;}
    
    public RenewalNoticeBatchProcessController(ApexPages.StandardController con){          
          isEnglish = 'en_US'.equals(UserInfo.getLanguage()); //check profile language      
          pageData = new ContractInfo__c();
          pageData2 = new ContractInfo__c();
          m_options = new List<SelectOption>();
          searchResults = new List<ContractInfo__c>(); 
          List<Document> ls =  new List<Document>();
          
            if(isEnglish){
                ls = [select Id, Name from Document where Folder.Name='Renewal Notice Template_ENG'];
            }
            else{
                ls = [select Id, Name from Document where Folder.Name='Renewal Notice Template_JPN'];
            }
            
            for(integer i=0; i<ls.size(); i++){
              m_options.add(new SelectOption(ls[i].Id, ls[i].Name));
              if(m_selTemplate==null) m_selTemplate = ls[i].Id;
            }                                    
      }
        
     public void search(){
       system.debug(pageData.KeiyakuArea__c);
       system.debug(pageData.MankiDate__c);
       system.debug(pageData2.MankiDate__c);
       system.debug(m_selTemplate);
       
       if(pageData.KeiyakuArea__c!=null && pageData.MankiDate__c!=null && pageData2.MankiDate__c!=null && m_selTemplate!=null){
           searchResults = [SELECT id,KeiyakuArea__c,MankiDate__c,TaikaiDate__c FROM ContractInfo__c WHERE KeiyakuArea__c=: pageData.KeiyakuArea__c AND MankiDate__c >=: pageData.MankiDate__c
           AND MankiDate__c <=: pageData2.MankiDate__c AND (TaikaiDate__c = null OR TaikaiDate__c >= Today)
           ];
           
           // show no result message if no result
           if(searchResults.size() == 0 || searchResults.size() == null){            
                   ApexPages.Message myMsg2 = new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.No_Result); 
                   ApexPages.addMessage(myMsg2); 
           }
       }
       else{       
           // check all fields must be filled
               ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.ErrorMessageSearch);  
               ApexPages.addMessage(myMsg);   
       } 
     }

    public PageReference back(){   
        String id = null;
        if(ApexPages.currentPage().getParameters().get('retURL')!=null){
           id = ApexPages.currentPage().getParameters().get('retURL').right(15); //get pervious page id
        }
        String spaceDelimeted = '/a0A?fcf='+id;
        PageReference reference = new PageReference(spaceDelimeted);
        system.debug(spaceDelimeted );
        reference.setRedirect(true);
        return reference;
    }
     
      public string SelectedTemplate { get { return m_selTemplate; } set { m_selTemplate = value; } }
      public List<SelectOption> TemplateOptions { get { return m_options; } }
}