unpackaged/objects/ContractInfo__c.object
<CustomObject>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>契約情報</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>契約番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>MemberKubunB__c</fullName>
        <formula>CASE(  Commodity__c  , 
&quot;メディック&quot;, IF ( TaikaiDate__c &lt;= TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;留学生&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;チャイナボウル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;ベトナムメディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;メディフル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;Medi-X&quot;, IF ( TaikaiDate__c &lt;= TODAY() , &quot;Medi-X退会者&quot;, &quot;Medi-X会員&quot;), 
&quot;&quot;)</formula>
        <label>会員区分B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>FamilyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MankiDate__c</fullName>
        <label>満期日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MemberKubunB__c</fullName>
        <formula>CASE( Commodity__c ,
&quot;メディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;留学生&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;チャイナボウル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;ベトナムメディック&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;メディフル&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;退会者&quot;, &quot;会員&quot;), 
&quot;Medi-X&quot;, IF ( TaikaiDate__c  &lt;=  TODAY() , &quot;Medi-X退会者&quot;, &quot;Medi-X会員&quot;),
&quot;&quot;)</formula>
        <label>会員区分B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>If(ISBLANK(Parent__c),
Member__r.f_Classification__c,
If(ISBLANK(Parent__r.Member__r.f_Classification__c),
&apos;&apos;,
Parent__r.Member__r.f_Classification__c + &apos;家族&apos;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>if(IsBlank(r_EffectiveUntil__c),&apos;&apos;,if(r_EffectiveUntil__c&gt;= TODAY(),&apos;会員&apos;,&apos;退会者&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>f_MemberNo__c</fullName>
        <formula>MembershipDetail__r.MemberNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>r_EffectiveUntil__c</fullName>
        <label>有効終了日</label>
        <summarizedField>wb_MemberHistory__c.EffectiveUntil__c</summarizedField>
        <summaryForeignKey>wb_MemberHistory__c.member__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MemberHistory__c.object
<CustomObject>
    <description>WellBe Membership History</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>member__c</fullName>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MemberHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員履歴</label>
    <nameField>
        <label>会員履歴番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_soap_log__c.object
<CustomObject>
    <fields>
        <fullName>LastAcessDate__c</fullName>
        <label>LastAcessDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LogIn__c</fullName>
        <label>LogIn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberInfo__c</fullName>
        <label>MemberInfo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>MemberNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>SOAPログ</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SOAPログ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_MobileAppLogin.cls
@RestResource(urlMapping='/MobileAppLogin/*')
global with sharing class wb_soap_MobileAppLogin {
    
    global class MemberLoginInfo{
       	global string Id; 
        global string MemberNo;   
        global string MemberClassification;  
        global string lastmodifieddate; 
        public MemberLoginInfo(){}
        
        public MemberLoginInfo( id theId, string theMemberNo, string Classification, datetime dt){
   			Id = theId; 
            MemberNo= theMemberNo;
            String formatedDt = dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            lastmodifieddate = formatedDt;
            MemberClassification = Classification;

        }
    }
        
    @HttpGet
    global static MemberLoginInfo getMemberLoginInfo() {
        
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String req = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        system.debug('req:'+req);
        if ( req.indexOf('=') > 1){
            string reqType = req.left( req.indexOf('='));
            string reqInfo = req.right(req.length() - req.indexOf('=') - 1);
            
            if ( reqType=='MemberNo') {
                
                return GetMemberLoginInfobyMemberNo(reqInfo);
                
            } else
                return new MemberLoginInfo();
            
 
        } else {
            return new MemberLoginInfo();
        }
        
    }
    
    public static MemberLoginInfo GetMemberLoginInfobyMemberNo( string theMemberNo ){
        
        if ( [select Id from wb_soap_log__c 
              where Type__c ='1ST' and MemberNo__c=:theMemberNo].size() == 0 ){
            insert new wb_soap_log__c(LastAcessDate__c= System.today(),MemberNo__c=theMemberNo,LogIn__c=1, Type__c ='1ST' );
        } else {
            wb_soap_log__c log = [select Id, LogIn__c ,LastAcessDate__c from wb_soap_log__c 
                                  where  Type__c ='1ST' and MemberNo__c=:theMemberNo ];
            if ( log.LastAcessDate__c == System.today() ) {
                if (log.LogIn__c != null) {
                    log.LogIn__c = log.LogIn__c + 1;
                   // log.LogIn__c = integer.valueOf('x');
                }
                else
                    log.LogIn__c = 1;
            }
            else {
                log.LastAcessDate__c = System.today();
                log.LogIn__c = 1;
                log.MemberInfo__c = 0;
            }
            update log; 
        }
        

        if( [select id from MemberInfo__c where MemberNo__c =:theMemberNo].size() > 0 ) {
                 
                 MemberInfo__c cr= [select id, MemberNo__c, CompanyKeiyakuNo__r.MankiDate__c, MemberKubunB__c,
                                    lastmodifieddate 
                                    from MemberInfo__c where MemberNo__c =:theMemberNo];
                  return new MemberLoginInfo(cr.id, cr.MemberNo__c, cr.MemberKubunB__c,
                                             cr.lastmodifieddate ) ;
             }
        else if ( [select id from FamilyInfo__c where MemberNo__c =:theMemberNo].size() > 0  ){
            FamilyInfo__c cfr = [select id, MemberShimei__r.CompanyKeiyakuNo__r.MankiDate__c,
                                 MemberNo__c, MemberKubunB__c,
                                 lastmodifieddate from FamilyInfo__c where MemberNo__c =:theMemberNo];
             return new MemberLoginInfo(cfr.id, cfr.MemberNo__c, cfr.MemberKubunB__c, 
                                        cfr.lastmodifieddate ) ;
        } 
        else if ([select id from wb_Member__c where f_MemberNo__c =:theMemberNo].size() > 0 ){
           // SELECT f_Classification__c,f_MemberNo__c,Individual__c,Name,r_EffectiveUntil__c FROM wb_Member__c
         /*   wb_MemberHistory__c r = [select member__r.Individual__c, MemberNo__c, MembershipEndDate__c, lastmodifieddate
                                     from wb_MemberHistory__c 
                                     where  MemberNo__c =: theMemberNo 
                                     and ( CancellationDate__c = null or CancellationDate__c > today )
                                     order by MembershipEndDate__c desc limit 1];*/
            wb_Member__c r = [SELECT Id, f_Classification__c,f_MemberNo__c,Individual__c,Name,r_EffectiveUntil__c, 
                              lastmodifieddate, Individual__r.lastmodifieddate
                              FROM wb_Member__c where f_MemberNo__c =:theMemberNo];
            return new MemberLoginInfo(r.Id, r.f_MemberNo__c, r.f_Classification__c, r.lastmodifieddate ) ;
        } else
            return new MemberLoginInfo();
    }
    

}