unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuNo__c</fullName>
        <label>契約№</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>KeiyakuNo__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>契約№</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/OTAHistory__c.object
<CustomObject>
    <fields>
        <fullName>MemberFamilyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員（家族）名称</label>
        <referenceTo>FamilyInfo__c</referenceTo>
        <relationshipLabel>保険履歴</relationshipLabel>
        <relationshipName>R00N10000000aHCpEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員名称</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>保険履歴</relationshipLabel>
        <relationshipName>R00N10000000aHCfEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <formula>IF ( MemberName__c  &lt;&gt; &quot;&quot;,  MemberName__r.MemberNo__c ,  MemberFamilyName__r.MemberNo__c )</formula>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_FamilyNo__c</fullName>
        <label>Temp FamilyNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_MemberNo__c</fullName>
        <label>Temp_MemberNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>保険履歴</label>
    <nameField>
        <displayFormat>I{0000000000}</displayFormat>
        <label>保険履歴番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/OTAHistoryImportBatch.cls
global class OTAHistoryImportBatch implements Database.Batchable<sObject>, Database.Stateful
{
    global OTAHistoryImportBatch()
    {}
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
		return Database.getQueryLocator('select Id, Temp_MemberNo__c, Temp_FamilyNo__c ' +
			'from OTAHistory__c where MemberName__c=null and MemberFamilyName__c=null');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
	    list<string> lm = new list<string>();
        list<string> lf = new list<string>();
        
        for(sobject s : scope)
        {
        	OTAHistory__c o = (OTAHistory__c)s;

			if(o.Temp_MemberNo__c!=null)
        		lm.add(o.Temp_MemberNo__c.substring(4,10));
       		else if(o.Temp_FamilyNo__c!=null)
       			lf.add(o.Temp_FamilyNo__c.substring(4,10));
        }
            
        map<string, string> mm = new map<string, string>();
        for(MemberInfo__c mi : [select Id, MemberNo__c from MemberInfo__c where KeiyakuNo__c in :lm])
       		mm.put(mi.MemberNo__c.substring(4,11), mi.Id);
               
        map<string, string> mf = new map<string, string>();
        for(FamilyInfo__c fi : [select Id, MemberNo__c from FamilyInfo__c where KeiyakuNo__c in :lf])
       		mf.put(fi.MemberNo__c.substring(4,11), fi.Id);
               		
        for(sobject s : scope)
        {
        	OTAHistory__c o = (OTAHistory__c)s;
        	
			string mkey;
			if(o.Temp_MemberNo__c!=null)
			{
        		mkey = o.Temp_MemberNo__c.substring(4,11);
        		o.MemberName__c = mm.containsKey(mkey) ? mm.get(mkey) : null;
			}
       		else if(o.Temp_FamilyNo__c!=null)
       		{
       			mkey = o.Temp_FamilyNo__c.substring(4,11);
       			o.MemberFamilyName__c = mf.containsKey(mkey) ? mf.get(mkey) : null;
       		}
        }
        
		update scope;
        
    }

    global void finish(Database.BatchableContext BC)
    {
    }
    
 
 
    static testMethod void OTAHistoryImportBatch_Test()
    {
        Test.startTest();
        test1();
        Test.stopTest();
    }
    
    static void Test1()
    {
        OTAHistoryImportBatch bat = new OTAHistoryImportBatch();
        Database.executeBatch(bat);
    }
    
}