unpackaged/objects/FamilyInfo__c.object
<CustomObject>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>会員（家族）情報</relationshipLabel>
        <relationshipName>FamilyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員（家族）情報</label>
    <nameField>
        <label>会員(家族)氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Kenshin__c.object
<CustomObject>
    <fields>
        <fullName>CancelDate__c</fullName>
        <label>キャンセル日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KenshinArea__c</fullName>
        <label>受診地区</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京</fullName>
                </value>
                <value>
                    <fullName>天津</fullName>
                </value>
                <value>
                    <fullName>大連</fullName>
                </value>
                <value>
                    <fullName>青島</fullName>
                </value>
                <value>
                    <fullName>上海</fullName>
                </value>
                <value>
                    <fullName>成都</fullName>
                </value>
                <value>
                    <fullName>武漢</fullName>
                </value>
                <value>
                    <fullName>杭州</fullName>
                </value>
                <value>
                    <fullName>寧波</fullName>
                </value>
                <value>
                    <fullName>蘇州</fullName>
                </value>
                <value>
                    <fullName>無錫</fullName>
                </value>
                <value>
                    <fullName>昆山</fullName>
                </value>
                <value>
                    <fullName>南通</fullName>
                </value>
                <value>
                    <fullName>常州</fullName>
                </value>
                <value>
                    <fullName>常熟</fullName>
                </value>
                <value>
                    <fullName>深セン</fullName>
                </value>
                <value>
                    <fullName>厦門</fullName>
                </value>
                <value>
                    <fullName>東莞</fullName>
                </value>
                <value>
                    <fullName>広州</fullName>
                </value>
                <value>
                    <fullName>中山</fullName>
                </value>
                <value>
                    <fullName>珠海</fullName>
                </value>
                <value>
                    <fullName>Hanoi</fullName>
                </value>
                <value>
                    <fullName>HoChiMinh</fullName>
                </value>
                <value>
                    <fullName>HaiPhong</fullName>
                </value>
                <value>
                    <fullName>DaNang</fullName>
                </value>
                <value>
                    <fullName>Gurgaon</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
                <value>
                    <fullName>Jakarta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KenshinDate__c</fullName>
        <label>受診日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KenshinHospital__c</fullName>
        <label>会場病院名</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KenshinPlan__c</fullName>
        <label>健診プラン</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>101</fullName>
                </value>
                <value>
                    <fullName>102</fullName>
                </value>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>202</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>204</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>207</fullName>
                </value>
                <value>
                    <fullName>222</fullName>
                </value>
                <value>
                    <fullName>223</fullName>
                </value>
                <value>
                    <fullName>224</fullName>
                </value>
                <value>
                    <fullName>301</fullName>
                </value>
                <value>
                    <fullName>302</fullName>
                </value>
                <value>
                    <fullName>303</fullName>
                </value>
                <value>
                    <fullName>304</fullName>
                </value>
                <value>
                    <fullName>3051</fullName>
                </value>
                <value>
                    <fullName>3052</fullName>
                </value>
                <value>
                    <fullName>306</fullName>
                </value>
                <value>
                    <fullName>307</fullName>
                </value>
                <value>
                    <fullName>308</fullName>
                </value>
                <value>
                    <fullName>309</fullName>
                </value>
                <value>
                    <fullName>310</fullName>
                </value>
                <value>
                    <fullName>311</fullName>
                </value>
                <value>
                    <fullName>312</fullName>
                </value>
                <value>
                    <fullName>313</fullName>
                </value>
                <value>
                    <fullName>314</fullName>
                </value>
                <value>
                    <fullName>315</fullName>
                </value>
                <value>
                    <fullName>325</fullName>
                </value>
                <value>
                    <fullName>326</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MemberFamilyShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員（家族）氏名</label>
        <referenceTo>FamilyInfo__c</referenceTo>
        <relationshipLabel>健診</relationshipLabel>
        <relationshipName>R00N10000000uqnLEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <formula>IF ( MemberShimei__c  &lt;&gt; &quot;&quot;, 
MemberShimei__r.MemberNo__c ,  
IF ( MemberFamilyShimei__c  &lt;&gt; &quot;&quot;,  MemberFamilyShimei__r.MemberNo__c , &quot;&quot;) )</formula>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberShimei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員氏名</label>
        <referenceTo>MemberInfo__c</referenceTo>
        <relationshipLabel>健診</relationshipLabel>
        <relationshipName>R00N10000000uqoNEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonalReceiptNo__c</fullName>
        <label>個人受付番号</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptNo__c</fullName>
        <label>受付番号</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状態</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wish_time__c</fullName>
        <label>wish_time</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>健診</label>
    <nameField>
        <displayFormat>K{0000000}</displayFormat>
        <label>健診番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Kenshin_Import__c.object
<CustomObject>
    <fields>
        <fullName>Fail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Import_Status__c</fullName>
        <label>Import Status</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Import_Date__c</fullName>
        <label>Last Import Date</label>
        <type>DateTime</type>
    </fields>
    <label>Kenshin Import</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Kenshin Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/KenshinImportControllerEx.cls
public class KenshinImportControllerEx
{
    public Kenshin_Import__c KenshinImport {get; set;}
    public Attachment Attachment {get; set;}
    public Boolean showUploadMesssage {get; set;}
    private Id batchId;

    public KenshinImportControllerEx(ApexPages.StandardSetController scon)
    { 
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.KenshinImportloadingMessage));
    }
    
    public void init()
    {
        List<Kenshin_Import__c> l = [select Id, Import_Status__c, Fail__c, Last_Import_Date__c
            from Kenshin_Import__c
            order by LastModifiedDate desc];
        
        if(l.size()<=0)
        {
            KenshinImport = new Kenshin_Import__c();
            Attachment = new Attachment();
        }
        else
        {
            KenshinImport = l[0];
            List<Attachment> la = [select Id, Body, Name, ParentId from Attachment 
                where ParentId=:KenshinImport.Id
                order by LastModifiedDate desc];
            if(la.size()<=0)
                Attachment = new Attachment();
            else
                Attachment = la[0];
        }
    }
    
    public PageReference upload()
    {
        showUploadMesssage = true;
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.KenshinImportloadingMessage));
        KenshinImport.Last_Import_Date__c = system.now();
        KenshinImport.Import_Status__c = '';
        upsert(KenshinImport);
        if(Attachment.ParentId==null) Attachment.ParentId = KenshinImport.Id;
        upsert(Attachment);
        
        KenshinImportBatch bat = new KenshinImportBatch(UserInfo.getUserId(), KenshinImport);
        batchId = Database.executeBatch(bat);
        
        String a = [SELECT Id, Status FROM AsyncApexJob where id=:batchId].status;
        if(a!=null){
            if(a == 'Completed'){
                showUploadMesssage = false;
            }
        }
        
        //PageReference page = new PageReference('/apex/KenshinImport?processing=true');
        //page.setRedirect(true);
        return null;
    }
    
    public PageReference runBatch()
    {
        showUploadMesssage = true;
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.KenshinImportloadingMessage));
        KenshinImport.Last_Import_Date__c = system.now();
        KenshinImport.Import_Status__c = '';
        upsert(KenshinImport);
        
        KenshinImportBatch bat = new KenshinImportBatch(UserInfo.getUserId(), KenshinImport);
        batchId = Database.executeBatch(bat);

        
        String a = [SELECT Id, Status FROM AsyncApexJob where id=:batchId].status;
        if(a!=null){
            if(a == 'Completed'){
                showUploadMesssage = false;
            }
        }
         
        //PageReference page = new PageReference('/apex/KenshinImport?processing=true');
        //page.setRedirect(true);
        return null;
    }
    
    /*public PageReference run()
    {
        list<Kenshin_Import__c> kis = [select Id, status__c, wb_member_cd__c, order_num__c, 
                                        order_detail_num__c, wish_date__c, wish_time__c, cancel_datetime__c,
                                        item_cd__c, jurisdiction_division_name__c, name__c
                                        from Kenshin_Import__c];
        KenshinImportControllerEx.Execute(kis);
        return null;
    }

    public static void Execute(List<Kenshin_Import__c> ls)
    {
        list<Kenshin_Import__c> kis = new list<Kenshin_Import__c>();
        set<string> ordernums = new set<string>();
        set<string> orderdetailnums = new set<string>();
        for(Kenshin_Import__c ki : ls)
        {
            kis.add(new Kenshin_Import__c(Id=ki.Id));
            ordernums.add(ki.order_num__c);
            orderdetailnums.add(ki.order_detail_num__c);
        }
        
        map<string, Kenshin__c> ks = new map<string, Kenshin__c>();
        for(Kenshin__c k : [select Id, ReceiptNo__c, PersonalReceiptNo__c from Kenshin__c
                              where ReceiptNo__c in :ordernums
                              and PersonalReceiptNo__c in :orderdetailnums])
        {
            ks.put(k.ReceiptNo__c + ':' + k.PersonalReceiptNo__c, k);
        }
        
        List<Kenshin__c> lk = new List<Kenshin__c>();
        for(Kenshin_Import__c ki : ls)
        {
            string memberNo = ki.wb_member_cd__c;
            boolean isMember = (memberno.endsWith('0'));
            string receiptNo = ki.order_num__c;
            string personalReceiptNo = ki.order_detail_num__c;
            string status = ki.status__c;
            date kenshinDate = ki.wish_date__c;
            string wishTime = ki.wish_time__c;
            date cancelDate = null;
            if(ki.cancel_datetime__c!=null)
                cancelDate = date.valueOf(ki.cancel_datetime__c.replace('/','-'));
            string kenshinPlan = '';
            if(ki.item_cd__c!=null) kenshinPlan = ki.item_cd__c.replace(',',';');
            string kenshinArea = ki.jurisdiction_division_name__c;
            string kenshinHospital = ki.name__c;
            
            MemberInfo__c mi = null;
            FamilyInfo__c fi = null;
            if(isMember) 
                mi = new MemberInfo__c(MemberNo__c=memberNo);
            else
                fi = new FamilyInfo__c(MemberNo__c=memberNo);
            
            string key = ki.order_num__c + ':' + ki.order_detail_num__c;
            Kenshin__c k;
            if(ks.containsKey(key))
                k = ks.get(key);
            else
            {
                k = new Kenshin__c();
                k.ReceiptNo__c = receiptNo;
                k.PersonalReceiptNo__c = personalReceiptNo;
                k.MemberShimei__r = mi;
                k.MemberFamilyShimei__r = fi;
            }
    
            k.Status__c = status;
            k.KenshinDate__c = kenshinDate;
            k.wish_time__c = wishTime;
            k.CancelDate__c = cancelDate;
            k.KenshinPlan__c = kenshinPlan;
            k.KenshinArea__c = kenshinArea;
            k.KenshinHospital__C = kenshinHospital;
            lk.add(k);
        }
        
        upsert lk;
    
        delete kis;
    }*/
    
    static testMethod void KenshinImportControllerEx_Test()
    {
        KenshinImportControllerEx con = new KenshinImportControllerEx(null); 
        
        Kenshin_Import__c ki = new Kenshin_Import__c();
        insert ki;
        con.init();
        
        Attachment att = new Attachment();
        att.Name = 'TEST';
        att.Body = Blob.valueOf('"status","wb_member_cd","order_num","order_detail_num","wish_date","wish_time","cancel_datetime","item_cd","jurisdiction_division_name","name"' 
            + '\r\n'
            + '"E","1NDL1264862",104936,117693,2009/12/19,16:00:00,,"101",",');
        att.ParentId = ki.Id;
        insert att;
        con.init();
        
        con.runBatch();
        
        delete [select Id from Kenshin_Import__c];
        con.init();
        con.Attachment.Name = 'TEST';
        con.Attachment.Body = Blob.valueOf('"status","wb_member_cd","order_num","order_detail_num","wish_date","wish_time","cancel_datetime","item_cd","jurisdiction_division_name","name"' 
            + '\r\n'
            + '"E","1NDL1264862",104936,117693,2009/12/19,16:00:00,,"101",",');
        con.upload();
    }
}