unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>会員番号</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_soap_log__c.object
<CustomObject>
    <fields>
        <fullName>JStr__c</fullName>
        <label>JStr</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LastAcessDate__c</fullName>
        <label>LastAcessDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LogIn__c</fullName>
        <label>LogIn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberID__c</fullName>
        <externalId>true</externalId>
        <label>MemberID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberInfo__c</fullName>
        <label>MemberInfo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>MemberNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>SOAPログ</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SOAPログ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_log.cls
@RestResource(urlMapping='/soap/ApiLog/*')

global with sharing class wb_soap_log {
    
    @HttpGet
    global static List<wb_soap_log__c> getApiLog() {
    //global static string getApiLog() {    
        RestRequest req = RestContext.request;
        string plastmodifieddate;
        if ( req.params.get('lastmodifieddate') != null)
            plastmodifieddate= req.params.get('lastmodifieddate');
        
        string wheresql;
        
        if (plastmodifieddate != null) {
           // wheresql = '  Contract_HospitalName__c like \'%' + HospitalName + '%\'  and f_AppPostingTarget__c = true' ; 
             wheresql = ' lastmodifieddate >= ' + plastmodifieddate  ; 
        }
        
         // string soql = 'SELECT Id,IsDeleted,JStr__c,LastAcessDate__c,LastModifiedDate,LogIn__c,MemberID__c,MemberInfo__c,MemberNo__c,Type__c FROM wb_soap_log__c';
         string soql = 'SELECT Id,IsDeleted, LastAcessDate__c,LastModifiedDate,LogIn__c,MemberID__c,MemberInfo__c,MemberNo__c,Type__c FROM wb_soap_log__c';
        if (wheresql != null )
        {
            soql = soql + ' ALL where ' + wheresql + ' order by LastModifiedDate limit 5000  ';
        } else 
        {
            soql = soql  + ' ALL order by LastModifiedDate limit 5000 ';     
        }
        
         List<wb_soap_log__c> Rst  = Database.query(soql);
        return Rst;
        //return soql;
    }

}