unpackaged/objects/MemberInfo__c.object
<CustomObject>
    <fields>
        <fullName>CompanyKeiyakuNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約番号</label>
        <referenceTo>ContractInfo__c</referenceTo>
        <relationshipLabel>会員情報</relationshipLabel>
        <relationshipName>R00N10000000HXmYEAW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員情報</label>
    <nameField>
        <label>会員氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_MD_datamigrate.cls
public class wb_MD_datamigrate {
    public List<Id> ContractIDs{get;set;}
    public wb_MD_datamigrate(){
        ContractIDs = new List<Id>();
          List<Id> IndID = new List<ID>();
        for ( AggregateResult r:[select CompanyKeiyakuNo__c
                         from Memberinfo__c
                         where CompanyKeiyakuNo__c != null
                         group by CompanyKeiyakuNo__c
                         order by count(Id) desc limit 7]){
                             ContractIDs.add(String.valueof(r.get('CompanyKeiyakuNo__c')));   
    }
    }

}