unpackaged/objects/wb_BudgetRate__c.object
<CustomObject>
    <description>WellBe Budget Exchange Rates</description>
    <fields>
        <fullName>FromCurrency__c</fullName>
        <label>元通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>レート</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ToCurrency__c</fullName>
        <label>切替通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>予算レート</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>予算レート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>Cps_AfterDeathImpediment__c</fullName>
        <label>（強制）死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_CancelDate__c</fullName>
        <label>（強制）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CommissionRate__c</fullName>
        <label>（強制）手数料率</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Commission__c</fullName>
        <label>（強制）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Currency__c</fullName>
        <label>（強制）保険通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentEndDate__c</fullName>
        <label>（強制）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentStartDate__c</fullName>
        <label>（強制）保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceAmount__c</fullName>
        <label>（強制）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceCompany__c</fullName>
        <label>（強制）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_MedicalCost__c</fullName>
        <label>（強制）医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathImpediment__c</fullName>
        <label>（強制）無責任死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathMedicalCost__c</fullName>
        <label>（強制）無責任医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtPropertyLoss__c</fullName>
        <label>（強制）無責任財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_PropertyLoss__c</fullName>
        <label>（強制）財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（強制)サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>車保険 (（強制)サービス)</relationshipLabel>
        <relationshipName>Cps_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vlt_CancelDate__c</fullName>
        <label>（任意）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_CommissionRate__c</fullName>
        <label>（任意）手数料率</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Commission__c</fullName>
        <label>（任意）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Currency__c</fullName>
        <label>（任意）保険通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_EndDate__c</fullName>
        <label>（任意）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceAmount__c</fullName>
        <label>（任意）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceCompany__c</fullName>
        <label>（任意）保険会社名</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（任意）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>Vlt_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vlt_StartDate__c</fullName>
        <label>（任意）保険始期</label>
        <type>Date</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>CommissionRate__c</fullName>
        <label>手数料率</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>問い合わせ番号</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>国</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_AfterDeathImpediment__c</fullName>
        <label>（強制）死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_MedicalCost__c</fullName>
        <label>（強制）医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathImpediment__c</fullName>
        <label>（強制）無責任死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathMedicalCost__c</fullName>
        <label>（強制）無責任医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtPropertyLoss__c</fullName>
        <label>（強制）無責任財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_PropertyLoss__c</fullName>
        <label>（強制）財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceClassification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員</fullName>
                </value>
                <value>
                    <fullName>健診</fullName>
                </value>
                <value>
                    <fullName>車保</fullName>
                </value>
                <value>
                    <fullName>搭乗</fullName>
                </value>
                <value>
                    <fullName>強制</fullName>
                </value>
                <value>
                    <fullName>任意</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>現地医療</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceCompany__c</fullName>
        <label>サービス会社</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_CI_CompulsoryRow.cls
public class wb_CI_CompulsoryRow {
    
    public string theCountry {get;set;}
    public string theCommissionCurrency {get;set;}
    public integer theLegalNumberofSeats {get;set;}
    
    public SelectOption[] Cps_InsuranceCompanyOptions {get;set;}
    public SelectOption[] Vlt_InsuranceCompanyOptions {get;set;}
    
    public wb_CIC_Compulsory__c theCompulsory { get; set; }
    
    public wb_CI_CompulsoryRow(wb_CIC_Compulsory__c cps ){
         theCompulsory = cps;
    }
    
    public wb_CI_CompulsoryRow( string c, string cur, integer s,  wb_CIC_Compulsory__c cps) {
        theCompulsory = cps;
        theCountry = c;
        theCommissionCurrency =cur;
        theLegalNumberofSeats = s;
        Cps_InsuranceCompanyOptions = getCps_InsuranceCompanyOptions();
        Vlt_InsuranceCompanyOptions = getVlt_InsuranceCompanyOptions();    
        
    }
    
    public SelectOption[] getCps_InsuranceCompanyOptions() {  
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','--None--'));  
        for (AggregateResult l : [ select ServiceCompany__c, count(Id) 
                                  FROM wb_Service__c
                                  where  ServiceClassification__c = '強制' and Country__c =:theCountry
                                  and Currency__c =:theCommissionCurrency // To limit the Insurance currrent be same as Commission current
                                  group by ServiceCompany__c 	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('ServiceCompany__c')), String.valueOf(l.get('ServiceCompany__c')) ));  
                                  }                           
        return opt;  
    } 
    
    public SelectOption[] getVlt_InsuranceCompanyOptions() {  
        
        List<SelectOption>  opt = new  List<SelectOption>();
        opt.add(new SelectOption('','--None--'));  
        for (AggregateResult l : [ select ServiceCompany__c, count(Id) 
                                  FROM wb_Service__c
                                  where  ServiceClassification__c = '任意' and Country__c =:theCountry  
                                  and Currency__c =:theCommissionCurrency // To limit the Insurance currrent be same as Commission current
                                  group by ServiceCompany__c 	]) {  
                                      opt.add(new SelectOption(String.valueOf(l.get('ServiceCompany__c')), String.valueOf(l.get('ServiceCompany__c')) ));  
                                  }                           
        return opt;  
    } 
    
    public void fetchComplusoryInsuranceFee()
    {
        if ( theCompulsory.Cps_InsuranceCompany__c <> null ) {
            
            
            
            wb_Service__c Service = [SELECT Id, Currency__c,
                                     Cps_MedicalCost__c, Cps_AfterDeathImpediment__c, Cps_NoLbtAfterDeathMedicalCost__c, Cps_NoLbtAfterDeathImpediment__c, 
                                     Cps_NoLbtPropertyLoss__c, Cps_PropertyLoss__c, // Cps_ServiceFee__c, 
                                     CommissionRate__c, ContactNumber__c
                                     FROM wb_Service__c 
                                     where  ServiceCompany__c =:theCompulsory.Cps_InsuranceCompany__c and Country__c =:theCountry  
                                     and ServiceClassification__c = '強制'  and Enable__c = true
                                     limit 1 ];
            theCompulsory.Cps_Currency__c = Service.Currency__c;
            
            decimal ex_rate;
            if ( Service.Currency__c <> theCommissionCurrency ) {
                wb_BudgetRate__c rate = [SELECT ToCurrency__c, Rate__c, FromCurrency__c 
                                         FROM wb_BudgetRate__c where FromCurrency__c =:Service.Currency__c and ToCurrency__c=:theCommissionCurrency];
                ex_rate = rate.Rate__c;
            } else {
                ex_rate =1;
            }
            
            
            theCompulsory.Cps_AfterDeathImpediment__c = Service.Cps_AfterDeathImpediment__c;
            theCompulsory.Cps_MedicalCost__c  = Service.Cps_MedicalCost__c;   
            theCompulsory.Cps_PropertyLoss__c = Service.Cps_PropertyLoss__c;
            theCompulsory.Cps_NoLbtAfterDeathImpediment__c = Service.Cps_NoLbtAfterDeathImpediment__c;
            theCompulsory.Cps_NoLbtAfterDeathMedicalCost__c  = Service.Cps_NoLbtAfterDeathMedicalCost__c;   
            theCompulsory.Cps_NoLbtPropertyLoss__c = Service.Cps_NoLbtPropertyLoss__c;
            // theCompulsory.Cps_InsuranceAmount__c = Service.Cps_ServiceFee__c * ex_rate;
            theCompulsory.Cps_CommissionRate__c = Service.CommissionRate__c; 
            //  theCompulsory.Cps_Commission__c = theCompulsory.Cps_InsuranceAmount__c * ( Service.CommissionRate__c/100);
            theCompulsory.Cps_Service__c = Service.ID;
        } else {
            theCompulsory.Cps_Currency__c=null;
            theCompulsory.Cps_AfterDeathImpediment__c =null;
            theCompulsory.Cps_MedicalCost__c  = null;   
            theCompulsory.Cps_PropertyLoss__c = null;
            theCompulsory.Cps_NoLbtAfterDeathImpediment__c = null;
            theCompulsory.Cps_NoLbtAfterDeathMedicalCost__c  = null; 
            theCompulsory.Cps_NoLbtPropertyLoss__c = null;
            theCompulsory.Cps_InsuranceAmount__c = null;
            theCompulsory.Cps_CommissionRate__c = null; 
            theCompulsory.Cps_Commission__c=null;
            theCompulsory.Cps_Service__c = null;
        }
        
    }
    
    public void fetchComplusoryInsuranceFeeOffline( List<wb_Service__c> ServiceMaster )
    {
        if ( theCompulsory.Cps_InsuranceCompany__c <> null ) {
            

            wb_Service__c Service;
            for ( integer i=0; i < ServiceMaster.size(); i++ ){
                if (ServiceMaster[i].ServiceCompany__c== theCompulsory.Cps_InsuranceCompany__c){
                    Service = ServiceMaster[i];
                    i = ServiceMaster.size();
                }
            }
            
            if ( Service != null ){
                theCompulsory.Cps_Currency__c = Service.Currency__c;
                system.debug( theCompulsory.Cps_Currency__c + ' ' +Service.Currency__c + ' ' + theCommissionCurrency);
                decimal ex_rate;
                if ( Service.Currency__c <> theCommissionCurrency ) {
                    wb_BudgetRate__c rate = [SELECT ToCurrency__c, Rate__c, FromCurrency__c 
                                             FROM wb_BudgetRate__c where FromCurrency__c =:Service.Currency__c and ToCurrency__c=:theCommissionCurrency];
                    ex_rate = rate.Rate__c;
                } else {
                    ex_rate =1;
                }
                
                
                theCompulsory.Cps_AfterDeathImpediment__c = Service.Cps_AfterDeathImpediment__c;
                theCompulsory.Cps_MedicalCost__c  = Service.Cps_MedicalCost__c;   
                theCompulsory.Cps_PropertyLoss__c = Service.Cps_PropertyLoss__c;
                theCompulsory.Cps_NoLbtAfterDeathImpediment__c = Service.Cps_NoLbtAfterDeathImpediment__c;
                theCompulsory.Cps_NoLbtAfterDeathMedicalCost__c  = Service.Cps_NoLbtAfterDeathMedicalCost__c;   
                theCompulsory.Cps_NoLbtPropertyLoss__c = Service.Cps_NoLbtPropertyLoss__c;
                // theCompulsory.Cps_InsuranceAmount__c = Service.Cps_ServiceFee__c * ex_rate;
                theCompulsory.Cps_CommissionRate__c = Service.CommissionRate__c; 
                //  theCompulsory.Cps_Commission__c = theCompulsory.Cps_InsuranceAmount__c * ( Service.CommissionRate__c/100);
                theCompulsory.Cps_Service__c = Service.ID;
            }
        } else {
            theCompulsory.Cps_Currency__c=null;
            theCompulsory.Cps_AfterDeathImpediment__c =null;
            theCompulsory.Cps_MedicalCost__c  = null;   
            theCompulsory.Cps_PropertyLoss__c = null;
            theCompulsory.Cps_NoLbtAfterDeathImpediment__c = null;
            theCompulsory.Cps_NoLbtAfterDeathMedicalCost__c  = null; 
            theCompulsory.Cps_NoLbtPropertyLoss__c = null;
            theCompulsory.Cps_InsuranceAmount__c = null;
            theCompulsory.Cps_CommissionRate__c = null; 
            theCompulsory.Cps_Commission__c=null;
            theCompulsory.Cps_Service__c = null;
        }
        
    }
    
    
    public void fetchVoluntaryInsuranceFee()
    {
        wb_Service__c Service = [SELECT Id, Currency__c,  CommissionRate__c
                                 FROM wb_Service__c 
                                 where  ServiceCompany__c =:theCompulsory.Vlt_InsuranceCompany__c and Country__c =:theCountry  
                                 and ServiceClassification__c = '任意'  and Enable__c = true
                                 limit 1 ];
        theCompulsory.VLT_SERVICE__C = Service.id;
        theCompulsory.Vlt_Currency__c = Service.Currency__c;
        theCompulsory.Vlt_CommissionRate__c = Service.CommissionRate__c;
        
    }
    
    public void fetchVoluntaryInsuranceFeeOffLine(List<wb_Service__c> ServiceMaster)
    {
        wb_Service__c Service;
        for (integer i = 0; i < ServiceMaster.size(); i++ ){
            if ( ServiceMaster[i].ServiceCompany__c == theCompulsory.Vlt_InsuranceCompany__c){
                Service =  ServiceMaster[i];
                i = ServiceMaster.size();
            }
        }
        theCompulsory.VLT_SERVICE__C = Service.id;
        theCompulsory.Vlt_Currency__c = Service.Currency__c;
        theCompulsory.Vlt_CommissionRate__c = Service.CommissionRate__c;
        
    }
    
    
    public void fetchCpsCommissionFee()
    {
        if ( theCompulsory.Cps_InsuranceAmount__c != null && theCompulsory.Cps_CommissionRate__c != null)
            theCompulsory.Cps_Commission__c = (theCompulsory.Cps_CommissionRate__c/100) * theCompulsory.Cps_InsuranceAmount__c; 
        else
            theCompulsory.Cps_Commission__c = null; 
    }
    
    public void fetchCpsCommissionRate()
    {
        theCompulsory.Cps_CommissionRate__c = (theCompulsory.Cps_Commission__c/theCompulsory.Cps_InsuranceAmount__c)*100; 
    }
    
    public void fetchVltCommissionFee()
    { 
        if ( theCompulsory.Vlt_InsuranceAmount__c != null && theCompulsory.Vlt_CommissionRate__c != null )
            theCompulsory.Vlt_Commission__c = (theCompulsory.Vlt_CommissionRate__c/100) * theCompulsory.Vlt_InsuranceAmount__c; 
        else
            theCompulsory.Vlt_Commission__c = null; 
        
        //if (( theCompulsory.Vlt_CommissionRate__c != null) && (theCompulsory.Vlt_CommissionRate__c != null ))
        //theCompulsory.Vlt_Commission__c = (theCompulsory.Vlt_CommissionRate__c/100) * theCompulsory.Vlt_InsuranceAmount__c; 
    }
    
    public void fetchVltCommissionRate()
    {   decimal a = theCompulsory.Vlt_InsuranceAmount__c;
     decimal c = theCompulsory.Vlt_Commission__c;
     theCompulsory.Vlt_CommissionRate__c = (c/a)*100; 
    }
    
    public void fetchCps_EndDate(){
        Date s = theCompulsory.Cps_CurrentStartDate__c;
        s = s.addYears(1);
        s = s.addDays(-1);
        theCompulsory.Cps_CurrentEndDate__c = s;
        //theCompulsory.Cps_CancelDate__c = s;
    }
    
    public void fetchVlt_EndDate(){
        if (theCompulsory.Vlt_StartDate__c != null) {
            Date s = theCompulsory.Vlt_StartDate__c;
            s = s.addYears(1);
            s = s.addDays(-1);
            theCompulsory.Vlt_EndDate__c = s;
            //theCompulsory.Vlt_CancelDate__c = s;
        } else {
            theCompulsory.Vlt_EndDate__c = null;
            //theCompulsory.Vlt_CancelDate__c = null;
        }
        
    }
    
}