unpackaged/objects/wb_BudgetRate__c.object
<CustomObject>
    <description>WellBe Budget Exchange Rates</description>
    <fields>
        <fullName>BudgetYear__c</fullName>
        <label>予算年</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CeilingUnit__c</fullName>
        <label>切上単位</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FromCurrency__c</fullName>
        <label>元通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromDate__c</fullName>
        <label>開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MonthCeilingUnit__c</fullName>
        <label>切上単位（月）</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>レート</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ToCurrency__c</fullName>
        <label>切替通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToDate__c</fullName>
        <label>終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>YearCeilingUnit__c</fullName>
        <label>切上単位（年）</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>予算レート</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>予算レート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_BudgetRateExt.cls
public class wb_BudgetRateExt {
    
    private ApexPages.StandardController standardController;
    public List<wb_BudgetRate__c> BudgetRate {get;set;}
    public integer selectedYear {get;set;}
    public wb_BudgetRate__c currentDateRage {get;set;}
    public date selectedYearStartDate {get;set;}
    public date selectedYearEndDate {get;set;}
    
    public wb_BudgetRateExt(ApexPages.StandardController stdController){
        this.standardController = stdController;
        currentDateRage = new wb_BudgetRate__c();
        integer currYear = System.Today().year();
        currentDateRage.BudgetYear__c = currYear;
        currentDateRage.FromDate__c = Date.newInstance(currYear,4,1);
        currentDateRage.ToDate__c= Date.newInstance(currYear +1,3,31);

        
        BudgetRate = [select id, Rate__c, //CeilingUnit__c, 
                      YearCeilingUnit__c, MonthCeilingUnit__c, FromDate__c,ToDate__c,ToCurrency__c,FromCurrency__c, BudgetYear__c
                      from wb_BudgetRate__c 
                      where FromDate__c=:currentDateRage.FromDate__c and ToDate__c =:currentDateRage.ToDate__c
                     order by ToCurrency__c];

    }
    
    public PageReference fetchBudgetRates(){
        
        integer currYear;
        currYear =  Integer.Valueof(currentDateRage.BudgetYear__c) ;
        currentDateRage.FromDate__c = Date.newInstance(currYear,4,1);
        currentDateRage.ToDate__c= Date.newInstance(currYear +1,3,31);
        BudgetRate = [select Rate__c, //CeilingUnit__c, 
                      YearCeilingUnit__c, MonthCeilingUnit__c, FromDate__c,ToDate__c,ToCurrency__c,FromCurrency__c, BudgetYear__c, id
                      from wb_BudgetRate__c 
                      where FromDate__c=: currentDateRage.FromDate__c and ToDate__c =:  currentDateRage.ToDate__c
                      order by ToCurrency__c];
        
        AggregateResult[] AgR = [select ToCurrency__c, count(id)
                                    from wb_BudgetRate__c 
                                    group by ToCurrency__c
                                    order by ToCurrency__c];
        
        for (AggregateResult r:AgR ) {
            boolean found = false;
            for ( wb_BudgetRate__c br:BudgetRate) {
                if ( String.valueOf(r.get('ToCurrency__c') )== br.ToCurrency__c  ){
                    found = true;
                    continue;   
                }
            }
            if (found==false)
            {
               wb_BudgetRate__c b = new wb_BudgetRate__c(Rate__c=null,FromDate__c =  currentDateRage.FromDate__c,
                                         ToDate__c = currentDateRage.ToDate__c,
                                         ToCurrency__c = String.valueOf(r.get('ToCurrency__c')),
                                         FromCurrency__c = 'USD',
                                         BudgetYear__c = currYear
                                        );
                BudgetRate.add(b);
            }
        }
        return null;
    }
    
    
    public PageReference SaveRecords(){
        
		upsert BudgetRate;
        
        //return new PageReference('https://cs6.salesforce.com/a0J/o');
        return null;
    }

    
    
    public List<SelectOption> getYearsOptions() {
        List<SelectOption> options = new List<SelectOption>();
        
        integer currentYear = System.Today().year();
        
        selectedYear=currentYear;
        for ( integer y = currentYear - 5 ; y <= currentYear + 2; y ++ ){
            options.add(new SelectOption(String.valueof(y),String.valueof(y)));  
        }
      
        return options;
    }
    
    public SelectOption[] YearsOptions;
    
}