unpackaged/objects/wb_CarInsurance__c.object
<CustomObject>
    <description>WellBe Car related Insurance Contract</description>
    <fields>
        <fullName>AcctPIC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>担当（計上）</label>
        <referenceTo>Shimei__c</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>StaffCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AffiliationDistrict__c</fullName>
        <label>所属地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <label>契約店</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>属性</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員企業</fullName>
                </value>
                <value>
                    <fullName>非会員企業</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CommissionCurrency__c</fullName>
        <label>手数料通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>CompanyCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractDistrict__c</fullName>
        <label>契約地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>自動車関連保険契約</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>自動車関連保険契約</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>CarInsuranceCar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>InsurancedCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EngineNo__c</fullName>
        <label>エンジン番号</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstRegistryDate__c</fullName>
        <label>初登年月</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FrameNo__c</fullName>
        <label>車台番号</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalNumberofSeats__c</fullName>
        <label>法定座席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>車型</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalCar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前の対象番号</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>入替対象車</relationshipLabel>
        <relationshipName>ReplacementCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>所有区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>所有</fullName>
                </value>
                <value>
                    <fullName>レンタル</fullName>
                    <label>リース／レンタル</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pattern__c</fullName>
        <externalId>true</externalId>
        <label>形態</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingAction__c</fullName>
        <label>アクション待ち</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistryNumber__c</fullName>
        <label>登録番号</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplacedDate__c</fullName>
        <label>異動日0時</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UsingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>利用会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>UsingCompanyInsurancedCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>InsurancedCar_Cps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>Car_Cps_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cps_CancelDate__c</fullName>
        <label>（強制）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentEndDate__c</fullName>
        <label>（強制）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentStartDate__c</fullName>
        <label>（強制）保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceCompany__c</fullName>
        <label>（強制）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_CancelDate__c</fullName>
        <label>（任意）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_EndDate__c</fullName>
        <label>（任意）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceCompany__c</fullName>
        <label>（任意）保険会社名</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_StartDate__c</fullName>
        <label>（任意）保険始期</label>
        <type>Date</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Passenger__c.object
<CustomObject>
    <description>WellBe Car Passenger Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CIC_Psgr_Ins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>Car_Psgr_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP_CancelDate__c</fullName>
        <label>（OP）解除日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_CommodityName__c</fullName>
        <label>（OP）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_CurrentEndDate__c</fullName>
        <label>（OP）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_CurrentStartDate__c</fullName>
        <label>（OP）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_Plan__c</fullName>
        <label>（OP）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CancelDate__c</fullName>
        <label>（搭乗）解約日24時</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_CommodityName__c</fullName>
        <label>（搭乗）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentEndDate__c</fullName>
        <label>（搭乗）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentStartDate__c</fullName>
        <label>（搭乗）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceCompany__c</fullName>
        <label>（搭乗）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_InsurancePlan__c</fullName>
        <label>（搭乗）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>搭乗保険</label>
    <nameField>
        <label>搭乗保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_CarInsuranceDetailView.cls
public class wb_CarInsuranceDetailView {
    ApexPages.StandardController stdController;
    public wb_CarInsurance__c theCarInsurance {get;set;}
    public List<wb_CI_InsurancedCarRow> InsurancedCarsList {get;set;}
    public List<wb_CI_InsurancedCarRow> InsurancedCarsNoEffList {get;set;}
    
    List<wb_CarInsurancedCars__c> Cars{get;set;}
    List<wb_CIC_Passenger__c> Passengers{get;set;}
    List<wb_CIC_Compulsory__c> Compulsoris{get;set;}


    public wb_CarInsuranceDetailView(ApexPages.StandardController stdController){
        this.stdController = stdController;
                  theCarInsurance = (wb_CarInsurance__c) stdController.getRecord();
        
        
        if ( theCarInsurance.id != null ) {
            theCarInsurance = [select Name, Status__c, Agent__c ,AffiliationDistrict__c,ContractDate__c,
                            ContractCompany__c,ContractCompany__r.name,
                            ContractDistrict__c,ContractCountry__c, Attribute__c, CommissionCurrency__c, 
                            AcctPIC__c
                            from wb_CarInsurance__c where id =: theCarInsurance.Id];
            
            LIST<wb_CarInsurancedCars__c> InsurancedCars = [SELECT id, Name, UsingCompany__c, EngineNo__c, Car__c, CarInsurance__c, Model__c, FrameNo__c,
                              LegalNumberofSeats__c,  Ownership__c,  FirstRegistryDate__c,
                              ReplacedDate__c, //f_EffectiveInsurance__c,
                              PendingAction__c, Pattern__c
                              FROM wb_CarInsurancedCars__c 
                              where  CarInsurance__c =: theCarInsurance.Id ];
            //system.debug( InsurancedCars.size());
            InsurancedCarsList = new List<wb_CI_InsurancedCarRow>();
            InsurancedCarsNoEffList = new List<wb_CI_InsurancedCarRow>();
            
            List<wb_CI_InsurancedCarRow> theCarsList = GetCarsList(theCarInsurance.id);
            
           // system.debug( theCarsList.size());
            for ( wb_CI_InsurancedCarRow car:theCarsList){
                if (car.IsAmendable == true && car.IsPending ==false)
                    InsurancedCarsList.add( car);
                else
                    InsurancedCarsNoEffList.add(car);
            }
            
           // system.debug(InsurancedCarsList.size() + ' ' + InsurancedCarsNoEffList.size() );
            /*
            for (wb_CarInsurancedCars__c c:InsurancedCars){
               
                wb_CI_InsurancedCarRow car = new wb_CI_InsurancedCarRow(c);
                if (car.IsAmendable == true && car.IsPending ==false)
                    InsurancedCarsList.add( car);
                else
                    InsurancedCarsNoEffList.add(car);
                 system.debug('C V:' + c.Name + ' ' + car.IsAmendable + ' ' + car.IsPending + car.MyProduct);
            } */
            
         //   status = CarInsurance.Status__c;
        } 
    }
    
    public List<wb_CI_InsurancedCarRow> GetCarsList(string id){
           Cars = new List<wb_CarInsurancedCars__c>();
        //List<wb_CarInsurancedCars__c> 
            Cars = [SELECT id, Name, UsingCompany__c, EngineNo__c, Car__c, 
                                              CarInsurance__c, Model__c, FrameNo__c,
                                              LegalNumberofSeats__c,  Ownership__c,  FirstRegistryDate__c,
                                              ReplacedDate__c,// f_EffectiveInsurance__c,
                                              PendingAction__c,OriginalCar__c , RegistryNumber__c, Pattern__c
                                              FROM wb_CarInsurancedCars__c 
                                              where CarInsurance__c =: Id
                                              order by RegistryNumber__c, id];
         Passengers = new List<wb_CIC_Passenger__c>();
        //List<wb_CIC_Passenger__c>
            Passengers = [select Psgr_InsuranceCompany__c,Psgr_CommodityName__c, Psgr_InsurancePlan__c,
                                                OP_CommodityName__c, OP_Plan__c, Psgr_CurrentEndDate__c, OP_CurrentEndDate__c,Psgr_CancelDate__c ,
                                                Psgr_CurrentStartDate__c,OP_CancelDate__c,OP_CurrentStartDate__c,CarInsurancedCar__c, CarInsurancedCar__r.id
                                                from wb_CIC_Passenger__c 
                                                where CarInsurancedCar__r.CarInsurance__c =:id
                                                order by CarInsurancedCar__r.id];
         Compulsoris = new  list<wb_CIC_Compulsory__c>();
       // list<wb_CIC_Compulsory__c>
            Compulsoris = [select Cps_InsuranceCompany__c,Vlt_InsuranceCompany__c, Cps_CurrentStartDate__c,
                                                  Cps_CurrentEndDate__c,Cps_CancelDate__c,Vlt_StartDate__c,Vlt_EndDate__c,Vlt_CancelDate__c, CarInsurancedCar__c , CarInsurancedCar__r.id
                                                  from wb_CIC_Compulsory__c 
                                                  where CarInsurancedCar__r.CarInsurance__c =:id
                                                  order by CarInsurancedCar__r.id];
        
        List<wb_CI_InsurancedCarRow> theCarList = new List<wb_CI_InsurancedCarRow>();
        
        List<wb_CIC_Passenger__c> Ps = new List<wb_CIC_Passenger__c>();
        List<wb_CIC_Compulsory__c> Cs = new List<wb_CIC_Compulsory__c>();
        integer cari=0, psgri=0, cpsi=0;
        integer psgrip, cpsip;

        
        for ( cari=0; cari < Cars.size(); cari ++ ){
         //   system.debug(  'cars' + cari + ' ' + cars[cari].RegistryNumber__c + ' ' + Passengers.size() + ' ' + Compulsoris.size() );
            Ps = new List<wb_CIC_Passenger__c>();
            Cs = new List<wb_CIC_Compulsory__c>();
            
            for (psgri= 0 ; psgri < Passengers.size(); psgri ++ )
            {
                if ( Passengers[psgri].CarInsurancedCar__r.id == cars[cari].id){
                    wb_CIC_Passenger__c newp = new wb_CIC_Passenger__c();
                    newp = Passengers[psgri].clone(true);
                    Ps.add(newp);     
                } //else {
                 //   psgrip = psgri;
                 //   psgri = Passengers.size();
              //  }
                
            }
            
          //  if (psgri == Passengers.size() + 1 )
        //        psgri = psgrip;
            
            for (cpsi = 0 ; cpsi < Compulsoris.size(); cpsi ++ )
            {
                if ( Compulsoris[cpsi].CarInsurancedCar__r.id == cars[cari].id){
                    wb_CIC_Compulsory__c newc = new wb_CIC_Compulsory__c();
                    newc = Compulsoris[cpsi].clone(true);
                    Cs.add(newc);     
                }// else {
                //    cpsip = cpsi;
                //    cpsi = Compulsoris.size();
               // }
                
            }
            
        //    if (cpsi == Compulsoris.size() + 1 )
        //        cpsi = cpsip;
            
            //system.debug('cars: ' + cars[cari].name + ' ' + Ps.size()  + ' ' + psgrip + ' ' + psgri + ' ' + Passengers.size());
            //theCarList.add(new wb_CI_InsurancedCarRow(cars[cari], Passengers, Compulsoris));
            theCarList.add(new wb_CI_InsurancedCarRow(cars[cari], Ps, Cs));
        }
        
        return theCarList;
    }
    
    
    
}