unpackaged/objects/wb_CarInsurance__c.object
<CustomObject>
    <description>WellBe Car related Insurance Contract</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>属性</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員企業</fullName>
                </value>
                <value>
                    <fullName>非会員企業</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CommissionCurrency__c</fullName>
        <label>手数料通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>CompanyCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>自動車関連保険契約</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>自動車関連保険契約</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>CarInsuranceCar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>InsurancedCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EngineNo__c</fullName>
        <label>エンジン番号</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstRegistryDate__c</fullName>
        <label>初登年月</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalNumberofSeats__c</fullName>
        <label>法定座席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>車型</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>所有区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>所有</fullName>
                </value>
                <value>
                    <fullName>レンタル</fullName>
                    <label>リース／レンタル</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReplacedDate__c</fullName>
        <label>異動日0時</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UsingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>利用会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>UsingCompanyInsurancedCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>InsurancedCar_Cps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>Car_Cps_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cps_PropertyLoss__c</fullName>
        <label>（強制）財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Passenger__c.object
<CustomObject>
    <description>WellBe Car Passenger Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CIC_Psgr_Ins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>Car_Psgr_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DriverSeatInsurance__c</fullName>
        <label>運転席保険</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_CancelDate__c</fullName>
        <label>（OP）解除日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_CommissionRate__c</fullName>
        <label>（OP）手数料率</label>
        <precision>9</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_Commission__c</fullName>
        <label>（OP）手数料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_CommodityName__c</fullName>
        <label>（OP）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_CurrentEndDate__c</fullName>
        <label>（OP）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_CurrentStartDate__c</fullName>
        <label>（OP）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_InsuranceFee__c</fullName>
        <label>（OP）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_Plan__c</fullName>
        <label>（OP）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_PolicyNumber__c</fullName>
        <label>（OP）証券番号</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（OP）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CI_OptionService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP_StdDriverSeatFee__c</fullName>
        <label>（OP）標準運伝席保険料</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_StdPassengerSeatFee__c</fullName>
        <label>（OP）標準搭乗席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PassagerSeatInsurance__c</fullName>
        <label>付保搭乗席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_AffiliationArea__c</fullName>
        <label>（搭乗）所属地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CancelDate__c</fullName>
        <label>（搭乗）解約日24時</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_CancelReason__c</fullName>
        <label>（搭乗）保険解約理由</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CommissionRate__c</fullName>
        <label>（搭乗）手数料率</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_Commission__c</fullName>
        <label>（搭乗）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_CommodityName__c</fullName>
        <label>（搭乗）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentEndDate__c</fullName>
        <label>（搭乗）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentStartDate__c</fullName>
        <label>（搭乗）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_InitialStartDate__c</fullName>
        <label>（搭乗）初年度始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceCompany__c</fullName>
        <label>（搭乗）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceFee__c</fullName>
        <label>（搭乗）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_InsurancePlan__c</fullName>
        <label>（搭乗）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_PolicyNumber__c</fullName>
        <label>（搭乗）証券番号</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（搭乗）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険 (（搭乗）サービス)</relationshipLabel>
        <relationshipName>CI_Psgr_Ins_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Psgr_StdDriverSeatFee__c</fullName>
        <label>（搭乗）標準運転席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_StdPassengerSeatFee__c</fullName>
        <label>（搭乗）標準搭乗席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_OPBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(OP_RemainInsuranceFee__c),0, OP_RemainInsuranceFee__c) - OP_InsuranceFee__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（OP）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_PsgrBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(Psgr_RemainInsuranceFee__c), 0, Psgr_RemainInsuranceFee__c) - Psgr_InsuranceFee__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（搭乗）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>搭乗保険</label>
    <nameField>
        <label>搭乗保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>DriverSeatInsurance__c</fullName>
        <label>運転席保険</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Vehicle__c.object
<CustomObject>
    <description>WellBe Car Master for Insurances</description>
    <fields>
        <fullName>LegalNumberofSeats__c</fullName>
        <label>法定座席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>車型</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>所有区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>所有</fullName>
                </value>
                <value>
                    <fullName>レンタル</fullName>
                    <label>リース／レンタル</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>利用会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>車両</relationshipLabel>
        <relationshipName>UsingCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>車両</label>
    <nameField>
        <label>登録番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_CarInsuranceCarsDetail.cls
public class wb_CarInsuranceCarsDetail {
    ApexPages.StandardController stdController;
    public PageReference refresh = ApexPages.currentPage();
    
    public wb_CarInsuranceCarsDetail(ApexPages.StandardController stdController){
        this.stdController = stdController;
        
        CarInsurancedCars = (wb_CarInsurancedCars__c) stdController.getRecord();
        //CarInsurancedCars.id ='a0QN0000005aLGQ';
        MeType = Apexpages.currentpage().getparameters().get('Type');
        if  (CarInsurancedCars.id != null) {
            CarInsurancedCars = [ select id, Name, CarInsurance__c, Car__c,FirstRegistryDate__c, UsingCompany__c,
                                 Model__c,Ownership__c, LegalNumberofSeats__c,EngineNo__c, ReplacedDate__c 
                                 from wb_CarInsurancedCars__c where id =: CarInsurancedCars.id];    
            
            CarInsurance = [SELECT Name, Id, ContractCompany__c,ContractCompany__r.name, CommissionCurrency__c,
                            ContractCountry__c, ContractDate__c, Attribute__c, Status__c
                            FROM wb_CarInsurance__c
                            where ID =:CarInsurancedCars.CarInsurance__c ];
            
            
            
            PassengerDT = new List<wb_CI_PassangerRow>();
            
            for ( wb_CIC_Passenger__c p:[SELECT Psgr_CancelDate__c , 
                                         Psgr_CurrentEndDate__c, Psgr_CurrentStartDate__c, 
                                         Psgr_StdDriverSeatFee__c, Psgr_StdPassengerSeatFee__c,Psgr_CommissionRate__c, Psgr_Commission__c, Psgr_AffiliationArea__c, 
                                         Psgr_CommodityName__c, Psgr_InitialStartDate__c, Psgr_InsuranceFee__c, 
                                         Psgr_InsuranceCompany__c, Psgr_InsurancePlan__c,  
                                         Psgr_Service__c,OP_CancelDate__c,
                                         OP_PolicyNumber__c,
                                         OP_CurrentEndDate__c, OP_CurrentStartDate__c, 
                                         OP_CommodityName__c,  OP_Plan__c, OP_Service__c, 
                                         OP_StdDriverSeatFee__c, OP_StdPassengerSeatFee__c, OP_InsuranceFee__c,	OP_CommissionRate__c, OP_Commission__c,
                                         Name, CarInsurancedCar__c, CarInsurancedCar__r.ReplacedDate__c, Id , Psgr_PolicyNumber__c,
                                         Psgr_CancelReason__c, PassagerSeatInsurance__c, DriverSeatInsurance__c,f_PsgrBillingAmount__c ,f_OPBillingAmount__c 
                                         FROM wb_CIC_Passenger__c where CarInsurancedCar__c =:CarInsurancedCars.id]
                ) {
                    PassengerDT.add( new wb_CI_PassangerRow(CarInsurance.ContractCountry__c, 
                                                            CarInsurance.CommissionCurrency__c, 
                                                            Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                            p
                                                           )
                                   );
                }
            
            
            CompulsoryDT = new List<wb_CI_CompulsoryRow>();
            
            for ( wb_CIC_Compulsory__c c:[SELECT Cps_PropertyLoss__c, Cps_PolicyNumber__c, Cps_NoLbtPropertyLoss__c, Cps_NoLbtAfterDeathImpediment__c, 
                                          Cps_NoLbtAfterDeathMedicalCost__c, Cps_AfterDeathImpediment__c, Cps_CommissionRate__c, 
                                          Cps_Commission__c, 
                                          Cps_MedicalCost__c, Cps_CancelReason__c, Cps_CancelDate__c, Cps_CurrentEndDate__c, Cps_InsuranceAmount__c, 
                                          Cps_CurrentStartDate__c, Cps_InsuranceCompany__c, Cps_Service__c, VIt_ScratchDamage__c, VIt_VehicleTheft__c, 
                                          VIt_VehicleDamage__c, Vlt_DriverInjury__c, Vlt_PassengerInjury__c, Vlt_PolicyNumber__c, Vlt_3rdPartyDamage__c, 
                                          Vlt_PsgrPersonalAccident__c, Vlt_CommissionRate__c, 
                                          Vlt_Commission__c, Vlt_Currency__c, Vlt_CancelReason__c, 
                                          Vlt_CancelDate__c, Vlt_EndDate__c, Vlt_InsuranceAmount__c, Vlt_StartDate__c, Vlt_InsuranceCompany__c, 
                                          Vlt_GlassBreakage__c, Vlt_OtherItems__c, Name, CarInsurancedCar__c, id ,
                                          Cps_Currency__c, Vlt_Selfburning__c, Vlt_Submersion__c, Vlt_Remark__c  
                                          FROM wb_CIC_Compulsory__c where CarInsurancedCar__c =:CarInsurancedCars.id]) {
                                              CompulsoryDT.add( new wb_CI_CompulsoryRow(CarInsurance.ContractCountry__c, 
                                                                                        CarInsurance.CommissionCurrency__c,
                                                                                        Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                                                        c
                                                                                       )
                                                              );
                                          }
            
        }
        else {
            
            CarInsurance = [SELECT Name, Id, ContractCompany__c,ContractCompany__r.name,
                            ContractCountry__c, ContractDate__c, Attribute__c, Status__c
                            FROM wb_CarInsurance__c
                            where ID =:CarInsurancedCars.CarInsurance__c ];
            
            CarInsurancedCars = new wb_CarInsurancedCars__c();
            CarInsurancedCars.CarInsurance__c = CarInsurance.id;
            PassengerDT = new List<wb_CI_PassangerRow>();
            CompulsoryDT = new List<wb_CI_CompulsoryRow>();
            
        }
        
        QuitMe = false;
        
    }
    
    public string MeType  {get;set;}
    public boolean QuitMe  {get;set;}
    //public boolean OpnCarTerminate {get;set;}
    public wb_CarInsurance__c CarInsurance {get;set;}
    public wb_CarInsurancedCars__c CarInsurancedCars {get;set;}
    
    public List<wb_CI_PassangerRow> PassengerDT {get;set;}
    public List<wb_CI_CompulsoryRow> CompulsoryDT {get;set;}
    
    public string thePassengerId {get;set;}
    public integer thePassengerIndex {get;set;}
    public void PassengerDT_remove(){
        if (thePassengerId != ''){
            if( PassengerDT.get(thePassengerIndex-1).thePassenger.id ==thePassengerId )
                delete PassengerDT.get(thePassengerIndex-1).thePassenger;
            PassengerDT.remove(thePassengerIndex-1);
        } else
        {
            PassengerDT.remove(thePassengerIndex-1);
        }
    }
    
    public string theCompulsoryId {get;set;}
    public integer theCompulsoryIndex {get;set;}
    public void CompulsoryDT_remove(){
        if (theCompulsoryId != ''){
            if( CompulsoryDT.get(theCompulsoryIndex-1).theCompulsory.id ==theCompulsoryId )
                delete CompulsoryDT.get(theCompulsoryIndex-1).theCompulsory;
            CompulsoryDT.remove(theCompulsoryIndex-1);
        } else
        {
            CompulsoryDT.remove(theCompulsoryIndex-1);
        }
    }
    
   // public wb_Vehicle__c Car {get;set;}
   // public wb_Service__c Service {get;set;}
    
   // public List<wb_Service__c> AllService{get;set;}
    
    
    public PageReference NewPassengerInsurance() {
        
        Integer n = [select id from  wb_CIC_Passenger__c where CarInsurancedCar__c =:CarInsurancedCars.id ].size();
        for ( wb_CI_PassangerRow p:PassengerDT) {
            if ( p.thePassenger.id == null){
                n ++;
            }
        }
        
        string nm = CarInsurancedCars.name + '-P' + string.valueof(n+1);            
        
        PassengerDT.add( new wb_CI_PassangerRow(CarInsurance.ContractCountry__c, 
                                                CarInsurance.CommissionCurrency__c, 
                                                Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                new wb_CIC_Passenger__c(CarInsurancedCar__c = CarInsurancedCars.id,  name = nm,
                                                                        Car__c = CarInsurancedCars.Car__c,
                                                                        PassagerSeatInsurance__c = CarInsurancedCars.LegalNumberofSeats__c - 1
                                                                       )
                                               )
                       );
        return null;
    }
    
    public PageReference NewCompulsoryInsurance() {
        
        Integer n = [select id from  wb_CIC_Compulsory__c where CarInsurancedCar__c =:CarInsurancedCars.id ].size();
        for ( wb_CI_CompulsoryRow p:CompulsoryDT) {
            if ( p.theCompulsory.id == null){
                n ++;
            }
        }
        
        string nm = CarInsurancedCars.name + '-C' + string.valueof(n+1);            
        
        CompulsoryDT.add( new wb_CI_CompulsoryRow(CarInsurance.ContractCountry__c, 
                                                  CarInsurance.CommissionCurrency__c, 
                                                  Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                  new wb_CIC_Compulsory__c(CarInsurancedCar__c = CarInsurancedCars.id,  name = nm, 
                                                                           Car__c = CarInsurancedCars.Car__c )
                                                 )
                        );
        
        return null;
    }
    
    
    public PageReference ValidateSaveClose(){
        
        validate();
        
        if(ApexPages.hasMessages(ApexPages.Severity.Error)){
            QuitMe = false;
            
        } else {
            for ( wb_CI_PassangerRow p:PassengerDT) {
                if (p.thePassenger.OP_Service__c != null && p.thePassenger.OP_CommodityName__c == null )
                    p.thePassenger.OP_Service__c = null;
                
                if ( p.thePassenger.id == null)
                    insert p.thePassenger;
                else
                    update p.thePassenger;
            }
            
            for ( wb_CI_CompulsoryRow c:CompulsoryDT) {
                if ( c.theCompulsory.id  == null)
                    insert c.theCompulsory;
                else
                    update c.theCompulsory;
            }
            QuitMe = true;
        }
        
        return null;
        
    }
    
    public PageReference ValidateSave(){
        
        validate();
        
        if(ApexPages.hasMessages(ApexPages.Severity.Error)){
            QuitMe = false;
            
        } else {
            for ( wb_CI_PassangerRow p:PassengerDT) {
                if ( p.thePassenger.id == null)
                    insert p.thePassenger;
                else
                    update p.thePassenger;
            }
            
            for ( wb_CI_CompulsoryRow c:CompulsoryDT) {
                if ( c.theCompulsory.id  == null)
                    insert c.theCompulsory;
                else
                    update c.theCompulsory;
            }
            QuitMe = false;
        }
        
        return null;
        
    }
    
    public PageReference validate()
    {
        for (wb_CI_PassangerRow psgr: PassengerDT)
        {
            if ( psgr.thePassenger.Psgr_InsuranceCompany__c == null ) 
                psgr.thePassenger.Psgr_InsuranceCompany__c.addError('!!!!');
            if ( psgr.thePassenger.Psgr_CommodityName__c == null ) 
                psgr.thePassenger.Psgr_CommodityName__c.addError('!!!!');
            
            if ( psgr.thePassenger.Psgr_InsurancePlan__c == null ) {
                psgr.thePassenger.Psgr_InsurancePlan__c.addError('!!!!'); 
            }   else {
                if ( psgr.thePassenger.Psgr_CurrentStartDate__c == null ) 
                    psgr.thePassenger.Psgr_CurrentStartDate__c.addError('!!!!'); 
                if ( psgr.thePassenger.Psgr_CurrentEndDate__c == null ) 
                    psgr.thePassenger.Psgr_CurrentEndDate__c.addError('!!!!'); 
            }
            
        }
        
        
        for (wb_CI_CompulsoryRow cps: CompulsoryDT)
        {
            
            if ( cps.theCompulsory.Cps_InsuranceCompany__c != null ||  cps.theCompulsory.Cps_CurrentStartDate__c != null
               ||  cps.theCompulsory.Cps_CurrentEndDate__c != null || cps.theCompulsory.Cps_InsuranceAmount__c != null ) {
                
                if ( cps.theCompulsory.Cps_CurrentStartDate__c == null ) 
                    cps.theCompulsory.Cps_CurrentStartDate__c.addError('!!!!'); 
                if ( cps.theCompulsory.Cps_CurrentEndDate__c == null ) 
                    cps.theCompulsory.Cps_CurrentEndDate__c.addError('!!!!'); 
                if ( cps.theCompulsory.Cps_InsuranceAmount__c == null ) 
                    cps.theCompulsory.Cps_InsuranceAmount__c.addError('!!!!'); 
                if ( cps.theCompulsory.Cps_InsuranceCompany__c == null ) 
                    cps.theCompulsory.Cps_InsuranceCompany__c.addError('!!!!'); 
              
            
            }
            
            if ( cps.theCompulsory.Vlt_InsuranceCompany__c != null || cps.theCompulsory.Vlt_StartDate__c != null ||
                cps.theCompulsory.Vlt_EndDate__c != null || cps.theCompulsory.Vlt_InsuranceAmount__c != null) {
                
                    if ( cps.theCompulsory.Vlt_StartDate__c == null ) 
                        cps.theCompulsory.Vlt_StartDate__c.addError('!!!!'); 
                    if ( cps.theCompulsory.Vlt_EndDate__c == null ) 
                        cps.theCompulsory.Vlt_EndDate__c.addError('!!!!'); 
                    if ( cps.theCompulsory.Vlt_InsuranceAmount__c == null ) 
                        cps.theCompulsory.Vlt_InsuranceAmount__c.addError('!!!!'); 
                    if ( cps.theCompulsory.Vlt_InsuranceCompany__c == null ) 
                        cps.theCompulsory.Vlt_InsuranceCompany__c.addError('!!!!'); 
                    if ( cps.theCompulsory.Vlt_CommissionRate__c == null ) 
                        cps.theCompulsory.Vlt_CommissionRate__c.addError('!!!!'); 
                
            }
               

        }
        
        return null;
    }
    
    public PageReference Cancel(){
        if (MeType=='popup'){
            QuitMe = true;
            return null;
        } else {
            PageReference returnPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
            return returnPage;
        }
        
        
    }

    
}