unpackaged/objects/wb_CarInsurance__c.object
<CustomObject>
    <description>WellBe Car related Insurance Contract</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>属性</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員企業</fullName>
                </value>
                <value>
                    <fullName>非会員企業</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CommissionCurrency__c</fullName>
        <label>手数料通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>CompanyCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>自動車関連保険契約</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>自動車関連保険契約</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>LegalNumberofSeats__c</fullName>
        <label>法定座席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Passenger__c.object
<CustomObject>
    <description>WellBe Car Passenger Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CIC_Psgr_Ins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DriverSeatInsurance__c</fullName>
        <label>運転席保険</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_CancelDate__c</fullName>
        <label>（OP）解除日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_Commission__c</fullName>
        <label>（OP）手数料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_CommodityName__c</fullName>
        <label>（OP）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_CurrentEndDate__c</fullName>
        <label>（OP）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_CurrentStartDate__c</fullName>
        <label>（OP）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OP_InsuranceFee__c</fullName>
        <label>（OP）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_Plan__c</fullName>
        <label>（OP）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（OP）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CI_OptionService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP_StdDriverSeatFee__c</fullName>
        <label>（OP）標準運伝席保険料</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_StdPassengerSeatFee__c</fullName>
        <label>（OP）標準搭乗席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PassagerSeatInsurance__c</fullName>
        <label>付保搭乗席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_AffiliationArea__c</fullName>
        <label>（搭乗）所属地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CancelDate__c</fullName>
        <label>（搭乗）解約日24時</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_Commission__c</fullName>
        <label>（搭乗）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_CommodityName__c</fullName>
        <label>（搭乗）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentEndDate__c</fullName>
        <label>（搭乗）現保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_CurrentStartDate__c</fullName>
        <label>（搭乗）現保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_InitialStartDate__c</fullName>
        <label>（搭乗）初年度始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceCompany__c</fullName>
        <label>（搭乗）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceFee__c</fullName>
        <label>（搭乗）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_InsurancePlan__c</fullName>
        <label>（搭乗）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（搭乗）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険 (（搭乗）サービス)</relationshipLabel>
        <relationshipName>CI_Psgr_Ins_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Psgr_StdDriverSeatFee__c</fullName>
        <label>（搭乗）標準運転席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_StdPassengerSeatFee__c</fullName>
        <label>（搭乗）標準搭乗席保険料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_OPBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(OP_RemainInsuranceFee__c),0, OP_RemainInsuranceFee__c) - OP_InsuranceFee__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（OP）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_PsgrBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(Psgr_RemainInsuranceFee__c), 0, Psgr_RemainInsuranceFee__c) - Psgr_InsuranceFee__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（搭乗）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>搭乗保険</label>
    <nameField>
        <label>搭乗保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_CIC_PassengerDT.cls
public class wb_CIC_PassengerDT {
    
    ApexPages.StandardController stdController;
    public id CI_ID {get;set;}
    public string CIC_ID {get;set;}

    public wb_CarInsurance__c CarInsurance {get;set;}
    public wb_CarInsurancedCars__c CarInsurancedCars {get;set;}
    
    public List<wb_CI_PassangerRow> PassengerDT {get;set;}
    
    public integer PassengerDTSize {get;set;}
    
    public wb_CIC_PassengerDT(ApexPages.StandardController stdController){
        this.stdController = stdController;
        CI_ID = apexpages.currentpage().getparameters().get('id');
        CIC_ID = apexpages.currentpage().getparameters().get('pv0');
        
       // CarInsurance = (wb_CarInsurance__c) stdController.getRecord();
        //CI_ID = 'a0fN0000005ZwByIAK';
        //CIC_ID ='a0hN0000005k9QYIAY';
        CarInsurance = [SELECT Name, Id, ContractCompany__c,ContractCompany__r.name,CommissionCurrency__c,
                        ContractCountry__c, ContractDate__c, Attribute__c, Status__c
                        FROM wb_CarInsurance__c
                        where ID =:CI_ID];
        
        CarInsurancedCars = [select id,LegalNumberofSeats__c  from wb_CarInsurancedCars__c where id =:CIC_ID];
        if  (CarInsurancedCars.id != null) {
                         PassengerDT = new List<wb_CI_PassangerRow>();
            
            for ( wb_CIC_Passenger__c p:[SELECT Psgr_CancelDate__c, 
                                         Psgr_CurrentEndDate__c, Psgr_CurrentStartDate__c, 
                                         Psgr_StdDriverSeatFee__c, Psgr_StdPassengerSeatFee__c, Psgr_AffiliationArea__c, 
                                         Psgr_CommodityName__c, Psgr_InitialStartDate__c, Psgr_InsuranceFee__c, 
                                         Psgr_InsuranceCompany__c, Psgr_InsurancePlan__c, 
                                         Psgr_Service__c, OP_CancelDate__c,
                                         OP_CurrentEndDate__c, OP_CurrentStartDate__c, 
                                         OP_CommodityName__c,  OP_Plan__c, OP_Service__c, 
                                         OP_StdDriverSeatFee__c, OP_StdPassengerSeatFee__c, OP_InsuranceFee__c,
                                         Name, CarInsurancedCar__c, Id , PassagerSeatInsurance__c ,DriverSeatInsurance__c,
                                         Psgr_Commission__c, OP_Commission__c, f_PsgrBillingAmount__c, f_OPBillingAmount__c 
                                         FROM wb_CIC_Passenger__c where CarInsurancedCar__c =:CarInsurancedCars.id]
                ) {
                    PassengerDT.add( new wb_CI_PassangerRow(CarInsurance.ContractCountry__c, 
                                                       CarInsurance.CommissionCurrency__c, 
                                                       Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                       p
                                                      )
                                   );
                }
        }
        PassengerDTSize = PassengerDT.size();
    }

}