unpackaged/objects/wb_CarInsurance__c.object
<CustomObject>
    <description>WellBe Car related Insurance Contract</description>
    <fields>
        <fullName>CommissionCurrency__c</fullName>
        <label>手数料通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>CompanyCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDistrict__c</fullName>
        <label>契約地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>自動車関連保険契約</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>自動車関連保険契約</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>CarInsuranceCar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>InsurancedCar</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>InsurancedCar_Cps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>Car_Cps_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cps_Commission__c</fullName>
        <label>（強制）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceAmount__c</fullName>
        <label>（強制）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（強制)サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>車保険 (（強制)サービス)</relationshipLabel>
        <relationshipName>Cps_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vlt_Commission__c</fullName>
        <label>（任意）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceAmount__c</fullName>
        <label>（任意）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（任意）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>Vlt_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Passenger__c.object
<CustomObject>
    <description>WellBe Car Passenger Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CIC_Psgr_Ins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>車両</label>
        <referenceTo>wb_Vehicle__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>Car_Psgr_Ins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP_Commission__c</fullName>
        <label>（OP）手数料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_CommodityName__c</fullName>
        <label>（OP）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_InsuranceFee__c</fullName>
        <label>（OP）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OP_Plan__c</fullName>
        <label>（OP）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（OP）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険</relationshipLabel>
        <relationshipName>CI_OptionService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Psgr_Commission__c</fullName>
        <label>（搭乗）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_CommodityName__c</fullName>
        <label>（搭乗）商品名称</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_InsuranceFee__c</fullName>
        <label>（搭乗）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Psgr_InsurancePlan__c</fullName>
        <label>（搭乗）保険プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psgr_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（搭乗）サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>搭乗保険 (（搭乗）サービス)</relationshipLabel>
        <relationshipName>CI_Psgr_Ins_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_OPBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(OP_RemainInsuranceFee__c),0, OP_RemainInsuranceFee__c) - OP_InsuranceFee__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（OP）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_PsgrBillingAmount__c</fullName>
        <formula>- ( IF (IsNull(Psgr_RemainInsuranceFee__c), 0, Psgr_RemainInsuranceFee__c) - Psgr_InsuranceFee__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>（搭乗）保険料差分</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>搭乗保険</label>
    <nameField>
        <label>搭乗保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_ReceivableServiceFee__c.object
<CustomObject>
    <description>WellBe Receivable</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>CI_Receivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>InsuracedCarReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>作成日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvoicingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>AccountReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OptionAmount__c</fullName>
        <label>OP商品費用</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OptionCommission__c</fullName>
        <label>OP手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OptionName__c</fullName>
        <label>OP商品名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceAmount__c</fullName>
        <label>主商品費用</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceCommission__c</fullName>
        <label>主商品手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <label>主商品名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>ServiceReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>総金額</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>売り上げ</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>売上番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Vehicle__c.object
<CustomObject>
    <description>WellBe Car Master for Insurances</description>
    <label>車両</label>
    <nameField>
        <label>登録番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_CarInsuranceBilling.cls
global with sharing class wb_CarInsuranceBilling {
    
    public List<BillingClass> BillingList;
    
    public class BillingClass{
        String ContractID {get; set;}
        Id ServiceID {get; set;}
  //      String Plan {get; set;}
 //       Decimal Amount {get; set;}
        Id ObjectId {get; set;}
 //       String ObjectName {get; set;}
        String Service {get; set;}
        Decimal ServiceAmount {get; set;}
        Decimal ServiceCommission {get; set;}
//        Id OptionID {get; set;}
        String Option {get; set;}
        Decimal OptionAmount {get; set;}
        Decimal OptionCommission {get; set;}
        Decimal TotalAmount {get; set;}
        //Decimal CommissionAmount {get; set;}
        
        public BillingClass(string c, 	Id objId,  string s, decimal sa, decimal scm,
                            string o, decimal oa, decimal ocm ){
                                this.ContractID =c;
                                this.ObjectId=objId;
                                // this.ServiceID = sid;
                                this.Service =s;
                                this.ServiceAmount =sa;
                                this.ServiceCommission = scm;
                                // this.OptionID = oid;
                                this.Option =o;
                                this.OptionAmount =oa;
                                 this.OptionCommission = ocm;
                                
                                if (sa == null)
                                    this.TotalAmount = oa;
                                else if ( oa == null )
                                    this.TotalAmount =sa;
                                else
                                    this.TotalAmount =sa +oa;
                            }
       
        public BillingClass(string c, 	Id objId,  string s, decimal sa,
                            string o, decimal oa ){
                                this.ContractID =c;
                                this.ObjectId=objId;
                                // this.ServiceID = sid;
                                this.Service =s;
                                this.ServiceAmount =sa;
                                // this.OptionID = oid;
                                this.Option =o;
                                this.OptionAmount =oa;
                                this.TotalAmount =sa +oa;
                            }

/*
        public BillingClass(string c,  string b, decimal p){
            this.ContractID =c;
            this.Service =b;
            this.ServiceAmount =p;            
            this.TotalAmount = p;
        }
*/        
        public BillingClass(string c,  string b, decimal p, decimal cm){
            this.ContractID =c;
            this.Service =b;
            this.ServiceAmount =p;            
            this.TotalAmount = p;
            this.ServiceCommission = cm;
        }

        
        public BillingClass(string c, Id ObjId, string b, decimal p){
            this.ContractID =c;
            this.ObjectId = ObjId;
            this.Service =b;
            this.ServiceAmount =p;            
            this.TotalAmount = p;
        } 
        
        public BillingClass(string c, Id ObjId, string b, decimal p, decimal cm){
            this.ContractID =c;
            this.ObjectId = ObjId;
            this.Service =b;
            this.ServiceAmount =p;            
            this.TotalAmount = p;
            this.ServiceCommission = cm;
        }
   
    }
    
    Webservice static string  Billing( ID c_id) {
        
        wb_CarInsurance__c 	carIns = [SELECT Status__c, ContractCountry__c, ContractDistrict__c, ContractCompany__c, CommissionCurrency__c, id 
                                      FROM wb_CarInsurance__c where id =:c_id]; 
        Date d;
        // Use the system date as billing date
        d = date.today();
        List<BillingClass> BillingList;
        
        
        BillingList = new List<BillingClass>();
        
        AggregateResult[] AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, 
                                 CarInsurancedCar__c,
                                // CarInsurancedCar__r.Car__r.name,         
                                 Psgr_Service__c, 
                                 Psgr_CommodityName__c , Psgr_InsurancePlan__c, 
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c, 
                                 sum(Psgr_InsuranceFee__c), sum(OP_InsuranceFee__c),
                                 sum(Psgr_Commission__c), sum(OP_Commission__c)
                                 FROM wb_CIC_Passenger__c
                                 where CarInsurancedCar__r.CarInsurance__c =:carIns.id
                                 group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c, //CarInsurancedCar__r.Car__r.name,  
                                 Psgr_Service__c, Psgr_CommodityName__c,Psgr_InsurancePlan__c ,
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c];
        
        for (AggregateResult SalesList : AgR) { 
            if (SalesList.get('OP_Service__c')!=null) {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),
                                                // (Id) (SalesList.get('Psgr_Service__c')),  
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0'),
                                                 (Decimal) SalesList.get('expr2'),
                                             //    (Id) (SalesList.get('OP_Service__c')),  
                                                 String.valueOf(SalesList.get('OP_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('OP_Plan__c')) ,   
                                                 (Decimal) SalesList.get('expr1'),
                                                 (Decimal) SalesList.get('expr3')
                                                ));
                
            }        
            else   {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),
                                              //   (Id) (SalesList.get('Psgr_Service__c')),  
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0'),
                                                 (Decimal) SalesList.get('expr2')
                                                ));
            }   
        }
        
        
        AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,
               sum(Cps_InsuranceAmount__c), 
               sum(Cps_Commission__c)
               FROM wb_CIC_Compulsory__c
               where CarInsurancedCar__r.CarInsurance__c =:carIns.id
               //and Cps_Service__c <> null
               group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c 
              having sum(Cps_InsuranceAmount__c) <> 0]; 
        for (AggregateResult SalesList : AgR) { 
            BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                             (Id) (SalesList.get('CarInsurancedCar__c')),  
                                             '強制' ,   
                                             (Decimal) SalesList.get('expr0'),
                                             (Decimal) SalesList.get('expr1')
                                            ));
        }
        
        AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,
               sum(Vlt_InsuranceAmount__c),
               sum(Vlt_Commission__c)              
               FROM wb_CIC_Compulsory__c
               where CarInsurancedCar__r.CarInsurance__c =:carIns.id
              // and Vlt_Service__c <> null
               and  Vlt_InsuranceAmount__c != null 
               group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c
              having sum(Vlt_InsuranceAmount__c) <> 0]; 
        for (AggregateResult SalesList : AgR) { 
            BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                             (Id) (SalesList.get('CarInsurancedCar__c')),
                                             '任意' ,   
                                             (Decimal) SalesList.get('expr0'),
                                             (Decimal) SalesList.get('expr1')
                                            ));
        }
        
        
        for ( wb_CarInsurancedCars__c Car:[select id from wb_CarInsurancedCars__c where CarInsurance__c =:carIns.id order by name ])
        {
            for (BillingClass BList : BillingList) { 
                if (BList.ObjectId == Car.id) {
                    wb_ReceivableServiceFee__c NewBilling = new wb_ReceivableServiceFee__c( Classification__c= '車保険',
                                                                                           Date__c=d, 
                                                                                           CarInsurance__c=carIns.id, 
                                                                                           CarInsurancedCar__c=BList.ObjectId,
                                                                                           Country__c = carIns.ContractCountry__c, 
                                                                                           District__c = carIns.ContractDistrict__c,
                                                                                           //  Service__c = BList.ServiceID,
                                                                                           ServiceName__c = BList.Service, 
                                                                                           Currency__c = carIns.CommissionCurrency__c,
                                                                                           ServiceAmount__c = BList.ServiceAmount,
                                                                                           ServiceCommission__c = BList.ServiceCommission,
                                                                                           //   Option__c = BList.OptionID,
                                                                                           OptionName__c = BList.Option,
                                                                                           OptionAmount__c = BList.OptionAmount,
                                                                                           OptionCommission__c = BList.OptionCommission,
                                                                                           TotalAmount__c = BList.TotalAmount,
                                                                                            
                                                                                           //ObjectName__c =  BList.ObjectName,
                                                                                           InvoicingCompany__c = carIns.ContractCompany__c
                                                                                          );   
                    
                    
                    try{
                        insert NewBilling;
                    } catch (System.QueryException e){
                        
                        System.debug(e);
                    }
                }
            }
        }
        
        
        carIns.Status__c = '確定';
        
        try{
            update carIns;
        } catch (System.QueryException e){
            System.debug(e);
        }
        
      
            return '契約の確定と売る上げ作成が完了';
      
    }
    
    
    public boolean  BillingAddtionCar( ID c_id) {
        wb_CarInsurancedCars__c car = [select id, CarInsurance__c 
                                       from wb_CarInsurancedCars__c where id =:c_id];
        
        wb_CarInsurance__c 	carIns = [SELECT Status__c, ContractCountry__c, ContractDistrict__c, ContractCompany__c, CommissionCurrency__c, id 
                                      FROM wb_CarInsurance__c where id =:car.CarInsurance__c]; 
        Date d;
        // Use the system date as billing date
        d = date.today();
        List<BillingClass> BillingList;
        
        
        BillingList = new List<BillingClass>();
        
        // Exchange Passanger
        AggregateResult[] AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, 
                                 CarInsurancedCar__c,         
                                 Psgr_Service__c, 
                                 Psgr_CommodityName__c , Psgr_InsurancePlan__c, 
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c,
                                 sum(f_PsgrBillingAmount__c) , 
                                 sum(f_OPBillingAmount__c),
                                 sum(Psgr_Commission__c),
								 sum(OP_Commission__c)                                 
                                 FROM wb_CIC_Passenger__c
                                 where CarInsurancedCar__c =:car.id
                                 and  Name  like '%e' // all car exchange record
                                 group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,  
                                 Psgr_Service__c, Psgr_CommodityName__c,Psgr_InsurancePlan__c ,
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c
                                 having sum(f_PsgrBillingAmount__c) <> 0 
                                 or   sum(f_OPBillingAmount__c) <> 0
                                ];
        
        for (AggregateResult SalesList : AgR) { 
            if (SalesList.get('OP_Service__c')!=null) {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                  (Id) (SalesList.get('CarInsurancedCar__c')),
                                              
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0'),
                                              (Decimal) SalesList.get('expr2'),
                                                 String.valueOf(SalesList.get('OP_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('OP_Plan__c')) ,   
                                                 (Decimal) SalesList.get('expr1'),
                                                   (Decimal) SalesList.get('expr3')
                                                ));
                
            }        
            else   {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),
                                                // (Id) (SalesList.get('Psgr_Service__c')),  
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0')
                                                ));
            }   
        }
        
        
        // Normal Passanger
         AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, 
                                 CarInsurancedCar__c,         
                                 Psgr_Service__c, 
                                 Psgr_CommodityName__c , Psgr_InsurancePlan__c, 
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c, 
                                 sum(Psgr_InsuranceFee__c), sum(OP_InsuranceFee__c),
                 				 sum(Psgr_Commission__c), sum(OP_Commission__c) 
                                 FROM wb_CIC_Passenger__c
                                 where CarInsurancedCar__c =:car.id
                                 and (not Name like '%e') // to skip all car exchange record
                                 group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,  
                                 Psgr_Service__c, Psgr_CommodityName__c,Psgr_InsurancePlan__c ,
                                 OP_Service__c, OP_CommodityName__c ,OP_Plan__c
                                 having sum(Psgr_InsuranceFee__c) <> 0 or  sum(OP_InsuranceFee__c) <> 0
                                ];
        
        for (AggregateResult SalesList : AgR) { 
            if (SalesList.get('OP_Service__c')!=null) {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                  (Id) (SalesList.get('CarInsurancedCar__c')),
                                              
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0'),
                                              (Decimal) SalesList.get('expr2'),
                                                 String.valueOf(SalesList.get('OP_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('OP_Plan__c')) ,   
                                                 (Decimal) SalesList.get('expr1'),
                                                 (Decimal) SalesList.get('expr3')
                                                ));
                
            }        
            else   {
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),
                                                // (Id) (SalesList.get('Psgr_Service__c')),  
                                                 String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                 String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                 (Decimal) SalesList.get('expr0'),
                                                   (Decimal) SalesList.get('expr2')
                                                ));
            }   
        }
        
         // Compulsory
        AgR = [SELECT CarInsurancedCar__r.CarInsurance__c,CarInsurancedCar__c, 
               sum(Cps_InsuranceAmount__c), sum(Cps_Commission__c)
               FROM wb_CIC_Compulsory__c
              // where CarInsurancedCar__r.CarInsurance__c =:car.id
               where CarInsurancedCar__c =:car.id
               //and Cps_Service__c <> null
               group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c
              having sum(Cps_InsuranceAmount__c) <> 0]; 
        for (AggregateResult SalesList : AgR) { 
            BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                             (Id) (SalesList.get('CarInsurancedCar__c')),  
                                             '強制' ,   
                                             (Decimal) SalesList.get('expr0'),
                                               (Decimal) SalesList.get('expr1')
                                            ));
        }
        //Voluntary
        AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,
               sum(Vlt_InsuranceAmount__c),
               sum(Vlt_Commission__c)
               FROM wb_CIC_Compulsory__c
               where CarInsurancedCar__c =:car.id
               //and Vlt_Service__c <> null
               and  Vlt_InsuranceAmount__c != null 
               group by CarInsurancedCar__r.CarInsurance__c , CarInsurancedCar__c
              having sum(Vlt_InsuranceAmount__c) <> 0]; 
        for (AggregateResult SalesList : AgR) { 
            BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                              (Id) (SalesList.get('CarInsurancedCar__c')), 
                                             '任意' ,   
                                             (Decimal) SalesList.get('expr0'),
                                             (Decimal) SalesList.get('expr1')
                                            ));
        }
        
 
        for (BillingClass BList : BillingList) { 
            
            wb_ReceivableServiceFee__c NewBilling = new wb_ReceivableServiceFee__c( Classification__c= '車保険',
                                                                                   Date__c=d, 
                                                                                   CarInsurance__c=carIns.id, 
                                                                                   CarInsurancedCar__c=BList.ObjectId,
                                                                                   Country__c = carIns.ContractCountry__c, 
                                                                                   District__c = carIns.ContractDistrict__c,
                                                                                   Service__c = BList.ServiceID,
                                                                                   ServiceName__c = BList.Service, 
                                                                                   Currency__c = carIns.CommissionCurrency__c,
                                                                                   ServiceAmount__c = BList.ServiceAmount,
                                                                                    ServiceCommission__c = BList.ServiceCommission,
                                                                                   //Option__c = BList.OptionID,
                                                                                   OptionName__c = BList.Option,
                                                                                   OptionAmount__c = BList.OptionAmount,
                                                                                   OptionCommission__c = BList.OptionCommission,
                                                                                   TotalAmount__c = BList.TotalAmount,
                                                                                  
                                                                                   // =  BList.ObjectName,
                                                                                   InvoicingCompany__c = carIns.ContractCompany__c );   
            
            
            try{
                insert NewBilling;
            } catch (System.QueryException e){
                
                System.debug(e);
                return false;
            }
        }
        /*
        carIns.Status__c = '確定';
        
        try{
            update carIns;
        } catch (System.QueryException e){
            System.debug(e);
            return false;
        }*/
        
        return true;
    }
    
    Webservice static string  CancelBilling( ID c_id) {
        
        if ( [select id from wb_CarInsurancedCars__c where ( Name like '%r%' or Name like '%A%') and CarInsurance__r.id =:c_id].size() == 0 ) {
            
            wb_CarInsurance__c carIns = [SELECT  Status__c, ContractCountry__c, ContractDistrict__c, ContractCompany__c, CommissionCurrency__c, Id 
                                         FROM wb_CarInsurance__c where id =:c_id]; 
            Date d;
            // Use the system date as billing date
            d = date.today();
            List<BillingClass> BillingList;
            
            BillingList = new List<BillingClass>();
            
            AggregateResult[] AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, 
                                     CarInsurancedCar__c ,    
                                     Psgr_Service__c, 
                                     Psgr_CommodityName__c , Psgr_InsurancePlan__c, 
                                     OP_Service__c, OP_CommodityName__c ,OP_Plan__c, 
                                     sum(Psgr_InsuranceFee__c), sum(OP_InsuranceFee__c) ,
                                     sum(Psgr_Commission__c), sum(OP_Commission__c) 
                                     FROM wb_CIC_Passenger__c
                                     where CarInsurancedCar__r.CarInsurance__c =:carIns.id
                                     group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,  
                                     Psgr_Service__c, Psgr_CommodityName__c,Psgr_InsurancePlan__c ,
                                     OP_Service__c, OP_CommodityName__c ,OP_Plan__c];
            
            
            
            for (AggregateResult SalesList : AgR) { 
                
                if (SalesList.get('OP_Service__c')!=null) {
                    BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                     (Id) (SalesList.get('CarInsurancedCar__c')),
                                                     // (Id) (SalesList.get('Psgr_Service__c')),  
                                                     String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                     String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                     -(Decimal) SalesList.get('expr0'),
                                                     -(Decimal) SalesList.get('expr2'),
                                                     // (Id) (SalesList.get('OP_Service__c')),  
                                                     String.valueOf(SalesList.get('OP_CommodityName__c')) +
                                                     String.valueOf(SalesList.get('OP_Plan__c')) ,   
                                                     -(Decimal) SalesList.get('expr1'),
                                                     -(Decimal) SalesList.get('expr3')
                                                    ));
                    
                }        
                else   {
                    BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                     (Id) (SalesList.get('CarInsurancedCar__c')),
                                                     //(Id) (SalesList.get('Psgr_Service__c')),  
                                                     String.valueOf(SalesList.get('Psgr_CommodityName__c')) +
                                                     String.valueOf(SalesList.get('Psgr_InsurancePlan__c')) ,   
                                                     -(Decimal) SalesList.get('expr0'),
                                                     -(Decimal) SalesList.get('expr2')
                                                    ));
                }   
            }
            
            
            AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,
                   sum(Cps_InsuranceAmount__c),
                   sum(Cps_Commission__c)
                   FROM wb_CIC_Compulsory__c
                   where CarInsurancedCar__r.CarInsurance__c =:carIns.id
                   and Cps_Service__c <> null
                   group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c ]; 
            for (AggregateResult SalesList : AgR) { 
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),  
                                                 '強制' ,   
                                                 - (Decimal) SalesList.get('expr0'),
                                                 - (Decimal) SalesList.get('expr1')
                                                ));
            }
            
            AgR = [SELECT CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c,
                   sum(Vlt_InsuranceAmount__c), sum(Vlt_Commission__c)
                   FROM wb_CIC_Compulsory__c
                   where CarInsurancedCar__r.CarInsurance__c =:carIns.id
                   and  Vlt_Service__c <> null and Vlt_InsuranceAmount__c <> null 
                   group by CarInsurancedCar__r.CarInsurance__c, CarInsurancedCar__c ]; 
            for (AggregateResult SalesList : AgR) { 
                BillingList.add(new BillingClass(String.valueOf(SalesList.get('CarInsurance__c')),
                                                 (Id) (SalesList.get('CarInsurancedCar__c')),  
                                                 '任意' ,   
                                                 - (Decimal) SalesList.get('expr0'),
                                                 - (Decimal) SalesList.get('expr1')
                                                ));
            }
            
            
            for ( wb_CarInsurancedCars__c Car:[select id from wb_CarInsurancedCars__c where CarInsurance__c =:carIns.id order by name ]) {  
                for (BillingClass BList : BillingList) { 
                    if (BList.ObjectId == Car.id) {
                        wb_ReceivableServiceFee__c NewBilling = new wb_ReceivableServiceFee__c( Classification__c= '車保険',
                                                                                               Date__c=d, 
                                                                                               CarInsurance__c=carIns.id, 
                                                                                               CarInsurancedCar__c=BList.ObjectId,
                                                                                               Country__c = carIns.ContractCountry__c, 
                                                                                               District__c = carIns.ContractDistrict__c,
                                                                                               // Service__c = BList.ServiceID,
                                                                                               ServiceName__c = BList.Service, 
                                                                                               Currency__c = carIns.CommissionCurrency__c,
                                                                                               ServiceAmount__c = BList.ServiceAmount,
                                                                                               ServiceCommission__c = BList.ServiceCommission,
                                                                                               //Option__c = BList.OptionID,
                                                                                               // OptionName__c = BList.Option,
                                                                                               OptionAmount__c = BList.OptionAmount,
                                                                                               OptionCommission__c = BList.OptionCommission,
                                                                                               TotalAmount__c = BList.TotalAmount,
                                                                                               
                                                                                               // =  BList.ObjectName,
                                                                                               InvoicingCompany__c = carIns.ContractCompany__c );   
                        
                        
                        
                        try{
                            insert NewBilling;
                        } catch (System.QueryException e){
                            
                            System.debug(e);
                        }
                    }
                }
            }
            
            carIns.Status__c = 'キャンセル';
            
            try{
                update carIns;
                
            } catch (System.QueryException e){
                System.debug(e);
            }
            
            return '契約のキャンセルが完了';
        } else
        {
            return '増車、入れ替えなどの契約をキャンセルできない';
        }
    }
    
}