unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>CarInsuranceCar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>InsurancedCar_Cps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_CIC_Compulsory_redirect.cls
public class wb_CIC_Compulsory_redirect {
    ApexPages.StandardController stdController;
    public wb_CIC_Compulsory__c wb_CIC_Compulsory {get;set;}
    
    public wb_CIC_Compulsory_redirect(ApexPages.StandardController stdController){
        this.stdController = stdController;
        wb_CIC_Compulsory = (wb_CIC_Compulsory__c) stdController.getRecord();
        wb_CIC_Compulsory = [select id, CarInsurancedCar__c, CarInsurancedCar__r.CarInsurance__c from wb_CIC_Compulsory__c where id =: wb_CIC_Compulsory.id ];
    }
    
    public PageReference redirect() {
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        return new PageReference(sfdcBaseURL+'/apex/wb_CarInsurance?Id=' + wb_CIC_Compulsory.CarInsurancedCar__r.CarInsurance__c);
    }
    
    
}