unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>対象車</relationshipLabel>
        <relationshipName>CarInsuranceCar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_CarInsurancedCars_redirect.cls
public class wb_CarInsurancedCars_redirect {
    ApexPages.StandardController stdController;
    public wb_CarInsurancedCars__c wb_CarInsurancedCars {get;set;}
    public wb_CarInsurancedCars_redirect(ApexPages.StandardController stdController){
        this.stdController = stdController;
        wb_CarInsurancedCars = (wb_CarInsurancedCars__c) stdController.getRecord();
        wb_CarInsurancedCars = [select id, CarInsurance__c from wb_CarInsurancedCars__c where id =: wb_CarInsurancedCars.id ];
    }
    
    public PageReference redirect() {
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        return new PageReference(sfdcBaseURL+'/apex/wb_CarInsurance?Id=' + wb_CarInsurancedCars.CarInsurance__c);
    }
    
}