unpackaged/objects/wb_CarInsurance__c.object
<CustomObject>
    <description>WellBe Car related Insurance Contract</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>属性</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会員企業</fullName>
                </value>
                <value>
                    <fullName>非会員企業</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CommissionCurrency__c</fullName>
        <label>手数料通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>自動車関連保険契約</relationshipLabel>
        <relationshipName>CompanyCarInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>自動車関連保険契約</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>自動車関連保険契約</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_CarInsurancedCars__c.object
<CustomObject>
    <description>WellBe Insuranced Cars</description>
    <fields>
        <fullName>LegalNumberofSeats__c</fullName>
        <label>法定座席数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>対象車</label>
    <nameField>
        <label>対象車番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_CIC_Compulsory__c.object
<CustomObject>
    <description>WellBe Car Compulsory &amp; Voluntary Insurances</description>
    <fields>
        <fullName>CarInsurancedCar__c</fullName>
        <label>対象車</label>
        <referenceTo>wb_CarInsurancedCars__c</referenceTo>
        <relationshipLabel>車保険</relationshipLabel>
        <relationshipName>InsurancedCar_Cps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cps_AfterDeathImpediment__c</fullName>
        <label>（強制）死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_CancelDate__c</fullName>
        <label>（強制）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CancelReason__c</fullName>
        <label>（強制）保険解約理由</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_CommissionRate__c</fullName>
        <label>（強制）手数料率</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Commission__c</fullName>
        <label>（強制）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Currency__c</fullName>
        <label>（強制）保険通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentEndDate__c</fullName>
        <label>（強制）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_CurrentStartDate__c</fullName>
        <label>（強制）保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceAmount__c</fullName>
        <label>（強制）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_InsuranceCompany__c</fullName>
        <label>（強制）保険会社名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_MedicalCost__c</fullName>
        <label>（強制）医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathImpediment__c</fullName>
        <label>（強制）無責任死亡後遺障害</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtAfterDeathMedicalCost__c</fullName>
        <label>（強制）無責任医療費用</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_NoLbtPropertyLoss__c</fullName>
        <label>（強制）無責任財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_PolicyNumber__c</fullName>
        <label>（強制）証券番号</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cps_PropertyLoss__c</fullName>
        <label>（強制）財産損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cps_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>（強制)サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>車保険 (（強制)サービス)</relationshipLabel>
        <relationshipName>Cps_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIt_ScratchDamage__c</fullName>
        <label>（任意）鈎損</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VIt_VehicleDamage__c</fullName>
        <label>（任意）車両損失</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VIt_VehicleTheft__c</fullName>
        <label>（任意）車両盗難</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_3rdPartyDamage__c</fullName>
        <label>（任意）第三者賠償</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_CancelDate__c</fullName>
        <label>（任意）保険解約日 （24時迄）</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_CancelReason__c</fullName>
        <label>（任意）保険解約理由</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_CommissionRate__c</fullName>
        <label>（任意）手数料率</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Commission__c</fullName>
        <label>（任意）手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Currency__c</fullName>
        <label>（任意）保険通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_DriverInjury__c</fullName>
        <label>（任意）車上人責任（運転）</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_EndDate__c</fullName>
        <label>（任意）保険終期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_GlassBreakage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>（任意）ガラス単独破壊</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceAmount__c</fullName>
        <label>（任意）保険料</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_InsuranceCompany__c</fullName>
        <label>（任意）保険会社名</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_OtherItems__c</fullName>
        <label>（任意）他の保険項目</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_PassengerInjury__c</fullName>
        <label>（任意）車上人責任（搭乗）</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_PolicyNumber__c</fullName>
        <label>（任意）証券番号</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_PsgrPersonalAccident__c</fullName>
        <label>（任意）搭乗者意外保険</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vlt_Remark__c</fullName>
        <label>（任意）備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlt_Selfburning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>（任意）車体自燃</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vlt_StartDate__c</fullName>
        <label>（任意）保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vlt_Submersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>（任意）水没険</label>
        <type>Checkbox</type>
    </fields>
    <label>車保険</label>
    <nameField>
        <label>車保険番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_CIC_CompulsoryDT.cls
public class wb_CIC_CompulsoryDT {
    ApexPages.StandardController stdController;
    public id CI_ID {get;set;}
    public string CIC_ID {get;set;}
    
    public wb_CarInsurance__c CarInsurance {get;set;}
    public wb_CarInsurancedCars__c CarInsurancedCars {get;set;}
    
    public List<wb_CI_CompulsoryRow> CompulsoryDT {get;set;}
    public integer CompulsoryDTSize {get;set;}
    
    public wb_CIC_CompulsoryDT(ApexPages.StandardController stdController){
        this.stdController = stdController;
        CI_ID = apexpages.currentpage().getparameters().get('id');
        CIC_ID = apexpages.currentpage().getparameters().get('pv0');
        CarInsurance = [SELECT Name, Id, ContractCompany__c,ContractCompany__r.name,CommissionCurrency__c,
                        ContractCountry__c, ContractDate__c, Attribute__c, Status__c
                        FROM wb_CarInsurance__c
                        where ID =:CI_ID];
      
        CarInsurancedCars = [select id,LegalNumberofSeats__c  from wb_CarInsurancedCars__c where id =:CIC_ID];
        
        if  (CarInsurancedCars.id != null) {
            CompulsoryDT = new List<wb_CI_CompulsoryRow>();
            for ( wb_CIC_Compulsory__c cps:[SELECT Cps_PropertyLoss__c, Cps_PolicyNumber__c, Cps_NoLbtPropertyLoss__c, Cps_NoLbtAfterDeathImpediment__c, 
                                            Cps_NoLbtAfterDeathMedicalCost__c, Cps_AfterDeathImpediment__c, Cps_CommissionRate__c, 
                                            Cps_Commission__c, 
                                            Cps_MedicalCost__c, Cps_CancelReason__c, Cps_CancelDate__c, Cps_CurrentEndDate__c, Cps_InsuranceAmount__c, 
                                            Cps_CurrentStartDate__c, Cps_InsuranceCompany__c, Cps_Service__c, VIt_ScratchDamage__c, VIt_VehicleTheft__c, 
                                            VIt_VehicleDamage__c, Vlt_DriverInjury__c, Vlt_PassengerInjury__c, Vlt_PolicyNumber__c, Vlt_3rdPartyDamage__c, 
                                            Vlt_PsgrPersonalAccident__c, Vlt_CommissionRate__c, 
                                            Vlt_Commission__c, Vlt_Currency__c, Vlt_CancelReason__c, 
                                            Vlt_CancelDate__c, Vlt_EndDate__c, Vlt_InsuranceAmount__c, Vlt_StartDate__c, Vlt_InsuranceCompany__c, 
                                            Vlt_GlassBreakage__c, Vlt_OtherItems__c, Name, CarInsurancedCar__c, id ,
                                            Cps_Currency__c, Vlt_Selfburning__c, Vlt_Submersion__c, Vlt_Remark__c  
                                            FROM wb_CIC_Compulsory__c where CarInsurancedCar__c =:CarInsurancedCars.id]) {
                                                CompulsoryDT.add( new wb_CI_CompulsoryRow(CarInsurance.ContractCountry__c, 
                                                                                          CarInsurance.CommissionCurrency__c,
                                                                                          Integer.valueof( CarInsurancedCars.LegalNumberofSeats__c),
                                                                                          cps
                                                                                         )
                                                                );
                                            }
        }
        
        CompulsoryDTSize = CompulsoryDT.size();
    }
}