unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MemberHistory__c.object
<CustomObject>
    <description>WellBe Membership History</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberType__c</fullName>
        <label>会員タイプ</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MembershipDetailHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReplacedWith__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>置き換え</label>
        <referenceTo>wb_MemberHistory__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MembershipHistoryReplacement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_effectiveness__c</fullName>
        <formula>if(IsBlank(ReplacedWith__c),
if( AND(MembershipStartDate__c &lt;= TODAY(),TODAY()&lt;=EffectiveUntil__c ),TRUE,FALSE ),
FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>member__c</fullName>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MemberHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員履歴</label>
    <nameField>
        <label>会員履歴番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会社</fullName>
                </value>
                <value>
                    <fullName>個人</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>分類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>新規</fullName>
                </value>
                <value>
                    <fullName>継続</fullName>
                </value>
                <value>
                    <fullName>追加</fullName>
                </value>
                <value>
                    <fullName>交替</fullName>
                </value>
                <value>
                    <fullName>変更</fullName>
                </value>
                <value>
                    <fullName>解約変更</fullName>
                </value>
                <value>
                    <fullName>移行</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MemberNo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Account_MDContractMember.cls
public class wb_Account_MDContractMember {
    private ApexPages.StandardController standardController;
    public Account theAccount {get; set;}
    
    public List<wb_Member__c> theContractedMembers {get; set;}
    public wb_utility_datapaging ContractedMembersPage {get; set;}
    
    public List<wb_MembershipDetail__c> theContractedMembersFamily {get; set;}
    
    public List<wb_MemberHistory__c> theContractedMemberHistories {get; set;}
    public wb_utility_datapaging ContractedMemberHistoryPage {get; set;}
    
    public wb_Account_MDContractMember(ApexPages.StandardController stdController){
        this.standardController = stdController;
        theAccount = (Account) stdController.getRecord();
        List<Id> MDContractID = new List<Id>();
        
        for ( wb_Membership__c m:[SELECT Id FROM wb_Membership__c
                                  where ContractCompany__c =:theAccount.id and Status__c ='確定']){
                                      MDContractID.add(m.id);
                                  }
        theContractedMembers = new List<wb_Member__c>();
        
        List<Id> effectiveMIds = new List<Id>();
        for (wb_MemberHistory__c em:[SELECT  member__c 
                                           FROM wb_MemberHistory__c 
                                           where  MembershipDetail__r.Membership__r.Status__c ='確定' and
                                           ( MembershipDetail__r.Membership__r.id =:MDContractID 
                                            or MembershipDetail__r.WorkingCompany__c =:theAccount.id)
                                           and f_effectiveness__c = true
                                          // and ReplacedWith__c = null
                                          ])
        {
            effectiveMIds.add(em.member__c);
        }
        
        theContractedMembers = [SELECT id, Name, EndDate__c,  WorkingCompany__c,WorkingCompany__r.name,Individual__c,
                                Individual__r.name, MembershipDetail__c, 
                                MembershipDetail__r.Type__c, 
                                MembershipDetail__r.Membership__r.Id, MembershipDetail__r.Membership__r.name,
                                MembershipDetail__r.MembershipEndDate__c,
                                MembershipDetail__r.MemberNo__c
                                FROM wb_Member__c
                                where Id =:effectiveMIds];
        //                        where MembershipDetail__r.Membership__r.Status__c ='確定' and
       //                         ( MembershipDetail__r.Membership__r.id =:MDContractID 
       //                         or WorkingCompany__c =:theAccount.id)];
    
        system.debug(MDContractID);
        List<Id> FamilyTypeID = new List<Id>(); 
        for (wb_Member__c m:theContractedMembers){
            if (m.MembershipDetail__r.Type__c =='家族'){
                FamilyTypeID.add(m.MembershipDetail__c);
            }
        }
        
        if (FamilyTypeID.size() > 0) {
            theContractedMembersFamily = [select Individual__c, Individual__r.name, MemberNo__c, ParentDetail__c
                                          from wb_MembershipDetail__c where ParentDetail__c =:FamilyTypeID];
        }
        
        List<Id> MemberID = new List<Id>();
        for ( wb_Member__c m:theContractedMembers){
            MemberID.add(m.id);
        }
        if (MemberID.size() > 0)
        /*    
        theContractedMemberHistories = [SELECT MemberNo__c, Name, MembershipDetail__c, MembershipDetail__r.name,
                                        MemberType__c, member__c, CancellationDate__c, MembershipEndDate__c, 
                                        MembershipStartDate__c, Classification__c 
                                        FROM wb_MemberHistory__c where member__c =:MemberID]; */
        theContractedMemberHistories = [SELECT MemberNo__c, Name, MembershipDetail__c, 
                                        MembershipDetail__r.MembershipPlan__c, MembershipDetail__r.Type__c,
                                        MemberType__c, member__c, CancellationDate__c, MembershipEndDate__c, 
                                        MembershipStartDate__c,MembershipStopDate__c, Classification__c 
                                        FROM wb_MemberHistory__c where member__c =:MemberID
                                        order by id desc ];

        if (theContractedMembersFamily != null) {
            system.debug(theContractedMembers.size() + ',' + theContractedMembersFamily.size());
            ContractedMembersPage = new wb_utility_datapaging(theContractedMembers, theContractedMembersFamily);
        } else {
            system.debug(theContractedMembers.size());
             ContractedMembersPage = new wb_utility_datapaging(theContractedMembers, null);
            //ContractedMembersPage = new wb_utility_datapaging(theContractedMembers);
        }
    }
    public string theHighlightedMember {get; set;}
    public void GetMemberHistory(){
        List<wb_MemberHistory__c> theHistory = new List<wb_MemberHistory__c>();
        if (theHighlightedMember.length() > 0){
            //boolean found = false;
            wb_Member__c theMember;
            for ( integer i = 0; i < theContractedMembers.size(); i++ ){
                if ( theContractedMembers[i].MembershipDetail__r.MemberNo__c == theHighlightedMember){
                    theMember =  theContractedMembers[i];
                    i = theContractedMembers.size();
                }
            }
            for (wb_MemberHistory__c h:theContractedMemberHistories){
                if(h.member__c == theMember.id)
                    theHistory.add(h);
            }
            
        }
        
         ContractedMemberHistoryPage = new wb_utility_datapaging(theHistory);
    }
    
}