unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MedicalInsuranceDetail__c.object
<CustomObject>
    <fields>
        <fullName>HandlingBy__c</fullName>
        <label>取扱区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WB扱い</fullName>
                </value>
                <value>
                    <fullName>WB以外</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>医療保険対象</relationshipLabel>
        <relationshipName>IndividualMedicalInsurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InsuranceCompany__c</fullName>
        <label>保険会社名称</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確認</fullName>
                </value>
                <value>
                    <fullName>保険なし</fullName>
                </value>
                <value>
                    <fullName>AIU保険会社</fullName>
                </value>
                <value>
                    <fullName>JI傷害火災保険株式会社</fullName>
                </value>
                <value>
                    <fullName>東京海上日動火災保険株式会社</fullName>
                </value>
                <value>
                    <fullName>富士火災海上保険株式会社</fullName>
                </value>
                <value>
                    <fullName>日新火災海上保険株式会社</fullName>
                </value>
                <value>
                    <fullName>朝日火災海上保険株式会社</fullName>
                </value>
                <value>
                    <fullName>共栄火災海上保険株式会社</fullName>
                </value>
                <value>
                    <fullName>セゾン自動車火災保険株式会社</fullName>
                </value>
                <value>
                    <fullName>セコム損害保険株式会社</fullName>
                </value>
                <value>
                    <fullName>ニッセイ同和損害保険株式会社</fullName>
                </value>
                <value>
                    <fullName>あいおい損害保険株式会社</fullName>
                </value>
                <value>
                    <fullName>日本興亜損害保険株式会社</fullName>
                </value>
                <value>
                    <fullName>ニッセイ同和損害保険株式会社(JI)</fullName>
                </value>
                <value>
                    <fullName>日立 Health Care Program</fullName>
                </value>
                <value>
                    <fullName>エース損害保険株式会社</fullName>
                </value>
                <value>
                    <fullName>三井住友海上火災保険株式会社</fullName>
                </value>
                <value>
                    <fullName>三井住友海上火災保険（香港)有限公司</fullName>
                </value>
                <value>
                    <fullName>株式会社損害保険ジャパン</fullName>
                </value>
                <value>
                    <fullName>日本財産保険(香港)有限公司</fullName>
                </value>
                <value>
                    <fullName>AIG INSURANCE HONG KONG LTD</fullName>
                </value>
                <value>
                    <fullName>東京海上火災保険（香港）有限公司</fullName>
                </value>
                <value>
                    <fullName>ニュ－インディア保険会社</fullName>
                </value>
                <value>
                    <fullName>平安養老保険</fullName>
                </value>
                <value>
                    <fullName>三井住友海上火災保険公司　上海分公司</fullName>
                </value>
                <value>
                    <fullName>三菱東京UFJ Health Care Program</fullName>
                </value>
                <value>
                    <fullName>長生人寿保険有限公司</fullName>
                </value>
                <value>
                    <fullName>三井住友海上火災有限公司　広州分公司</fullName>
                </value>
                <value>
                    <fullName>日本興亜保険（亜洲）有限公司</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsuranceCurrency__c</fullName>
        <label>保険通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InsuranceEndDate__c</fullName>
        <label>保険満期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InsurancePlan__c</fullName>
        <label>保険プラン</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SB</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SD</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>新A</fullName>
                </value>
                <value>
                    <fullName>新B</fullName>
                </value>
                <value>
                    <fullName>新C</fullName>
                </value>
                <value>
                    <fullName>新D</fullName>
                </value>
                <value>
                    <fullName>新E</fullName>
                </value>
                <value>
                    <fullName>新F</fullName>
                </value>
                <value>
                    <fullName>新G</fullName>
                </value>
                <value>
                    <fullName>新H</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsuranceStartDate__c</fullName>
        <label>保険始期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MedicalInsurance__c</fullName>
        <label>医療保険</label>
        <referenceTo>wb_MedicalInsurance__c</referenceTo>
        <relationshipLabel>医療保険対象</relationshipLabel>
        <relationshipName>MedicalInsuranceDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MedicalSettlement__c</fullName>
        <label>医療費決済方法</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>海外旅行傷害保険</fullName>
                </value>
                <value>
                    <fullName>中国医療傷害保険</fullName>
                </value>
                <value>
                    <fullName>ベトナム医療障害保険</fullName>
                </value>
                <value>
                    <fullName>クレジットカード付帯保険</fullName>
                </value>
                <value>
                    <fullName>現金</fullName>
                </value>
                <value>
                    <fullName>会社積立</fullName>
                </value>
                <value>
                    <fullName>旅行総合保険</fullName>
                </value>
                <value>
                    <fullName>立て替え保証</fullName>
                </value>
                <value>
                    <fullName>Medi-X</fullName>
                </value>
                <value>
                    <fullName>Health Care Program</fullName>
                </value>
                <value>
                    <fullName>未確認</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PolicyNumber__c</fullName>
        <label>証券番号</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>優先順</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>医療備考</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StorageLocation__c</fullName>
        <label>保管場所</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>医療保険対象</label>
    <nameField>
        <label>医療保険対象番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Individual_MedicalInsuranceDetail.cls
public class wb_Individual_MedicalInsuranceDetail {
    private ApexPages.StandardController standardController;
    public wb_Individual__c Individual {get;set;}
    
    public List<wb_MedicalInsuranceDetail__c> MedicalInsuranceDetail {get;set;}
    
    public List<Attachment> AllAttachments {get;set;}
    
    public List<aRow> TblMedicalInsuranceDetail { get; set; }
    public class aRow {
        public wb_MedicalInsuranceDetail__c theMedicalInsuranceDetail { get; set; }
        public List<Attachment> Attachments {get;set;}
        public aRow(wb_MedicalInsuranceDetail__c d) {
            theMedicalInsuranceDetail = d;
            Attachments = new List<Attachment>();
        }
    }
    
    public wb_Individual_MedicalInsuranceDetail(ApexPages.StandardController stdController){
        this.standardController = stdController;
        Individual = (wb_Individual__c) stdController.getRecord();
        MedicalInsuranceDetail = [select id, Name, InsurancePlan__c, StorageLocation__c, MedicalInsurance__c,Priority__c,
                                  InsuranceStartDate__c,InsuranceEndDate__c,MedicalSettlement__c,InsuranceCurrency__c,
                                  InsuranceCompany__c,HandlingBy__c,PolicyNumber__c, Remark__c
                                  from wb_MedicalInsuranceDetail__c where Individual__c =:Individual.id];
        
        List<Id> MI_Id = new  List<Id>();
        TblMedicalInsuranceDetail = new List<aRow>();
        for( wb_MedicalInsuranceDetail__c d:MedicalInsuranceDetail){
            MI_Id.add(d.MedicalInsurance__c);
            TblMedicalInsuranceDetail.add( new aRow(d));
        }
        
        AllAttachments = [SELECT id, ParentId ,name
                       FROM Attachment where ParentId =:MI_Id];
        
        
       for( aRow r:TblMedicalInsuranceDetail){
           for ( Attachment a:AllAttachments){
               if (r.theMedicalInsuranceDetail.MedicalInsurance__c ==  a.ParentId )
                   r.Attachments.add(a);
           }
       }
    }

}