unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>If(ISBLANK(Parent__c),
Member__r.f_Classification__c,
If(ISBLANK(Parent__r.Member__r.f_Classification__c),
&apos;&apos;,
Parent__r.Member__r.f_Classification__c + &apos;家族&apos;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>f_ContractCompany__c</fullName>
        <formula>Member__r.f_ContractCompany__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>契約会社</label>
        <type>Text</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Old_MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>旧会員番号</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_Classification__c</fullName>
        <formula>if(IsBlank(r_EffectiveUntil__c),&apos;&apos;,if(r_EffectiveUntil__c&gt;= TODAY(),&apos;会員&apos;,&apos;退会者&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>区分</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>f_ContractCompany__c</fullName>
        <formula>MembershipDetail__r.Membership__r.ContractCompany__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>契約会社</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>f_MemberNo__c</fullName>
        <formula>MembershipDetail__r.MemberNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>会員番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>r_EffectiveUntil__c</fullName>
        <label>有効終了日</label>
        <summarizedField>wb_MemberHistory__c.EffectiveUntil__c</summarizedField>
        <summaryForeignKey>wb_MemberHistory__c.member__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MemberHistory__c.object
<CustomObject>
    <description>WellBe Membership History</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberType__c</fullName>
        <label>会員タイプ</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MembershipDetailHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReplacedWith__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>置き換え</label>
        <referenceTo>wb_MemberHistory__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MembershipHistoryReplacement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_effectiveness__c</fullName>
        <formula>if(IsBlank(ReplacedWith__c),
if( AND(MembershipStartDate__c &lt;= TODAY(),TODAY()&lt;=EffectiveUntil__c ),TRUE,FALSE ),
FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>member__c</fullName>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MemberHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員履歴</label>
    <nameField>
        <label>会員履歴番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>CancellationDate__c</fullName>
        <label>キャンセル日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>分類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>新規</fullName>
                </value>
                <value>
                    <fullName>継続</fullName>
                </value>
                <value>
                    <fullName>追加</fullName>
                </value>
                <value>
                    <fullName>交替</fullName>
                </value>
                <value>
                    <fullName>変更</fullName>
                </value>
                <value>
                    <fullName>解約変更</fullName>
                </value>
                <value>
                    <fullName>移行</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MemberNo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Individual_Membership.cls
public class wb_Individual_Membership {
    private ApexPages.StandardController standardController;
    public wb_Individual__c theIndividual {get;set;}
    
    public List<wb_Member__c> theMembers {get; set;}
    public wb_utility_datapaging MembersPage {get; set;}
    
    public List<wb_MemberHistory__c> theMemberHistories {get; set;}
    //public List<wb_MemberHistory__c> MemberHistories {get; set;}
    public wb_utility_datapaging MemberHistoryPage {get; set;}
    public boolean effective  {get; set;}     
    public wb_Individual_Membership(ApexPages.StandardController stdController){
        this.standardController = stdController;
        theIndividual = (wb_Individual__c) stdController.getRecord();
        system.debug('theIndividual:' + theIndividual.id);
        /*
        AggregateResult[] MemberEffectiveness = [SELECT  member__r.name memseq, MembershipDetail__r.name conseq, f_effectiveness__c, count(Id)
                                                 FROM wb_MemberHistory__c 
                                                 where  member__r.Individual__c =:theIndividual.Id and f_effectiveness__c = true
                                                 and ReplacedWith__c = null
                                                 group by member__r.name, MembershipDetail__r.name, f_effectiveness__c ];
   
      */
            
        theMembers = [SELECT id, Name,  WorkingCompany__c, WorkingCompany__r.name, f_ContractCompany__c, 
                      MembershipDetail__r.Membership__r.ContractCompany__c,
                      Individual__c, Old_MemberNo__c,
                      Individual__r.name, MembershipDetail__c, 
                      f_MemberNo__c, r_EffectiveUntil__c, f_Classification__c,
                      MembershipDetail__r.Type__c, 
                      MembershipDetail__r.Membership__r.Id, MembershipDetail__r.Membership__r.name,
                      MembershipDetail__r.MembershipEndDate__c,
                      MembershipDetail__r.MemberNo__c
                      FROM wb_Member__c
                      where MembershipDetail__r.Membership__r.Status__c ='確定' and
                      Individual__c =:theIndividual.Id];
        
        MembersPage = new wb_utility_datapaging(theMembers);
        
        List<Id> MemberID = new List<Id>();
        for ( wb_Member__c m:theMembers){
            MemberID.add(m.id);
        }
        if (MemberID.size() > 0)
            
            theMemberHistories = [SELECT MemberNo__c, Name, MembershipDetail__c, 
                                  MembershipDetail__r.MembershipPlan__c, MembershipDetail__r.Type__c,
                                  MemberType__c, member__c, CancellationDate__c, MembershipEndDate__c, 
                                  MembershipStartDate__c,MembershipStopDate__c, Classification__c 
                                  FROM wb_MemberHistory__c where member__c =:MemberID
                                  order by id desc ];
        
        List<wb_MemberHistory__c> theHistory = new List<wb_MemberHistory__c>();
        if (theMembers.size() > 0  ) {
            for (wb_MemberHistory__c h:theMemberHistories){
                if(h.member__c == theMembers[0].id)
                    theHistory.add(h);
            }
        }
         MemberHistoryPage = new wb_utility_datapaging(theHistory);
    }
    //theHighlightedMember
    public string theHighlightedMember {get; set;}
    public void GetMemberHistory(){
        system.debug(theHighlightedMember +',' + theMembers.size());
        List<wb_MemberHistory__c> theHistory = new List<wb_MemberHistory__c>();
        if (theHighlightedMember.length() > 0){
            //boolean found = false;
            wb_Member__c theMember;
            for ( integer i = 0; i < theMembers.size(); i++ ){
                if ( theMembers[i].name == theHighlightedMember){
                    theMember =  theMembers[i];
                    i = theMembers.size();
                }
            }
            
            if (theMember != null ) {
                system.debug(theMember);
                for (wb_MemberHistory__c h:theMemberHistories){
                    if(h.member__c == theMember.id)
                        theHistory.add(h);
                }
            }
        }
        
        MemberHistoryPage = new wb_utility_datapaging(theHistory);
    }
    
}