unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>BillingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>支払会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約（支払い）</relationshipLabel>
        <relationshipName>BillingMembershipContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>会員氏名</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_MDContract.cls
@RestResource(urlMapping='/MDContract/*')
global with sharing class wb_soap_MDContract {
    
    global class ContractMember{
        global string Id; 
        global string WorkingCompany;
        global string MemberNo;
        global string MemberName;
        global string Plan;
        ContractMember(wb_MembershipDetail__c d){
            Id = d.Id;
            WorkingCompany = d.WorkingCompany__r.name;
            MemberNo= d.MemberNo__c;
            if (d.MemberName__c != null)
                MemberName=d.MemberName__c;
            else 
                MemberName = d.Individual__r.name;
            Plan= d.MembershipPlan__c;
        }
    }
    
     global class Contract{
         global string Id; 
         global string ContractCompany;
         global string BillingCompany;
         global string PaymentCurrency;
         global string StartDate;
         global string EndDate;
         global List<ContractMember> Members;
         
         Contract(wb_Membership__c H, List<wb_MembershipDetail__c> D){
             Id = H.Id;
             ContractCompany = H.ContractCompany__r.name;
             BillingCompany = H.BillingCompany__r.name;
             PaymentCurrency = H.Currency__c;
             Members = new List<ContractMember>();
             for (wb_MembershipDetail__c dd:D){
                 Members.add( new ContractMember(dd));
             }
         }
     }
    
    @HttpGet
    global static List<Contract> getContract() {
        
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String req = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        system.debug('req:'+req);
        if ( req.indexOf('=') > 1){
            string reqType = req.left( req.indexOf('='));
            string reqInfo = req.right(req.length() - req.indexOf('=') - 1);
            if ( reqType=='CONTRACTCOMPANYID')
                return GetContracts(Id.valueOf(reqInfo));
            else 
                return null;
        } else
            return null;            
        
        
    }
    
    public static List<Contract> GetContracts(Id CompID){
        List<Contract> Contracts = new List<Contract>();
        List<wb_Membership__c> Membership =  [ SELECT  Id,
                                              ContractCompany__r.name,
                                              BillingCompany__r.name,
                                              Currency__c
                                              FROM wb_Membership__c
                                              where ContractCompany__c=:CompID and Status__c ='確定'
                                              order by Id];
        List<Id> MID = new List<Id>();
        for (wb_Membership__c m:Membership)
            MID.add(m.Id);
        
        List<wb_MembershipDetail__c> MembershipDetail =[SELECT Id, Membership__c, MemberName__c, Individual__r.name,
                                                        WorkingCompany__r.name, 
                                                        MembershipPlan__c, MemberNo__c, MembershipStartDate__c, MembershipEndDate__c
                                                        FROM wb_MembershipDetail__c where Membership__c =:MID and Type__c != '入会金'
                                                        order by Membership__c, Id];
        integer i ;
        integer j=0;
        
        for (i = 0 ; i < Membership.size(); i ++ ){
            List<wb_MembershipDetail__c> d = new List<wb_MembershipDetail__c>();
            for (;j < MembershipDetail.size() &&
                 ( Membership[i].Id == MembershipDetail[j].Membership__c || Membership[i].Id > MembershipDetail[j].Membership__c)
                 ; j ++){
                d.add(MembershipDetail[j]);
            }
            Contracts.add( new Contract(Membership[i], d));
        }
        
        return Contracts;
    }
    

}