unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>未確定</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>CompanyEmployee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>f_NameforOrdering__c</fullName>
        <formula>VALUE(f_NameforOrderingTxt__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NameforOrdering</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Account_MDContract.cls
public class wb_Account_MDContract {
    private ApexPages.StandardController standardController;
    public Account theAccount {get; set;}
    public List<wb_Membership__c> theMemberships {get; set;}   
    public List<wb_Membership__c> theDraftContracts {get; set;}
    
    public List<wb_Membership__c> theConfirmedContracts {get; set;}

    public wb_utility_datapaging ConfirmedContractsPage {get; set;}
    public List<wb_MembershipDetail__c> theConfirmedContractDetails {get; set;}
    public wb_utility_datapaging ConfirmedContractDetailsPage {get; set;}
    
    public List<wb_Membership__c> theCancelledContracts {get; set;}
    public List<wb_MembershipDetail__c> theMembershipDetails {get; set;}
    public List<wb_Member__c> theMember {get; set;}
    
    public wb_Account_MDContract(ApexPages.StandardController stdController){
        this.standardController = stdController;
        theAccount = (Account) stdController.getRecord();
        theMemberships =  [SELECT Id, Name, Status__c, Currency__c,ContractDate__c FROM wb_Membership__c
                           where ContractCompany__c =:theAccount.id 
                           order by name desc];
    
        theDraftContracts = new List<wb_Membership__c>();
        theConfirmedContracts = new List<wb_Membership__c>();
        theCancelledContracts = new List<wb_Membership__c>();
        
        for (wb_Membership__c c:theMemberships){
            if ( c.Status__c =='未確定')
                theDraftContracts.add(c);
            if ( c.Status__c =='確定')
                theConfirmedContracts.add(c);
            if ( c.Status__c =='キャンセル')
                theCancelledContracts.add(c);
        }
   //     List<Id> MDContractID = new List<Id>();
   //     for ( wb_Membership__c m:theConfirmedContracts){
  //          MDContractID.add(m.id);
   //     }
       // theMember = new List<wb_Member__c>();
   /*     theMember = [SELECT MembershipDetail__r.Membership__r.Id,
                     MembershipDetail__r.Membership__r.name, MembershipDetail__r.name,
                     Individual__r.name, MembershipDetail__c, 
                     WorkingCompany__c, Name , MembershipDetail__r.Type__c, 
                     MembershipDetail__r.MembershipEndDate__c,
                     MembershipDetail__r.MemberNo__c
                     FROM wb_Member__c
                     where  MembershipDetail__r.Membership__r.id =:MDContractID]; */
        
        ConfirmedContractsPage = new wb_utility_datapaging(theConfirmedContracts);
        
        theConfirmedContractDetails = [SELECT Membership__r.name, name, Type__c, Individual__c, Individual__r.name, WorkingCompany__c, MembershipEndDate__c, MembershipStopDate__c
                                       FROM wb_MembershipDetail__c
                                       where Membership__r.ContractCompany__c =:theAccount.id 
                                       //Membership__r.name =:theHighlightedConfirmed 
                                       and ParentDetail__c = null 
                                       order by Membership__r.name, f_NameforOrdering__c ];
    }
	public string theHighlightedConfirmed {get; set;}
    public void GetConfirmedDetails(){
        //  system.debug('GetConfirmedDetails:' + theHighlightedConfirmed);
        
        List<wb_MembershipDetail__c> theDetail = new List<wb_MembershipDetail__c>();
        
        if (theHighlightedConfirmed.length() > 0){
            
          //  theConfirmedContractDetails = [SELECT name, Type__c, Individual__c, Individual__r.name, WorkingCompany__c, MembershipEndDate__c, MembershipStopDate__c
          //                                 FROM wb_MembershipDetail__c
         //                                  where  Membership__r.name =:theHighlightedConfirmed 
          //                                 and ParentDetail__c = null order by id];
            for (wb_MembershipDetail__c d: theConfirmedContractDetails){
              if ( d.Membership__r.name == theHighlightedConfirmed )
                  theDetail.add(d);
            }
            
        } //else
           // theConfirmedContractDetails = new List<wb_MembershipDetail__c>();
        
        ConfirmedContractDetailsPage = new wb_utility_datapaging(theDetail);
    }

    
}