unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>IndividualMDMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipStopDate__c</fullName>
        <label>会員異動日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PendingAction__c</fullName>
        <label>アクション待ち</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreviousRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the record before changes</description>
        <label>前詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細 (前詳細)</relationshipLabel>
        <relationshipName>MDMembershipNextRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Membership_Search.cls
public class wb_Membership_Search {
    string theID { get; set; }
    public string theReplaceeID { get; set; }
    public string theReplaceeIdx { get; set; }
    public string theOption { get; set; }
    public class aSelectableRow {
        public Boolean IsSelected { get; set; }
        public integer Index { get; set; }
        public wb_MembershipDetail__c theRow  { get; set; }
        
        public aSelectableRow(wb_MembershipDetail__c row, integer i){
            theRow = row;
            Index = i;
        }
    }
    
    public List<aSelectableRow> ReplacementList  { get; set; }
    
    public  wb_Membership_Search(){
        theID = ApexPages.currentPage().getParameters().get('Id');
        theReplaceeID = ApexPages.currentPage().getParameters().get('pv0');
        theReplaceeIdx = ApexPages.currentPage().getParameters().get('pv1');
        theOption = ApexPages.currentPage().getParameters().get('pv2');
    }
    
    public void getReplacementList(){
        List<wb_MembershipDetail__c> theList;
        if (theOption =='Cancellation') {
            List<wb_MembershipDetail__c> UsedList = [select PreviousRecord__c                                                   
                                                     from wb_MembershipDetail__c 
                                                     where Membership__c =:theID
                                                     and PreviousRecord__c != null];
            List<Id> UsedID = new List<Id>();
			for (wb_MembershipDetail__c l:UsedList)
                UsedID.add(l.PreviousRecord__c);
            
             theList = [select id, name, Individual__c, Individual__r.name, MembershipStopDate__c
                                                    from wb_MembershipDetail__c 
                                                    where Membership__c =:theID
                                                    and PreviousRecord__c = null and MembershipStopDate__c != null
                                                    and Individual__c != null and ParentDetail__c = null
                                                    and PendingAction__c = null and Id !=:UsedID ];
            
        } else {
            theList = [select id, name, Individual__c, Individual__r.name, MembershipStopDate__c 
                                                    from wb_MembershipDetail__c 
                                                    where Membership__c =:theID
                                                    and PreviousRecord__c = null and MembershipStopDate__c = null
                                                    and Individual__c != null and ParentDetail__c = null
                                                    and PendingAction__c = null];
        }
        ReplacementList = new List<aSelectableRow>();
        for (wb_MembershipDetail__c l:theList){
            ReplacementList.add( new aSelectableRow(l,ReplacementList.size()) );
        }
    }

}