unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>個人</relationshipLabel>
        <relationshipName>IndividualMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>雇員</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Member__c.object
<CustomObject>
    <description>WellBe Membership</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>個人</label>
        <referenceTo>wb_Individual__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MDMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>MembershipDetailMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤務会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員</relationshipLabel>
        <relationshipName>CompanyEmployeeMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会員</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MemberHistory__c.object
<CustomObject>
    <description>WellBe Membership History</description>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberType__c</fullName>
        <label>会員タイプ</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MembershipDetailHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MembershipEndDate__c</fullName>
        <label>会員終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MembershipStartDate__c</fullName>
        <label>会員開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>member__c</fullName>
        <label>会員</label>
        <referenceTo>wb_Member__c</referenceTo>
        <relationshipLabel>会員履歴</relationshipLabel>
        <relationshipName>MemberHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員履歴</label>
    <nameField>
        <label>会員履歴番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Individual_Member.cls
public class wb_Individual_Member {
    
    private ApexPages.StandardController standardController;
    public wb_Individual__c Individual {get;set;}
    
    public List<wb_member__c> Member {get;set;}
    public List<wb_MemberHistory__c> MemberHistory {get;set;}
    
    public class MemberNo{
        string MemberNo {get; set;}
        date EndDate {get; set;}
        public MemberNo(string mn, date ed){
            MemberNo =mn;
            EndDate = ed;
        }
    }
    
    public class aRow{
        public wb_member__c theRow {get; set;}
        public List<wb_MemberHistory__c> theChild {get; set;}
        public string CurrentMemberNo {get; set;}
        public List<MemberNo> MyMemberNo {get; set;}
        public aRow( wb_member__c m, List<wb_MemberHistory__c> c ){
            theRow = m;
            theChild = new List<wb_MemberHistory__c>();
            theChild = c;
            fetchMyMemberNo();
        }
        
        public void fetchMyMemberNo(){
            system.debug('fetchMyMemberNo');
            MyMemberNo = new List<MemberNo>();
            for (wb_MemberHistory__c c:theChild){
                if (MyMemberNo.size() == 0) {
                    MyMemberNo.add( new MemberNo(c.MemberNo__c, c.MembershipEndDate__c));
                }
                else {
                    boolean Add2List = false;
                    for (integer i = 0; i < MyMemberNo.size() && Add2List == false; i++ ){
                        if ( MyMemberNo[i].EndDate <  c.MembershipEndDate__c ){
                            MyMemberNo.add(i,new MemberNo(c.MemberNo__c, c.MembershipEndDate__c) );
                            Add2List = true;
                        } 
                    }
                    if (Add2List == false){
                         MyMemberNo.add(new MemberNo(c.MemberNo__c, c.MembershipEndDate__c) );
                    }
                }
            }
            if (MyMemberNo.size() > 0 ) {
                CurrentMemberNo = MyMemberNo[0].MemberNo;
            	system.debug(MyMemberNo.size() + ':' + MyMemberNo[0].MemberNo);
            }
        }
	
    }
    
    public List<aRow> theList {get;set;}
    
    public wb_Individual_Member(ApexPages.StandardController stdController){
        this.standardController = stdController;
        Individual = (wb_Individual__c) stdController.getRecord();
        Member = [select id, Name, WorkingCompany__c, MembershipDetail__c, EndDate__c 
                  from wb_member__c where Individual__c =:Individual.id];
        List<Id> MemId = new List<Id>();
        for (wb_member__c m:Member){
            MemId.add(m.id);
        }
        
        MemberHistory = [ SELECT member__c, MemberType__c, MemberNo__c, MembershipEndDate__c, MembershipStartDate__c 
                         FROM wb_MemberHistory__c 
                         where member__c =:MemId];
        
        theList = new List<aRow>();
        
        for (wb_member__c m:Member){
            List<wb_MemberHistory__c> ch = new  List<wb_MemberHistory__c>();
            for ( wb_MemberHistory__c mh:MemberHistory){
                if ( mh.member__c == m.id)
                    ch.add(mh);
            }
            theList.add(new aRow(m,ch));
           // theList[theList.size()-1].fetchMyMemberNo();
        }

    }

}