unpackaged/objects/wb_Individual__c.object
<CustomObject>
    <description>WellBe Personal Information for Individual and his Family</description>
    <label>個人</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_Service__c.object
<CustomObject>
    <description>WellBe Services Master</description>
    <fields>
        <fullName>CardPrefix__c</fullName>
        <label>カード接頭</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>データタイプ</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceFee__c</fullName>
        <label>サービス費</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>サービス</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>サービス</label>
    <nameField>
        <label>サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_Individual_Test.cls
@isTest
public class wb_Individual_Test {
    
    @isTest static void test_1(){
        Account theCompany = TestUtil.CreateCompany('ウェルビー Holding',
                                           'WellBe Holding Ltd',
                                           'アジア',
                                           '香港',
                                           '香港',
                                           '香港',
                                           'HKD');
        TestUtil.createService();
        List<wb_Service__c> s =[SELECT id, Service__c, CardPrefix__c, Currency__c, ServiceFee__c,  
                DataType__c
                FROM wb_Service__c];
        system.debug(s);
        wb_Individual__c theMember = TestUtil.createMember('A',theCompany.Id);
        
        PageReference pageRef = Page.wb_Individual_SearchAndNew;
     	pageRef.getParameters().put('pv3',  string.valueOf(theCompany.Id));
        pageRef.getParameters().put('pv4',  '2018/07/16');
        Test.setCurrentPage(pageRef);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(theMember);
        
       // wb_CarInsurance sc_a = new wb_CarInsurance(sc);
        
        wb_Individual IndMgr = new wb_Individual();
        
        IndMgr.WorkFor = theCompany;
        
        IndMgr.search();
        IndMgr.Home();
        IndMgr.Cancel();
        
        IndMgr = new wb_Individual(sc);
        IndMgr.NewFamilyMember();
        IndMgr.validateAndUpdate();
        
        
    }

}