unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>分類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>新規</fullName>
                </value>
                <value>
                    <fullName>継続</fullName>
                </value>
                <value>
                    <fullName>追加</fullName>
                </value>
                <value>
                    <fullName>交替</fullName>
                </value>
                <value>
                    <fullName>変更</fullName>
                </value>
                <value>
                    <fullName>解約変更</fullName>
                </value>
                <value>
                    <fullName>移行</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>会員氏名</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>人数</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberService</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_MembershipUtility_test.cls
@isTest
public class wb_MembershipUtility_test {
    
    @isTest static void test1(){
        List<wb_MembershipDetail__c> MembershipDetailsParent = new List<wb_MembershipDetail__c>();
        List<wb_MembershipDetail__c> MembershipDetailsChild  = new List<wb_MembershipDetail__c>();
        
        MembershipDetailsParent.add( 
            new wb_MembershipDetail__c(Classification__c='移行', Name='1', Quantity__c=1, Service__c='a0L5D0000000LYjUAM', Type__c='家族', MembershipPlan__c='Global Plus Member', MemberName__c='八木　浩道'));
        
        MembershipDetailsParent.add( 
            new wb_MembershipDetail__c(Classification__c='移行', Name='3', Quantity__c=1, Service__c='a0L5D0000000LYjUAM', Type__c='家族', MembershipPlan__c='Global Plus Member', MemberName__c='松村　浩夫'));
        
        
        MembershipDetailsChild.add(
            new wb_MembershipDetail__c(Name='1', ParentDetail__c=null,  MemberName__c='八木　美佐代', Type__c='家族', Classification__c='移行')
        );
        
        MembershipDetailsChild.add(
            new wb_MembershipDetail__c(Name='3', ParentDetail__c=null,  MemberName__c='松村　実憂', Type__c='家族', Classification__c='移行')
        );
        
        MembershipDetailsChild.add(
            new wb_MembershipDetail__c(Name='3', ParentDetail__c=null,  MemberName__c='松村　杷奈', Type__c='家族', Classification__c='移行')
        );
        
        MembershipDetailsChild.add(
            new wb_MembershipDetail__c(Name='3', ParentDetail__c=null,  MemberName__c='松村　玲子', Type__c='家族', Classification__c='移行')
        );

            
        List<wb_MembershipUtility.ChildIndex> Parent_CIndx = new List<wb_MembershipUtility.ChildIndex>();
        
        wb_MembershipUtility Helper = new wb_MembershipUtility();
        
        Parent_CIndx = Helper.bulidChildIndex(MembershipDetailsParent,MembershipDetailsChild);
        
        system.debug(MembershipDetailsParent);
        system.debug(MembershipDetailsChild);
        system.debug(Parent_CIndx);
        
        
    }

}