unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCountry__c</fullName>
        <label>契約国</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDistrict__c</fullName>
        <label>契約地区</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>MembershipPlan__c</fullName>
        <label>会員プラン</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>人数</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_rpt_MDMemberDistribution.cls
public class wb_rpt_MDMemberDistribution {
    
    public string filename{
        get{
            return 'MDMemberReport.xls';
        }
    }
    public String xlsHeader{
        get{
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
   // public AggregateResult[] RptContractArea {get;set;}
   // public AggregateResult[] RptShozoArea {get;set;}
    
    public class ReportRow{
        public string C1 {get;set;}
        public string C2 {get;set;}
        public string C3 {get;set;}
        public string C4 {get;set;}
        public string C5 {get;set;}
        public string C6 {get;set;}
        public string C7 {get;set;}
        public string C8 {get;set;}
        public string C9 {get;set;}
        public string C10 {get;set;}
        
        public ReportRow(string s1, string s2, string s3, string s4, string s5, 
                        string s6, string s7, string s8, string s9, string s10)
        {
            C1 = s1;
            C2 = s2;
            C3 = s3;
            C4 = s4;   
            C5 = s5;
            C6 = s6;
            C7 = s7;
            C8 = s8;  
            C9 = s9;
            C10 = s10;  
        }
    }
    
    public List<ReportRow> RptContractArea {get;set;}
    public List<ReportRow> RptShozoArea {get;set;}
    
    public wb_rpt_MDMemberDistribution(){
        
        AggregateResult[] Rpt = [SELECT Membership__r.ContractCountry__c ContractCountry__c, 
                           Membership__r.ContractDistrict__c ContractDistrict__c,
                                  Type__c, MembershipPlan__c,   sum(Quantity__c) Qty
                                  FROM wb_MembershipDetail__c
                                  where Type__c in ('単身','家族','無記名')
                                  group by  Membership__r.ContractCountry__c, Membership__r.ContractDistrict__c,
                                  Type__c, MembershipPlan__c];
        RptContractArea = new List<ReportRow>();
        for ( AggregateResult r:Rpt){
            RptContractArea.add( new ReportRow( String.valueOf(r.get('ContractCountry__c')),
                                               String.valueOf(r.get('ContractDistrict__c')),
                                               String.valueOf(r.get('Type__c')),
                                                String.valueOf(r.get('MembershipPlan__c')),
                                               String.valueOf(r.get('Qty')),
                                               null,null,null,null,null
                                              )
                               );
        }
        Rpt  = [SELECT Membership__r.ContractCompany__r.ShozokuArea__c ShozokuArea__c, Type__c, MembershipPlan__c,   sum(Quantity__c) Qty
                                 FROM wb_MembershipDetail__c
                                 where Type__c in ('単身','家族','無記名')
                                 group by  Membership__r.ContractCompany__r.ShozokuArea__c, 
                                 Membership__r.ContractDistrict__c,
                                 Type__c, MembershipPlan__c];
        RptShozoArea = new List<ReportRow>();
         for ( AggregateResult r:Rpt){
             RptShozoArea.add(
                 new ReportRow( String.valueOf(r.get('ShozokuArea__c')),
                               String.valueOf(r.get('Type__c')),
                               String.valueOf(r.get('MembershipPlan__c')),
                               String.valueOf(r.get('Qty')),
                               null, null,null,null,null,null
                              )
             );
         }
        
    }
}