unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_MembershipDetail_redirect.cls
public class wb_MembershipDetail_redirect {
    ApexPages.StandardController stdController;
    public wb_MembershipDetail__c wb_MembershipDetail {get;set;}
    public wb_MembershipDetail_redirect(ApexPages.StandardController stdController){
        this.stdController = stdController;
        wb_MembershipDetail = (wb_MembershipDetail__c) stdController.getRecord();
        wb_MembershipDetail = [select id, Membership__c from wb_MembershipDetail__c where id =: wb_MembershipDetail.id ];
    }
    
    public PageReference redirect() {
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        return new PageReference(sfdcBaseURL+'/apex/wb_Membership_View?Id=' + wb_MembershipDetail.Membership__c);
    }

}