unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>会社</fullName>
                </value>
                <value>
                    <fullName>個人</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_ReceivableServiceFee__c.object
<CustomObject>
    <description>WellBe Receivable</description>
    <fields>
        <fullName>CarInsurance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>自動車関連保険契約</label>
        <referenceTo>wb_CarInsurance__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>CI_Receivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>区分</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>国</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>通貨</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>作成日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>地区</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvoicingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>AccountReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>MembershipReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceAmount__c</fullName>
        <label>主商品費用</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceCommission__c</fullName>
        <label>主商品手数料</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <label>主商品名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス</label>
        <referenceTo>wb_Service__c</referenceTo>
        <relationshipLabel>売り上げ</relationshipLabel>
        <relationshipName>ServiceReceivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>総金額</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>f_Service__c</fullName>
        <formula>ServiceName__c + &apos; &apos; + OptionName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>商品</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>売り上げ</label>
        <referenceTo>wb_ReceivableServiceFee__c</referenceTo>
        <relationshipLabel>子売り上げ</relationshipLabel>
        <relationshipName>ChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>売り上げ</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>売上番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_Membership_Receivable.cls
public class wb_Membership_Receivable {
    private ApexPages.StandardController standardController;
    public wb_Membership__c Membership {get; set;}
    public List<wb_ReceivableServiceFee__c> ReceivableServiceFee {get; set;}
    
    public wb_Membership_Receivable(ApexPages.StandardController stdController){
        this.standardController = stdController;
        Membership = (wb_Membership__c) stdController.getRecord();
        
        ReceivableServiceFee = [SELECT Id, Service__c, ServiceName__c, ServiceCommission__c, ServiceAmount__c, Membership__c, Date__c, Classification__c, f_Service__c, Country__c, District__c, Name, TotalAmount__c, CarInsurance__c, parent__c, InvoicingCompany__c, Currency__c 
                                FROM wb_ReceivableServiceFee__c where Membership__c =:Membership.id ];
    }
    
}