unpackaged/objects/wb_Membership__c.object
<CustomObject>
    <description>WellBe MD Member Contract Header</description>
    <fields>
        <fullName>ApplicationDate__c</fullName>
        <label>申込日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>支払会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約（支払い）</relationshipLabel>
        <relationshipName>BillingMembershipContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約会社</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>会員契約 (契約会社)</relationshipLabel>
        <relationshipName>CompanyContract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日付</label>
        <type>Date</type>
    </fields>
    <label>会員契約</label>
    <nameField>
        <label>契約番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/wb_MembershipDetail__c.object
<CustomObject>
    <description>WellBe MD Member Contract Detail</description>
    <fields>
        <fullName>BillingAmount__c</fullName>
        <label>請求金額</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>会員氏名</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <label>会員番号</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>会員契約</label>
        <referenceTo>wb_Membership__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemberDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to the Parent Member</description>
        <label>親会員契約詳細</label>
        <referenceTo>wb_MembershipDetail__c</referenceTo>
        <relationshipLabel>会員契約詳細</relationshipLabel>
        <relationshipName>MDMemebrChildRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>人数</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>入会金</fullName>
                </value>
                <value>
                    <fullName>無記名</fullName>
                </value>
                <value>
                    <fullName>仮名</fullName>
                </value>
                <value>
                    <fullName>家族</fullName>
                </value>
                <value>
                    <fullName>単身</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnitAmount__c</fullName>
        <label>年単価</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>会員契約詳細</label>
    <nameField>
        <label>契約詳細番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/wb_Membership_Quote.cls
public class wb_Membership_Quote {
    private ApexPages.StandardController standardController;
    public wb_Membership__c Membership {get; private set; }
    
     public String getFont() {
        return font;
    }

    private static final String font = 'Arial Unicode MS' ;
        
    //controls how many quote line items are displayed on page 1
    private static Integer FIRST_BREAK = 10;
    //controls how many quote line items are displayed on subsequent pages
    private static Integer SUBSEQ_BREAKS = 20;
    
    public List<wb_MembershipDetail__c[]> pageBrokenQuoteLines {get; private set; }
    public List<wb_MembershipDetail__c> quoteLineItems {get; private set; }
    public void wb_Membership_Quote(Id MembershipID){
        
        Membership = [SELECT BillingCompany__c, ContractDate__c, ContractCompany__c, ContractCompany__r.name,
                      BillingCompany__r.name, BillingCompany__r.BillingStreet, BillingCompany__r.BillingPostalCode,
                      BillingCompany__r.BillingCity,
                      Id, Name, OwnerId, Owner.LastName, Owner.FirstName, ApplicationDate__c,
                      (select id, Type__c, name, MemberNo__c, MemberName__c, Quantity__c, UnitAmount__c, BillingAmount__c
                       from MDMemberDetail__r
                       where ParentDetail__c = null 
                      order by name)  
                      FROM wb_Membership__c where Id =:MembershipID ];
        
        quoteLineItems = Membership.MDMemberDetail__r;
        
    }
    public wb_Membership_Quote(ApexPages.StandardController stdController){
        standardController = stdController;
        
        Membership = (wb_Membership__c) stdController.getRecord();
        
        if (Membership.Id != null )
            wb_Membership_Quote(Membership.Id);
        else
            wb_Membership_Quote('a0o5D000000PJ76QAG');
        
        
    }
    /*
    private void prepareQuoteLinesForPrinting()
    {
        pageBrokenQuoteLines = new List<wb_MembershipDetail__c[]>();
        
        wb_MembershipDetail__c[] pageOfQuotes = new wb_MembershipDetail__c[]{};
            Integer counter = 0;
        
        boolean firstBreakFound = false;
        boolean setSubSeqBreak = false;        
        Integer breakPoint = FIRST_BREAK;
        
        for(wb_MembershipDetail__c q : quoteLineItems)
        {
            if(counter <= breakPoint)
            {
                pageOfQuotes.add(q);
                counter++;	
            }
            if(counter == breakPoint)
            {
                if (!firstBreakFound) 
                {
                    firstBreakFound = true;
                    setSubSeqBreak  = true;
                }
                counter = 0;
                pageBrokenQuoteLines.add(pageOfQuotes);
                pageOfQuotes.clear();
            }
            if(setSubSeqBreak) 
            {
                breakPoint = SUBSEQ_BREAKS;
                setSubSeqBreak = false;
            }
        }
        //if we have finished looping and have some quotes left let's assign them
        if(!pageOfQuotes.isEmpty())
            pageBrokenQuoteLines.add(pageOfQuotes);
    }
    */
}