unpackaged/objects/wb_soap_log__c.object
<CustomObject>
    <fields>
        <fullName>MemberID__c</fullName>
        <externalId>true</externalId>
        <label>MemberID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNo__c</fullName>
        <externalId>true</externalId>
        <label>MemberNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SOAPログ</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SOAPログ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/wb_soap_logApi_Test.cls
@isTest
public class wb_soap_logApi_Test {
    
    @isTest static void test1(){
        
        insert new wb_soap_log__c(MemberNo__c ='12345', MemberID__c='HGK') ;
        
         RestRequest request = new RestRequest();
        
        request.requestUri = 'https://cs72.salesforce.com/services/apexrest/soap/ApiLog/';
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        wb_soap_log.getApiLog();
        
    }
    
   
}